### ISSUE TITLE
angular app with crash when use custom CSS

### ISSUE THREAD

**Issue by miroslavaivanova** [NativeScript/nativescript-dev-webpack#1080]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
 - CLI: 6.1.2

**Describe the bug**
create a project and add custom CSS. When run the app you will see that it will crash.

**To Reproduce**
1. `tns create app --ng`
2. change the name `app.css` with `new.css`
3. add in main.ts 
`import * as application from "tns-core-modules/application";`
`application.setCssFileName("new.css");`
4. add in `app.components.ts` : `styleUrls:["../new.css"]`
5. change `app.css` with `new.css` in `webpack.config.js`
6. `tns run ios` and will see exception: 
`ERROR in ./new.css
Module build failed (from ../node_modules/nativescript-dev-webpack/css2json-loader.js):
Error: undefined:1:547: missing '{'
    at error (/Users/mivanova/Work/appTestnode_modules/tns-core-modules/css/lib/parse/index.js:62:15)
    at declarations (/Users/mivanova/Work/appTest/node_modules/tns-core-modules/css/lib/parse/index.js:247:25)
    at rule (/Users/mivanova/Work/appTest/node_modules/tns-core-modules/css/lib/parse/index.js:560:21)
    at rules (/Users/mivanova/Work/appTest/node_modules/tns-core-modules/css/lib/parse/index.js:117:70)
    at stylesheet (/Users/mivanova/Work/appTest/node_modules/tns-core-modules/css/lib/parse/index.js:81:21)
    at Object.module.exports [as parse] (/Users/mivanova/Work/appTest/node_modules/tns-core-modules/css/lib/parse/index.js:564:20)
    at Object.loader (/Users/mivanova/Work/appTest/node_modules/nativescript-dev-webpack/css2json-loader.js:12:23)
 @ ./app/app.component.ts 9:21-44
 @ ./app/app.module.ts
 @ ./main.ts
`
ERROR in ../node_modules/nativescript-dev-webpack/load-application-css-angular.js
Module not found: Error: Can't resolve '~/app' in '/Users/mivanova/Work/appTest/node_modules/nativescript-dev-webpack'
 @ ../node_modules/nativescript-dev-webpack/load-application-css-angular.js 5:49-65 6:47-63
 @ ./main.ts

**Expected behavior**
app should work

**Comment by riteshdalal** [comment]
Just encountered the same issue. Was there any update on this?
