### ISSUE TITLE
ERROR in this.symbolResolver.getSymbolByModule is not a function

### ISSUE THREAD

**Issue by Yamilquery** [NativeScript/nativescript-dev-webpack#114]
When I run this commands:

`sudo rm -rf node_modules/ platforms/ hooks/`

`tns run ios --bundle`

`npm run build-ios-bundle -- --release --for-device --teamId ABCDASDASD`

I'm getting this error:

```
> ns-bundle

Running webpack for ios...
Hash: 990e030681ade016ed47                                                               
Version: webpack 2.2.0
Time: 33778ms
                         Asset       Size  Chunks                    Chunk Names
                     bundle.js    2.54 MB       0  [emitted]  [big]  bundle
                    app.css.js  268 bytes       1  [emitted]         app.css
                     vendor.js    3.13 MB       2  [emitted]  [big]  vendor
                       app.css    2.04 kB       1  [emitted]         app.css
 fonts/fontawesome-webfont.ttf     166 kB          [emitted]         
fonts/fontawesome-webfont.woff      98 kB          [emitted]         
                  package.json  149 bytes          [emitted]         
                    starter.js   41 bytes          [emitted]         
   [2] ../~/@angular/core/@angular/core.es5.js 460 kB {2} [built]
   [3] ../~/@angular/router/@angular/router.es5.js 210 kB {2} [built]
  [19] ../~/@angular/http/@angular/http.es5.js 73.2 kB {2} [built]
  [20] ../~/@angular/common/@angular/common.es5.js 131 kB {2} [built]
  [22] ../~/nativescript-angular/router.js 3.1 kB {2} [built]
  [31] ../~/@angular/forms/@angular/forms.es5.js 204 kB {2} [built]
  [80] ../~/@angular/platform-browser/@angular/platform-browser.es5.js 141 kB {2} [built]
 [174] ../~/nativescript-angular/forms.js 1.46 kB {2} [built]
 [372] ./app.module.ngfactory.ts 44 kB {0} [built]
 [373] ./vendor-platform.ios.ts 61 bytes {2} [built]
 [817] ./app.css 41 bytes {1} [built]
 [818] ./main.aot.ts 466 bytes {0} [built]
 [819] ./vendor.ts 408 bytes {2} [built]
 [820] ../~/nativescript-css-loader!./platform.ios.css 412 bytes [built]
 [821] ../~/nativescript-css-loader/lib/css-base.js 1.51 kB [built]
    + 807 hidden modules

WARNING in ./app.css
  resolve-url-loader cannot operate: CSS error
  /Users/yamildiazaguirre/Documents/node/LAaps/LevenLock/levenmas/app/app.css:6:37: property missing ':'
  at error (/Users/yamildiazaguirre/Documents/node/LAaps/LevenLock/levenmas/node_modules/css/lib/parse/index.js:62:15)

ERROR in this.symbolResolver.getSymbolByModule is not a function
Child app/app.component.html:
       [0] ./app.component.html 62 bytes {0} [built]
Child app/login/login.component.html:
       [0] ./login/login.component.html 2.23 kB {0} [built]
Child app/categorias/categorias.component.html:
       [0] ./categorias/categorias.component.html 1.28 kB {0} [built]
Child app/productos/productos.component.html:
       [0] ./productos/productos.component.html 1.73 kB {0} [built]
Child app/producto_detalle/producto_detalle.component.html:
       [0] ./producto_detalle/producto_detalle.component.html 1.3 kB {0} [built]
Child app/producto_contratar/producto_contratar.component.html:
       [0] ./producto_contratar/producto_contratar.component.html 3.51 kB {0} [built]
Child app/producto_cotizar/producto_cotizar.component.html:
       [0] ./producto_cotizar/producto_cotizar.component.html 3.98 kB {0} [built]
Child app/producto_personas/producto_personas.component.html:
       [0] ./producto_personas/producto_personas.component.html 4.17 kB {0} [built]
Child app/producto_tarjeta/producto_tarjeta.component.html:
       [0] ./producto_tarjeta/producto_tarjeta.component.html 10.3 kB {0} [built]
Child app/personas_emergencia/personas_emergencia.component.html:
       [0] ./personas_emergencia/personas_emergencia.component.html 1.8 kB {0} [built]
Child app/perfil/perfil.component.html:
       [0] ./perfil/perfil.component.html 1.66 kB {0} [built]
Child app/perfil_detalle/perfil_detalle.component.html:
       [0] ./perfil_detalle/perfil_detalle.component.html 7.45 kB {0} [built]
Child app/cambiar_contrasena/cambiar_contrasena.component.html:
       [0] ./cambiar_contrasena/cambiar_contrasena.component.html 1.39 kB {0} [built]
Child app/privacidad/privacidad.component.html:
       [0] ./privacidad/privacidad.component.html 1.23 kB {0} [built]
Child app/terminos/terminos.component.html:
       [0] ./terminos/terminos.component.html 1.22 kB {0} [built]
Child app/general/general.component.html:
       [0] ./general/general.component.html 1.05 kB {0} [built]
Child app/asistencias/asistencias.component.html:
       [0] ./asistencias/asistencias.component.html 1.6 kB {0} [built]
Child app/endosos/endosos.component.html:
       [0] ./endosos/endosos.component.html 1.48 kB {0} [built]
Child app/companias/companias.component.html:
       [0] ./companias/companias.component.html 1.7 kB {0} [built]
Child app/compra/compra.component.html:
       [0] ./compra/compra.component.html 1.78 kB {0} [built]
Child app/compra_detalle/compra_detalle.component.html:
       [0] ./compra_detalle/compra_detalle.component.html 4.38 kB {0} [built]
Child app/olvide_contrasena/olvide_contrasena.component.html:
       [0] ./olvide_contrasena/olvide_contrasena.component.html 1.6 kB {0} [built]
Child app/registro/registro.component.html:
       [0] ./registro/registro.component.html 3.52 kB {0} [built]
Child app/recomendado/recomendado.component.html:
       [0] ./recomendado/recomendado.component.html 2.21 kB {0} [built]
Child app/shared/menu/menu.component.html:
       [0] ./shared/menu/menu.component.html 3.54 kB {0} [built]
Child app/shared/panico/panico.component.html:
       [0] ./shared/panico/panico.component.html 1.91 kB {0} [built]
Child app/shared/panico_guest/panico_guest.component.html:
       [0] ./shared/panico_guest/panico_guest.component.html 1.43 kB {0} [built]
Child app/login/login-common.css:
       [0] ./login/login-common.css 3.08 kB {0} [built]
Child app/login/login.component.ios.css:
       [0] ./login/login.component.ios.css 587 bytes {0} [built]
Child app/categorias/categorias-common.css:
       [0] ./categorias/categorias-common.css 2.48 kB {0} [built]
Child app/productos/productos-common.css:
       [0] ./productos/productos-common.css 349 bytes {0} [built]
Child app/producto_detalle/producto_detalle-common.css:
       [0] ./producto_detalle/producto_detalle-common.css 767 bytes {0} [built]
Child app/producto_contratar/producto_contratar-common.css:
       [0] ./producto_contratar/producto_contratar-common.css 1.97 kB {0} [built]
Child app/producto_cotizar/producto_cotizar-common.css:
       [0] ./producto_cotizar/producto_cotizar-common.css 3.76 kB {0} [built]
Child app/producto_personas/producto_personas-common.css:
       [0] ./producto_personas/producto_personas-common.css 1.2 kB {0} [built]
Child app/producto_tarjeta/producto_tarjeta-common.css:
       [0] ./producto_tarjeta/producto_tarjeta-common.css 2.97 kB {0} [built]
Child app/personas_emergencia/personas_emergencia-common.css:
       [0] ./personas_emergencia/personas_emergencia-common.css 3.31 kB {0} [built]
Child app/perfil/perfil-common.css:
       [0] ./perfil/perfil-common.css 1.53 kB {0} [built]
Child app/perfil_detalle/perfil_detalle-common.css:
       [0] ./perfil_detalle/perfil_detalle-common.css 692 bytes {0} [built]
Child app/cambiar_contrasena/cambiar_contrasena-common.css:
       [0] ./cambiar_contrasena/cambiar_contrasena-common.css 692 bytes {0} [built]
Child app/privacidad/privacidad-common.css:
       [0] ./privacidad/privacidad-common.css 3.31 kB {0} [built]
Child app/terminos/terminos-common.css:
       [0] ./terminos/terminos-common.css 3.31 kB {0} [built]
Child app/general/general-common.css:
       [0] ./general/general-common.css 642 bytes {0} [built]
Child app/asistencias/asistencias-common.css:
       [0] ./asistencias/asistencias-common.css 915 bytes {0} [built]
Child app/endosos/endosos-common.css:
       [0] ./endosos/endosos-common.css 928 bytes {0} [built]
Child app/companias/companias-common.css:
       [0] ./companias/companias-common.css 1.26 kB {0} [built]
Child app/compra/compra-common.css:
       [0] ./compra/compra-common.css 723 bytes {0} [built]
Child app/olvide_contrasena/olvide_contrasena-common.css:
       [0] ./olvide_contrasena/olvide_contrasena-common.css 978 bytes {0} [built]
Child app/compra_detalle/compra_detalle-common.css:
       [0] ./compra_detalle/compra_detalle-common.css 1.74 kB {0} [built]
Child app/registro/registro-common.css:
       [0] ./registro/registro-common.css 874 bytes {0} [built]
Child app/recomendado/recomendado-common.css:
       [0] ./recomendado/recomendado-common.css 1.97 kB {0} [built]
Child app/shared/menu/menu-common.css:
       [0] ./shared/menu/menu-common.css 1.3 kB {0} [built]
Child app/shared/panico/panico-common.css:
       [0] ./shared/panico/panico-common.css 2.52 kB {0} [built]
Child app/shared/panico_guest/panico_guest-common.css:
       [0] ./shared/panico_guest/panico_guest-common.css 2.7 kB {0} [built]
Child extract-text-webpack-plugin:
       [0] ../~/nativescript-css-loader/lib/css-base.js 1.51 kB {0} [built]
       [1] ../~/nativescript-css-loader!./platform.ios.css 412 bytes {0} [built]
       [2] ../~/resolve-url-loader!../~/nativescript-css-loader!../~/nativescript-dev-webpack/platform-css-loader.js!./app.css 2.21 kB {0} [built] [1 warning]
    
    WARNING in ../~/resolve-url-loader!../~/nativescript-css-loader!../~/nativescript-dev-webpack/platform-css-loader.js!./app.css
      resolve-url-loader cannot operate: CSS error
      /Users/yamildiazaguirre/Documents/node/LAaps/LevenLock/levenmas/app/app.css:6:37: property missing ':'
      at error (/Users/yamildiazaguirre/Documents/node/LAaps/LevenLock/levenmas/node_modules/css/lib/parse/index.js:62:15)
child process exited with code 2

npm ERR! Darwin 16.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ns-bundle" "--ios" "--start-app"
npm ERR! node v7.6.0
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ ns-bundle: `ns-bundle`
npm ERR! Exit status 2
```

In the morning it worked perfect and suddenly stopped working ...

**Comment by sis0k0** [comment]
Hey @Yamilquery,

can you share your `package.json`? I think that is related to mismatching versions of `@angular/compiler-cli` and the other @angular packages. For example, if your app depends on `@angular/core` 4.0.0 and `@angular/compiler-cli` 4.0.2, try updating all versions to ~4.0.2.

**Comment by Yamilquery** [comment]
Hi @sis0k0,

This is my package.json

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.dtech.levenmasdev",
    "tns-android": {
      "version": "2.5.0"
    },
    "tns-ios": {
      "version": "2.5.0"
    }
  },
  "dependencies": {
    "@angular/animations": "4.0.2",
    "@angular/cli": "1.0.0",
    "@angular/common": "4.0.2",
    "@angular/compiler": "4.0.2",
    "@angular/core": "4.0.2",
    "@angular/forms": "4.0.2",
    "@angular/http": "4.0.2",
    "@angular/platform-browser": "4.0.2",
    "@angular/platform-browser-dynamic": "4.0.2",
    "@angular/router": "4.0.2",
    "email-validator": "^1.0.7",
    "moment": "^2.18.1",
    "nativescript-angular": "1.5.1",
    "nativescript-gif": "^1.0.9",
    "nativescript-imagepicker": "^2.5.1",
    "nativescript-iqkeyboardmanager": "^1.0.1",
    "nativescript-phone": "^1.2.4",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-webview-interface": "^1.4.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.2.0",
    "tns-core-modules": "^2.5.2",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.0.2",
    "@ngtools/webpack": "1.2.13",
    "babel-traverse": "6.23.1",
    "babel-types": "6.23.0",
    "babylon": "6.16.1",
    "copy-webpack-plugin": "~3.0.1",
    "extract-text-webpack-plugin": "~2.0.0-beta.4",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-android-snapshot": "^0.*.*",
    "nativescript-dev-typescript": "~0.3.5",
    "nativescript-dev-webpack": "^0.3.7",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~1.6.0",
    "typescript": "~2.1.0",
    "webpack": "2.2.0",
    "webpack-sources": "~0.1.3"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --start-app",
    "start-ios-bundle": "npm run ns-bundle --ios --start-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}

```

But I still getting the same error... :(

**Comment by Yamilquery** [comment]
It worked correctly, thank you very much!
