### ISSUE TITLE
platform/android folder being cleaned

### ISSUE THREAD

**Issue by carrbrpoa** [NativeScript/nativescript-dev-webpack#157]
Hello,

I noticed that today, after I stashed the additions made by `npm install --save-dev nativescript-dev-webpack`, now `npm run start-android-bundle` throws error and seems to be cleaning gradle stuff of `platform/android` folder, leaving only `platform/android/src`:

![image](https://cloud.githubusercontent.com/assets/10212618/26218913/1ca80024-3be3-11e7-91c4-bc6fc61f3b5e.png)

Any ideas?

Thanks

**Comment by sis0k0** [comment]
The platform remove/add will be removed in the next version of the plugin. However, the above error is caused by something in the node_modules (obviously :d). Can you attach your project with the node_modules folder or at least only the node_modules?

**Comment by carrbrpoa** [comment]
Nevermind, just shared the 50MB thing with you by Drive

**Comment by carrbrpoa** [comment]
Well, today I returned to this project, deleted `platform` (which contained `/android/src` only) and it worked! By the way, once you install `nativescript-dev-webpack` in a project, it can only be ran with `npm run start-android-bundle`? Thanks

**Comment by sis0k0** [comment]
@carrbrpoa, no you can still run the project with `tns run android`, `tns debug android`, etc.

**Comment by carrbrpoa** [comment]
Hey @sis0k0,

Actually now it throws me an error when I try `tns run android`:

```
Executing before-prepare hook from C:\Android\Projetos\OSUrbApp\hooks\before-prepare\nativescript-dev-typescript.js
Found peer TypeScript 2.2.2
Preparing project...
Project successfully prepared (android)
Searching for devices...
Building project...
Picked up _JAVA_OPTIONS: -Dhttp.proxyHost=localhost -Dhttp.proxyPort=3128 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=3128
Starting a Gradle Daemon, 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
> Configuring > 0/3 projects > root project
 :config phase:  createDefaultIncludeFiles
        +found plugins: nativescript-camera
        +found plugins: nativescript-couchbase
        +found plugins: tns-core-modules-widgets

:config phase:  createPluginsConfigFile
         Creating product flavors include.gradle file in C:\Android\Projetos\OSUrbApp\platforms\android/configurations folder...
> Configuring > 0/3 projects > root project
:config phase:  pluginExtend
        +applying configuration from: C:\Android\Projetos\OSUrbApp\platforms\android\configurations\include.gradle
        +applying configuration from: C:\Android\Projetos\OSUrbApp\platforms\android\configurations\nativescript-camera\include.gradle
        +applying configuration from: C:\Android\Projetos\OSUrbApp\platforms\android\configurations\nativescript-couchbase\include.gradle
        +applying configuration from: C:\Android\Projetos\OSUrbApp\platforms\android\configurations\tns-core-modules-widgets\include.gradle
> Configuring > 0/3 projects > root project
 :config phase:  addAarDependencies
        +adding dependency: C:\Android\Projetos\OSUrbApp\platforms\android\libs\aar\widgets-release.aar
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instea
d.
Incremental java compilation is an incubating feature.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_5bv00pf0nb20m3s6smcms76uf.run(C:\Android\Projetos\OSUrbApp\platforms\android\build-tools\android-static-binding-generator\build.gradle:126)
:preBuild UP-TO-DATE
:preF0F1F2DebugBuild UP-TO-DATE
:checkF0F1F2DebugManifest
:preF0F1F2ReleaseBuild UP-TO-DATE
:prepareComAndroidSupportAnimatedVectorDrawable2531Library UP-TO-DATE
:prepareComAndroidSupportAppcompatV72531Library UP-TO-DATE
:prepareComAndroidSupportDesign2531Library UP-TO-DATE
:prepareComAndroidSupportRecyclerviewV72531Library UP-TO-DATE
:prepareComAndroidSupportSupportCompat2531Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUi2531Library UP-TO-DATE
:prepareComAndroidSupportSupportCoreUtils2531Library UP-TO-DATE
:prepareComAndroidSupportSupportFragment2531Library UP-TO-DATE
:prepareComAndroidSupportSupportMediaCompat2531Library UP-TO-DATE
:prepareComAndroidSupportSupportV42531Library UP-TO-DATE
:prepareComAndroidSupportSupportVectorDrawable2531Library UP-TO-DATE
:prepareComAndroidSupportTransition2531Library UP-TO-DATE
:prepareComCouchbaseLiteCouchbaseLiteAndroid131Library UP-TO-DATE
:prepareComCouchbaseLiteCouchbaseLiteAndroidSqliteCustom131Library UP-TO-DATE
:prepareOSUrbAppRuntimeUnspecifiedLibrary UP-TO-DATE
:prepareWidgetsReleaseLibrary UP-TO-DATE
:prepareF0F1F2DebugDependencies
:compileF0F1F2DebugAidl UP-TO-DATE
:compileF0F1F2DebugRenderscript UP-TO-DATE
:generateF0F1F2DebugBuildConfig UP-TO-DATE
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:generateTypescriptDefinitions SKIPPED
:copyTypings SKIPPED
:asbg:generateInterfaceNamesList
:asbg:traverseJsFiles
:asbg:runAstParser
Running incremental build
finished with reading lines with js files
:asbg:generateBindings
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
C:\Android\Projetos\OSUrbApp\platforms\android\src\main\java\com\tns\gen\android\content\BroadcastReceiver_frnal_ts_helpers_l58_c38__BroadcastReceiver.java
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:60)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)
Picked up _JAVA_OPTIONS: -Dhttp.proxyHost=localhost -Dhttp.proxyPort=3128 -Dhttps.proxyHost=localhost -Dhttps.proxyPort=3128
:asbg:generateBindings FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\Android\Projetos\OSUrbApp\platforms\android\build-tools\android-static-binding-generator\build.gradle' line: 251

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_40\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 32.157 secs
Multiple errors were thrown:
Command gradlew.bat failed with exit code 1
# run android
```

Any ideas?

Thanks

**Comment by carrbrpoa** [comment]
Ok, now I manage to exit that problematic situation.
This is what I've done:

`tns platform remove android` then `tns build android`. After that, could run `tns run android` normally, but I feel that whenever I do `npm run start-android-bundle` I enter in that problematic situation again.

**Comment by smarza** [comment]
Hey @carrbrpoa @sis0k0 @rbasniak

I'm getting the same kind of issue here.

```npm run ns-bundle --android --run-app```

**Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
C:\git\DEMO.APP\platforms\android\src\main\java\com\tns\gen\com\facebook\imagepipeline\animated\base\AnimatedDrawable_frnal_ts_helpers_l58_c38__AnimatedImage.java
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:59)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)
:asbg:generateBindings FAILED**

```
BUILD SUCCESSFUL

Total time: 16.049 secs
Successfully prepared plugin nativescript-angular for android.
Successfully prepared plugin nativescript-intl for android.
Successfully prepared plugin nativescript-appversion for android.
Successfully prepared plugin nativescript-audio for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Successfully prepared plugin nativescript-cardview for android.
Successfully prepared plugin nativescript-downloadmanager for android.
Successfully prepared plugin nativescript-fabric for android.
Successfully prepared plugin nativescript-fresco for android.
Successfully prepared plugin nativescript-geolocation for android.
Successfully prepared plugin nativescript-loading-indicator for android.
Successfully prepared plugin nativescript-local-notifications for android.
Successfully prepared plugin nativescript-localstorage for android.
Successfully prepared plugin nativescript-plugin-firebase for android.
Successfully prepared plugin nativescript-pulltorefresh for android.
Successfully prepared plugin nativescript-ripple for android.
Successfully prepared plugin nativescript-social-share for android.
Successfully prepared plugin nativescript-telerik-ui for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin nativescript-toast for android.
Project successfully prepared (android)
Executing after-prepare hook from C:\git\DEMO.APP\hooks\after-prepare\firebase-build-gradle.js
Configure firebase
Executing after-prepare hook from C:\git\DEMO.APP\hooks\after-prepare\firebase-copy-google-services.js
Copy C:\git\DEMO.APP\app\App_Resources\Android\google-services.json to C:\git\DEMO.APP\platforms\android\google-services.json.
Executing after-prepare hook from C:\git\DEMO.APP\hooks\after-prepare\nativescript-fabric.js
Executing after-prepare hook from C:\git\DEMO.APP\hooks\after-prepare\nativescript-plugin-firebase.js
Searching for devices...
Building project...
> Configuring > 0/3 projects > root project
 :config phase:  createDefaultIncludeFiles
        +found plugins: nativescript-cardview
Renaming plugin directory to flavor name: C:\git\DEMO.APP\platforms\android\src\nativescript-cardview -> C:\git\DEMO.APP\platforms\android\src\F0
        +found plugins: nativescript-fabric
Renaming plugin directory to flavor name: C:\git\DEMO.APP\platforms\android\src\nativescript-fabric -> C:\git\DEMO.APP\platforms\android\src\F1
        +found plugins: nativescript-fresco
Renaming plugin directory to flavor name: C:\git\DEMO.APP\platforms\android\src\nativescript-fresco -> C:\git\DEMO.APP\platforms\android\src\F2
        +found plugins: nativescript-geolocation
         + creating include.gradle file for C:\git\DEMO.APP\platforms\android\configurations\nativescript-geolocation
Renaming plugin directory to flavor name: C:\git\DEMO.APP\platforms\android\src\nativescript-geolocation -> C:\git\DEMO.APP\platforms\android\src\F3
        +found plugins: nativescript-local-notifications
         + creating include.gradle file for C:\git\DEMO.APP\platforms\android\configurations\nativescript-local-notifications
Renaming plugin directory to flavor name: C:\git\DEMO.APP\platforms\android\src\nativescript-local-notifications -> C:\git\DEMO.APP\platforms\android\src\F4
        +found plugins: nativescript-plugin-firebase
Renaming plugin directory to flavor name: C:\git\DEMO.APP\platforms\android\src\nativescript-plugin-firebase -> C:\git\DEMO.APP\platforms\android\src\F5
        +found plugins: nativescript-ripple
Renaming plugin directory to flavor name: C:\git\DEMO.APP\platforms\android\src\nativescript-ripple -> C:\git\DEMO.APP\platforms\android\src\F6
        +found plugins: nativescript-telerik-ui
Renaming plugin directory to flavor name: C:\git\DEMO.APP\platforms\android\src\nativescript-telerik-ui -> C:\git\DEMO.APP\platforms\android\src\F7
        +found plugins: tns-core-modules-widgets
         + creating include.gradle file for C:\git\DEMO.APP\platforms\android\configurations\tns-core-modules-widgets
Renaming plugin directory to flavor name: C:\git\DEMO.APP\platforms\android\src\tns-core-modules-widgets -> C:\git\DEMO.APP\platforms\android\src\F8

:config phase:  createPluginsConfigFile
         Creating product flavors include.gradle file in C:\git\DEMO.APP\platforms\android/configurations folder...

:config phase:  pluginExtend
        +applying configuration from: C:\git\DEMO.APP\platforms\android\configurations\include.gradle
        +applying configuration from: C:\git\DEMO.APP\platforms\android\configurations\nativescript-cardview\include.gradle
        +applying configuration from: C:\git\DEMO.APP\platforms\android\configurations\nativescript-fabric\include.gradle
        +applying configuration from: C:\git\DEMO.APP\platforms\android\configurations\nativescript-fresco\include.gradle
        +applying configuration from: C:\git\DEMO.APP\platforms\android\configurations\nativescript-geolocation\include.gradle
        +applying configuration from: C:\git\DEMO.APP\platforms\android\configurations\nativescript-local-notifications\include.gradle
        +applying configuration from: C:\git\DEMO.APP\platforms\android\configurations\nativescript-plugin-firebase\include.gradle
        +applying configuration from: C:\git\DEMO.APP\platforms\android\configurations\nativescript-ripple\include.gradle
        +applying configuration from: C:\git\DEMO.APP\platforms\android\configurations\nativescript-telerik-ui\include.gradle
        +applying configuration from: C:\git\DEMO.APP\platforms\android\configurations\tns-core-modules-widgets\include.gradle
> Configuring > 0/3 projects > root project
 :config phase:  addAarDependencies
        +adding dependency: C:\git\DEMO.APP\platforms\android\libs\aar\Common-2017.1.504-dev-release.aar
        +adding dependency: C:\git\DEMO.APP\platforms\android\libs\aar\Data-2017.1.504-dev-release.aar
        +adding dependency: C:\git\DEMO.APP\platforms\android\libs\aar\firebase-release.aar
        +adding dependency: C:\git\DEMO.APP\platforms\android\libs\aar\List-2017.1.504-dev-release.aar
        +adding dependency: C:\git\DEMO.APP\platforms\android\libs\aar\Primitives-2017.1.504-dev-release.aar
        +adding dependency: C:\git\DEMO.APP\platforms\android\libs\aar\widgets-release.aar
The JavaCompile.setDependencyCacheDir() method has been deprecated and is scheduled to be removed in Gradle 4.0.
The TaskInputs.source(Object) method has been deprecated and is scheduled to be removed in Gradle 4.0. Please use TaskInputs.file(Object).skipWhenEmpty() instead.
Incremental java compilation is an incubating feature.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
        at build_7bbjirkeeqx3652f6tjhtzyw5.run(C:\git\DEMO.APP\platforms\android\build-tools\android-static-binding-generator\build.gradle:126)
:createBuildID UP-TO-DATE
:preBuild UP-TO-DATE
:preF0F1F2F3F4F5F6F7F8DebugBuild UP-TO-DATE
:checkF0F1F2F3F4F5F6F7F8DebugManifest
:preF0F1F2F3F4F5F6F7F8ReleaseBuild UP-TO-DATE
:prepareAppRuntimeUnspecifiedLibrary
:prepareComAndroidSupportAnimatedVectorDrawable2531Library
:prepareComAndroidSupportAppcompatV72531Library
:prepareComAndroidSupportCardviewV72531Library
:prepareComAndroidSupportCustomtabs2531Library
:prepareComAndroidSupportDesign2531Library
:prepareComAndroidSupportRecyclerviewV72531Library
:prepareComAndroidSupportSupportCompat2531Library
:prepareComAndroidSupportSupportCoreUi2531Library
:prepareComAndroidSupportSupportCoreUtils2531Library
:prepareComAndroidSupportSupportFragment2531Library
:prepareComAndroidSupportSupportMediaCompat2531Library
:prepareComAndroidSupportSupportV42531Library
:prepareComAndroidSupportSupportVectorDrawable2531Library
:prepareComAndroidSupportTransition2531Library
:prepareComBalysvMaterialRipple102Library
:prepareComCrashlyticsSdkAndroidAnswers1311Library
:prepareComCrashlyticsSdkAndroidBeta123Library
:prepareComCrashlyticsSdkAndroidCrashlytics266Library
:prepareComCrashlyticsSdkAndroidCrashlyticsCore2315Library
:prepareComFacebookAndroidFacebookAndroidSdk4230Library
:prepareComFacebookFrescoDrawee090Library
:prepareComFacebookFrescoFbcore090Library
:prepareComFacebookFrescoFresco090Library
:prepareComFacebookFrescoImagepipeline090Library
:prepareComFacebookFrescoImagepipelineBase090Library
:prepareComGoogleAndroidGmsPlayServicesBase1026Library
:prepareComGoogleAndroidGmsPlayServicesBasement1026Library
:prepareComGoogleAndroidGmsPlayServicesTasks1026Library
:prepareComGoogleFirebaseFirebaseAnalytics1026Library
:prepareComGoogleFirebaseFirebaseAnalyticsImpl1026Library
:prepareComGoogleFirebaseFirebaseAuth1026Library
:prepareComGoogleFirebaseFirebaseCommon1026Library
:prepareComGoogleFirebaseFirebaseCore1026Library
:prepareComGoogleFirebaseFirebaseDatabase1026Library
:prepareComGoogleFirebaseFirebaseDatabaseConnection1026Library
:prepareComGoogleFirebaseFirebaseIid1026Library
:prepareComGoogleFirebaseFirebaseMessaging1026Library
:prepareComGoogleFirebaseFirebaseStorage1026Library
:prepareComGoogleFirebaseFirebaseStorageCommon1026Library
:prepareCommon20171504DevReleaseLibrary
:prepareData20171504DevReleaseLibrary
:prepareFirebaseReleaseLibrary
:prepareIoFabricSdkAndroidFabric1315Library
:prepareList20171504DevReleaseLibrary
:preparePrimitives20171504DevReleaseLibrary
:prepareWidgetsReleaseLibrary
:prepareF0F1F2F3F4F5F6F7F8DebugDependencies
:compileF0F1F2F3F4F5F6F7F8DebugAidl
:compileF0F1F2F3F4F5F6F7F8DebugRenderscript
:generateF0F1F2F3F4F5F6F7F8DebugBuildConfig
:cleanLocalAarFiles
:ensureMetadataOutDir
:collectAllJars
:setProperties
:generateTypescriptDefinitions SKIPPED
:copyTypings SKIPPED
:asbg:generateInterfaceNamesList
:asbg:traverseJsFiles
:asbg:runAstParser
Running full build
finished with reading lines with js files
:asbg:generateBindings
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
C:\git\DEMO.APP\platforms\android\src\main\java\com\tns\gen\com\facebook\imagepipeline\animated\base\AnimatedDrawable_frnal_ts_helpers_l58_c38__AnimatedImage.java
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:59)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)
:asbg:generateBindings FAILED

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\git\DEMO.APP\platforms\android\build-tools\android-static-binding-generator\build.gradle' line: 251

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_121\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1 mins 8.095 secs
Multiple errors were thrown:
Command gradlew.bat failed with exit code 1
```

Please let me know what do you think.

Thanks

**Comment by alexma01** [comment]
same problem
