### ISSUE TITLE
[Android] Execution failed for task ':processF0DebugResources'

### ISSUE THREAD

**Issue by roblav96** [NativeScript/nativescript-dev-webpack#18]
Giving this weback thing another go today and I've come across a build error on android.
## `tns run android --log trace`

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0DebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/roblav96/Library/Android/build-tools/24.0.3/aapt'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.682 secs
Error: Command /Users/roblav96/Downloads/pack/platforms/android/gradlew failed with exit code 1
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:566:15)
    at /usr/local/lib/node_modules/nativescript/lib/common/errors.js:128:33
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:84:106
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/yok.js:208:124
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/services/commands-service.js:51:55
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    at /usr/local/lib/node_modules/nativescript/lib/common/errors.js:128:33
    at Function.settle (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:249:26)
    at FiberFuture.wait (/usr/local/lib/node_modules/nativescript/node_modules/fibers/future.js:565:10)
    - - - - -
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/nativescript/lib/common/child-process.js:91:38)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```
## Info

```
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.3.0           │ 2.3.0          │ Up to date    │
│ tns-core-modules │ 2.3.0           │ 2.3.0          │ Up to date    │
│ tns-android      │ 2.3.0           │ 2.3.0          │ Up to date    │
│ tns-ios          │                 │ 2.3.0          │ Not installed │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

```
node -v
v6.5.0
```

```
Android 6.0.1
```

```
java -version
java version "1.8.0_92"
Java(TM) SE Runtime Environment (build 1.8.0_92-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.92-b14, mixed mode)
```

```
System Version: OS X 10.11.6 (15G31)
```

**Comment by hdeshev** [comment]
We released an updated version of the plugin today that offers many improvements such as resolving theme CSS files and supporting Angular AoT compilation. It's not backwards compatible, and you'll have to delete all your previous webpack configs, so that new ones get generated from the template.

Details in the [docs article](http://docs.nativescript.org/angular/tooling/bundling-with-webpack.html). I can help with migrating, if you post the app online on GitHub.

**Comment by hdeshev** [comment]
Closing this old issue. I'll reopen it, if the problem persists with the latest nativescript-cli and nativescript-dev-webpack releases.

**Comment by roblav96** [comment]
@hdeshev So far its working great! :D
