### ISSUE TITLE
[hdeshev/npm-scripts] Failed to create JavaScript extend wrapper for class 'com/tns/NativeScriptApplication'

### ISSUE THREAD

**Issue by roblav96** [NativeScript/nativescript-dev-webpack#20]
Trying out the new webpack branch `hdeshev/npm-scripts` on android and the app won't launch.

## Steps:
```
tns create sandbox
cd sandbox
tns platform add ios@next
tns platform add android@next
npm install nativescript-dev-webpack@https://github.com/NativeScript/nativescript-dev-webpack#4f3e8f3b37a66846dc258ed1c12098d5f58330c9
(set entry.bundle = './app' in webpack.common.js)
npm run start-android
```

## `tns info`
```
┌──────────────────┬────────────────────────────┬────────────────┬─────────────┐
│ Component        │ Current version            │ Latest version │ Information │
│ nativescript     │ 2.5.0-2016-10-24-6930      │ 2.3.0          │ Up to date  │
│ tns-core-modules │ 2.5.0-2016-10-24-4533      │ 2.3.0          │ Up to date  │
│ tns-android      │ 2.5.0-next-2016-10-20-1295 │ 2.3.0          │ Up to date  │
│ tns-ios          │ 2.5.0-2016-10-21-1         │ 2.3.0          │ Up to date  │
└──────────────────┴────────────────────────────┴────────────────┴─────────────┘
OSX 10.11.5
Android 6.0.1
Node 6.9.1
Java 1.8.0_92
```

## `adb-logcat`
```
10-25 02:17:58.442 18483 18483 D TNS.Java: Enabling NativeScript Debugger Agent
10-25 02:17:58.470 18483 18483 W System.err: com.tns.NativeScriptException: Failed to create JavaScript extend wrapper for class 'com/tns/NativeScriptApplication'
10-25 02:17:58.470 18483 18483 W System.err: 	at com.tns.Runtime.createJSInstanceNative(Native Method)
10-25 02:17:58.470 18483 18483 W System.err: 	at com.tns.Runtime.createJSInstance(Runtime.java:599)
10-25 02:17:58.470 18483 18483 W System.err: 	at com.tns.Runtime.initInstance(Runtime.java:577)
10-25 02:17:58.470 18483 18483 W System.err: 	at com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:152)
10-25 02:17:58.470 18483 18483 W System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:15)
10-25 02:17:58.470 18483 18483 W System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1014)
10-25 02:17:58.470 18483 18483 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4751)
10-25 02:17:58.471 18483 18483 W System.err: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
10-25 02:17:58.471 18483 18483 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
10-25 02:17:58.471 18483 18483 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-25 02:17:58.471 18483 18483 W System.err: 	at android.os.Looper.loop(Looper.java:148)
10-25 02:17:58.471 18483 18483 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
10-25 02:17:58.471 18483 18483 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-25 02:17:58.471 18483 18483 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-25 02:17:58.471 18483 18483 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-25 02:17:59.613 18483 18483 V JS      : ------> onActivityCreated: com.tns.NativeScriptActivity@cc6a36f activity.isNativeScriptActivity: true
10-25 02:17:59.744 18483 18483 D AndroidRuntime: Shutting down VM
10-25 02:17:59.744 18483 18483 E art     : invalid stream - problem with parameter iterator in /data/app/com.roblav96.sandbox-1/base.apk for method void com.tns.NativeScriptActivity.onCreate(android.os.Bundle)
10-25 02:17:59.745 18483 18483 W System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.roblav96.sandbox/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
10-25 02:17:59.745 18483 18483 W System.err: Calling js method onCreate failed
10-25 02:17:59.745 18483 18483 W System.err: Error: Failed to load Page from entry.moduleName: main-page
10-25 02:17:59.745 18483 18483 W System.err: File: "/data/data/com.roblav96.sandbox/files/app/vendor.js, line: 25660, column: 12
10-25 02:17:59.745 18483 18483 W System.err: StackTrace: 
10-25 02:17:59.745 18483 18483 W System.err: 	Frame: function:'resolvePageFromEntry', file:'/data/data/com.roblav96.sandbox/files/app/vendor.js', line: 25660, column: 19
10-25 02:17:59.745 18483 18483 W System.err: 	Frame: function:'Frame.navigate', file:'/data/data/com.roblav96.sandbox/files/app/vendor.js', line: 25733, column: 20
10-25 02:17:59.745 18483 18483 W System.err: 	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/com.roblav96.sandbox/files/app/vendor.js', line: 5792, column: 19
10-25 02:17:59.745 18483 18483 W System.err: 	Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/com.roblav96.sandbox/files/app/vendor.js', line: 15768, column: 25
10-25 02:17:59.745 18483 18483 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
10-25 02:17:59.745 18483 18483 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
10-25 02:17:59.745 18483 18483 W System.err: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
10-25 02:17:59.745 18483 18483 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
10-25 02:17:59.745 18483 18483 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
10-25 02:17:59.745 18483 18483 W System.err: 	at android.os.Looper.loop(Looper.java:148)
10-25 02:17:59.745 18483 18483 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5461)
10-25 02:17:59.746 18483 18483 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-25 02:17:59.746 18483 18483 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
10-25 02:17:59.746 18483 18483 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
10-25 02:17:59.746 18483 18483 W System.err: Caused by: com.tns.NativeScriptException: 
10-25 02:17:59.746 18483 18483 W System.err: Calling js method onCreate failed
10-25 02:17:59.746 18483 18483 W System.err: Error: Failed to load Page from entry.moduleName: main-page
10-25 02:17:59.746 18483 18483 W System.err: File: "/data/data/com.roblav96.sandbox/files/app/vendor.js, line: 25660, column: 12
10-25 02:17:59.746 18483 18483 W System.err: StackTrace: 
10-25 02:17:59.746 18483 18483 W System.err: 	Frame: function:'resolvePageFromEntry', file:'/data/data/com.roblav96.sandbox/files/app/vendor.js', line: 25660, column: 19
10-25 02:17:59.746 18483 18483 W System.err: 	Frame: function:'Frame.navigate', file:'/data/data/com.roblav96.sandbox/files/app/vendor.js', line: 25733, column: 20
10-25 02:17:59.746 18483 18483 W System.err: 	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/com.roblav96.sandbox/files/app/vendor.js', line: 5792, column: 19
10-25 02:17:59.746 18483 18483 W System.err: 	Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/com.roblav96.sandbox/files/app/vendor.js', line: 15768, column: 25
10-25 02:17:59.746 18483 18483 W System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
10-25 02:17:59.746 18483 18483 W System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1011)
10-25 02:17:59.746 18483 18483 W System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:896)
10-25 02:17:59.746 18483 18483 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:884)
10-25 02:17:59.746 18483 18483 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:868)
10-25 02:17:59.746 18483 18483 W System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:860)
10-25 02:17:59.746 18483 18483 W System.err: 	at com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
10-25 02:17:59.746 18483 18483 W System.err: 	at android.app.Activity.performCreate(Activity.java:6251)
10-25 02:17:59.746 18483 18483 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
10-25 02:17:59.746 18483 18483 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
```

**Comment by hdeshev** [comment]
That branch relies on updates to nativescript-cli and android-runtime. The problem should go away with the official 2.4 release.
