### ISSUE TITLE
iOS physical device only - app/vendor.js: Uncaught (in promise): NSErrorWrapper

### ISSUE THREAD

**Issue by jericdeleon** [NativeScript/nativescript-dev-webpack#207]
Hi, I am using nativescript-dev-webpack 0.7.1 with nativescript-angular 3.1.1 with the default webpack.config.js; so far, each of the below attempts works as follows:

Android emulator (`tns run android --emulator`): works fine
Android device (`tns run android --device`): works fine
Android emulator (`npm run start-android-bundle --snapshot`): works fine
Android device (`npm run start-android-bundle --snapshot`): works fine

iOS emulator (`tns run ios --emulator`): works fine
iOS device (`tns run ios --device`): works fine
iOS emulator (`npm run start-ios-bundle --snapshot`): works fine
iOS device (`npm run start-ios-bundle --snapshot`): error

While running the webpack bundle on a physical iOS device, my app stops with the ff. log:

```
Successfully installed on device with identifier '9cc0218e36d58add225bdf57898b8d39387da457'.
Starting...
Successfully run application org.nativescript.safely on device with ID 9cc0218e36d58add225bdf57898b8d39387da457.
Successfully started on device with identifier '9cc0218e36d58add225bdf57898b8d39387da457'.
CONSOLE LOG file:///app/vendor.js:4221:20: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
CONSOLE LOG file:///app/bundle.js:25898:24: firebase.init done
CONSOLE ERROR file:///app/vendor.js:2259:24: ERROR Error: Uncaught (in promise): NSErrorWrapper: You don\M-b\M^@\M^Yt have permission to save the file \M-b\M^@\M^\assets\M-b\M^@\M^] in the folder \M-b\M^@\M^\app\M-b\M^@\M^].
```

Do you know why this is happening, and how I can possibly resolve it?
I can't even read the file paths being flagged

(if you need parts of the code, just relay)

**Comment by mikraus94** [comment]
Hi @lorcanfurey ,

I've resolve this issue by adding my data folder to webpack.config.js

` new CopyWebpackPlugin([
            { from: mainSheet },
            { from: "css/**" },
            { from: "fonts/**" },
            { from: "**/*.jpg" },
            { from: "**/*.png" },
            { from: "**/*.xml" },
            { from: "data/**" },
        ], { ignore: ["App_Resources/**"] }),`

I hope it will help you.

**Comment by MilosStanic** [comment]
I have the same error, but unfortunately, the trick that helped @mikraus94 didn't help me. 

In my case the app works in all cases except when ran on physical iphone 7 and on physical android device when ran with `npm run start-ios-bundle --uglify` and `npm run start-android-bundle --uglify --snapshot`, respectively. Application works in all cases in ios and android emulators and runs on iphone and android physical devices when ran with `tns run ios` or `tns run android` or `tns debug ios` or `tns debug android`. 
In case of iPhone 7, I'm getting the same error as @jericdeleon , and the application doesn't crash, but I can't navigate to the main part of my app after I load some data from server. 
In case of Android device, application crashes with console message: 
```
10-09 13:00:45.021 11068 11068 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
10-09 13:00:45.021 11068 11068 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.TokenBindingManagerAdapter>
10-09 13:00:45.031 11068 11068 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
10-09 13:00:45.031 11068 11068 I art     : Rejecting re-init on previously-failed class java.lang.Class<com.android.webview.chromium.ServiceWorkerControllerAdapter>
System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/org.nativescript.UnisApp/shared_prefs/WebViewChromiumPrefs.xml.bak
chromium: [INFO:library_loader_hooks.cc(136)] Chromium logging enabled: level = 0, default verbosity = 0
10-09 13:00:45.261 11068 11068 I cr_BrowserStartup: Initializing chromium process, singleProcess=true
```
I also have the detailed crash log: 
```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to resume activity {org.nativescript.UnisApp/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
Calling js method onStart failed

Error: java.lang.NullPointerException: Attempt to invoke virtual method 'android.graphics.drawable.Drawable android.graphics.drawable.Drawable$ConstantState.newDrawable(android.content.res.Resources)' on a null object reference
    android.graphics.drawable.LayerDrawable$ChildDrawable.<init>(LayerDrawable.java:1721)
    android.graphics.drawable.LayerDrawable$LayerState.<init>(LayerDrawable.java:1792)
    android.graphics.drawable.RippleDrawable$RippleState.<init>(RippleDrawable.java:999)
    android.graphics.drawable.RippleDrawable.<init>(RippleDrawable.java:1042)
    android.graphics.drawable.RippleDrawable.<init>(RippleDrawable.java:96)
    android.graphics.drawable.RippleDrawable$RippleState.newDrawable(RippleDrawable.java:1023)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
    com.tns.Runtime.callJSMethod(Runtime.java:953)
    com.tns.Runtime.callJSMethod(Runtime.java:937)
    com.tns.Runtime.callJSMethod(Runtime.java:929)
    com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:38)
    android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1266)
    android.app.Activity.performStart(Activity.java:6916)
    android.app.Activity.performRestart(Activity.java:6975)
    android.app.Activity.performResume(Activity.java:6980)
    android.app.ActivityThread.performResumeActivity(ActivityThread.java:4146)
    android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4251)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:158)
    android.app.ActivityThread.main(ActivityThread.java:7230)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
File: "file:///data/data/org.nativescript.UnisApp/files/app/vendor.js, line: 539, column: 10636

StackTrace: 
	Frame: function:'View.(anonymous function)', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 539, column: 10637
	Frame: function:'E', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 1156, column: 13657
	Frame: function:'e', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 1156, column: 12760
	Frame: function:'t.onResumeNativeUpdates', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 12322
	Frame: function:'t._resumeNativeUpdates', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3527
	Frame: function:'t.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3035
	Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 539, column: 1343
	Frame: function:'t.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/0.js', line: 1741, column: 413
	Frame: function:'', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3169
	Frame: function:'t.eachChildView', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2298, column: 2546
	Frame: function:'t.eachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2128, column: 13025
	Frame: function:'t._loadEachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3145
	Frame: function:'t.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3063
	Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 539, column: 1343
	Frame: function:'', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3169
	Frame: function:'t.eachChildView', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2298, column: 2546
	Frame: function:'t.eachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2128, column: 13025
	Frame: function:'t._loadEachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3145
	Frame: function:'t.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3063
	Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 539, column: 1343
	Frame: function:'', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3169
	Frame: function:'t.eachChildView', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2298, column: 2546
	Frame: function:'t.eachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2128, column: 13025
	Frame: function:'t._loadEachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3145
	Frame: function:'t.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3063
	Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 539, column: 1343
	Frame: function:'', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3169
	Frame: function:'t.eachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2398, column: 1322
	Frame: function:'t._loadEachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3145
	Frame: function:'t.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3063
	Frame: function:'', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3169
	Frame: function:'', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2398, column: 3011
	Frame: function:'r.eachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2398, column: 2989
	Frame: function:'t._loadEachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3145
	Frame: function:'t.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3063
	Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 539, column: 1343
	Frame: function:'', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3169
	Frame: function:'t.eachChildView', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2298, column: 2546
	Frame: function:'t.eachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2128, column: 13025
	Frame: function:'t._loadEachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3145
	Frame: function:'t.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3063
	Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 539, column: 1343
	Frame: function:'', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3169
	Frame: function:'r.eachChildView', file:'file:///data/data/org.nativescript.UnisApp/files/app/bundle.js', line: 266, column: 3185
	Frame: function:'t.eachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2128, column: 13025
	Frame: function:'t._loadEachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3145
	Frame: function:'t.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3063
	Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 539, column: 1343
	Frame: function:'e.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/bundle.js', line: 111, column: 658
	Frame: function:'', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3169
	Frame: function:'t.eachChildView', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2298, column: 2546
	Frame: function:'t.eachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2128, column: 13025
	Frame: function:'t._loadEachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3145
	Frame: function:'t.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3063
	Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 539, column: 1343
	Frame: function:'', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3169
	Frame: function:'t.eachChildView', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 1436, column: 1194
	Frame: function:'t.eachChildView', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2288, column: 5128
	Frame: function:'t.eachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2128, column: 13025
	Frame: function:'t._loadEachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3145
	Frame: function:'t.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3063
	Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 539, column: 1343
	Frame: function:'t.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2288, column: 1822
	Frame: function:'Page.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 778, column: 2944
	Frame: function:'', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3169
	Frame: function:'r.eachChildView', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2113, column: 7388
	Frame: function:'t.eachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2128, column: 13025
	Frame: function:'t._loadEachChild', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3145
	Frame: function:'t.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2148, column: 3063
	Frame: function:'View.onLoaded', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 539, column: 1343
	Frame: function:'e.onStart', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 604, column: 12301
	Frame: function:'NativeScriptActivity.onStart', file:'file:///data/data/org.nativescript.UnisApp/files/app/vendor.js', line: 2803, column: 809


	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4157)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4251)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1840)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:158)
	at android.app.ActivityThread.main(ActivityThread.java:7230)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
Caused by: com.tns.NativeScriptException: 
Calling js method onStart failed
```

**Comment by kikoseijo** [comment]
ITs not a solution, but been trying to bundle the app same you did, using webpack and had same problem, found out that the simulator shows info on the OSX console.

#### some tips:

* webpack does not bundle all CSS around, and I guess its doing same with images in your case are the  resources. `newDrawable(android.content.res.Resources)' on a null object reference`
* all packages must be directly included in the ***bundle-config.ts***
* Webpack does not like include("telerick-ui/thing"); must be used as a import thing from variations.

```
global.registerModule("nativescript-pro-ui/sidedrawer",
        () => require("../node_modules/nativescript-pro-ui/sidedrawer"));
```


Hope something lights the bolt!
Im my case the console gave me enough info using ios.

![screen shot 2017-10-10 at 04 03 31](https://user-images.githubusercontent.com/1528668/31366322-9e5909e8-ad70-11e7-9276-cca3f36e49d1.png)

**Comment by MilosStanic** [comment]
Meanwhile, by disabling components, I have established that the error on Android was coming from the FAB plugin, where setting background color in CSS was breaking the app on Android. Removing background color from CSS fixed the issue on Android. However, the issue remains on IOS. 

The solution @kikoseijo suggested with bundle-config.ts only applies to TypeScript version of Nativescript. This file doesn't exist in the Angular version that I'm using. 

I will keep trying and report results here.

**Comment by MilosStanic** [comment]
Okay, so, as the error message says, there was a problem writing 'assets' folder into 'app' folder on the device. 

I wonder why it took me 20 days to realize there actually was an 'assets' folder in my 'app' folder and it contained `fontawesome.css` file. 

So, as @mikraus94 said in his message, all I had to do was add 
``` 
{ from: "assets/**"},
```
 to my `CopyWebpackPlugin` declaration in the `webpack.config.js` file, and it all worked fine.

Thank you all.

**Comment by kikoseijo** [comment]
Move to React-Native, and say bye to all this silly problems.
I don't say {N} its not good, but its ***"a little brother"*** from React-Native.

And let me know what you think.

**Comment by Burgov** [comment]
@MilosStanic my symptoms were different - didn't try on iOS, but on Android, the icons simply disappeared. Your solution solved that for me, thanks!
