### ISSUE TITLE
TypeError: viewClass is not a constructor

### ISSUE THREAD

**Issue by caferrari** [NativeScript/nativescript-dev-webpack#225]
After building the project with Webpack + AOT i've got this error when the app starts:

```shell
Successfully installed on device with identifier '0012041599'.
Starting...
Successfully started on device with identifier '0012041599'.
JS: Angular is running in the development mode. Call enableProdMode() to enable the production mode.
JS: firebase.init done
JS: ERROR Error: Uncaught (in promise): TypeError: viewClass is not a constructor
JS: TypeError: viewClass is not a constructor
JS:     at ViewUtil.module.exports.ViewUtil.createView (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:54572:20)
JS:     at EmulatedRenderer.module.exports.NativeScriptRenderer.createElement (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:54189:30)
JS:     at EmulatedRenderer.module.exports.EmulatedRenderer.createElement (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:54435:51)
JS:     at DebugRenderer2.module.exports.DebugRenderer2.createElement (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:13756:49)
JS:     at createElement (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:9834:27)
JS:     at createViewNodes (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:12523:44)
JS:     at callViewAction (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:13009:13)
JS:     at execComponentViewsAction (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:12918:13)
JS:     at createViewNodes (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:12592:5)
JS:     at createRootView (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:12470:5)
JS:     at callWithDebugContext (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:13685:42)
JS:     at Object.debugCreateRootView [as createRootView] (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:13145:12)
JS:     at ComponentFactory_.module.exports.ComponentFactory_.create (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:10391:46)
JS:     at ComponentFactoryBoundToModule.module.exports.ComponentFactoryBoundToModule.create (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:3927:29)
JS:     at ViewContainerRef_.module.exports.ViewContainerRef_.createComponent (file:///data/data/br.com.abrafarma.eventos/files/app/vendor.js:10593:62)

```

My package.json:

```json
{
  "description": "NativeScript Application",
  "license": "",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "br.com.abrafarma.eventos",
    "tns-android": {
      "version": "3.1.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "nativescript-angular": "~3.1.0",
    "nativescript-cardview": "^2.0.2",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-plugin-firebase": "4.0.3",
    "nativescript-ripple": "^2.0.0",
    "nativescript-telerik-ui": "^3.0.1",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.1.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.1.0",
    "@ngtools/webpack": "~1.5.0",
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.17.4",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-sass": "^1.2.0",
    "nativescript-dev-typescript": "~0.5.0",
    "nativescript-dev-webpack": "^0.7.3",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "tslib": "^1.7.1",
    "typescript": "~2.3.4",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}

```

**Comment by caferrari** [comment]
Was another problem =/

**Comment by r0zar** [comment]
Since it's been like 8 months im guessing you don't remember what the problem/fix was?

**Comment by weijyewang** [comment]
I too just got this problem. @caferrari please share with us your solution

**Comment by luckyape** [comment]
@caferrari worst. resolution. ever. what was the other problem?

**Comment by Egor3f** [comment]
> 
> 
> Was another problem =/

Гори в аду, ублюдок

**Comment by ebewley** [comment]
Since the content of this issue is ENTIRELY USELESS, can you please have it removed so that people do not waste their time following unnecessary links in attempting to resolve similar issues?
Thanks
