### ISSUE TITLE
"Zone Already Loaded" error when building with --snapshot param

### ISSUE THREAD

**Issue by codeback** [NativeScript/nativescript-dev-webpack#230]
I'm getting this error when running the following command:
```
npm run ns-bundle --android --build-app --snapshot
```

I changed app/vendor-platform.android.ts file according to this [comment](https://github.com/NativeScript/nativescript-dev-webpack/issues/196#issuecomment-311525883) with no luck.

Please, see below my package.json and the error stack trace
```
{
  "name": "hoppin",
  "version": "0.4.0",
  "nativescript": {
    "id": "app.hoppin.hoppinDev",
    "tns-ios": {
      "version": "3.0.1"
    },
    "tns-android": {
      "version": "3.1.1"
    }
  },
  "scripts": {
    "preinstall": "mkdirp app",
    "clean": "rimraf platforms node_modules lib hooks app && mkdirp app",
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app --snapshot",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app --snapshot",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  },
  "dependencies": {
    "@angular/animations": "~4.1.2",
    "@angular/common": "~4.1.2",
    "@angular/compiler": "~4.1.2",
    "@angular/core": "~4.1.2",
    "@angular/forms": "~4.1.2",
    "@angular/http": "~4.1.2",
    "@angular/platform-browser": "~4.1.2",
    "@angular/router": "~4.1.2",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^2.0.3",
    "@ngrx/store": "^2.2.2",
    "@ngx-translate/core": "^6.0.1",
    "@ngx-translate/http-loader": "0.0.3",
    "angulartics2": "^2.2.2",
    "lodash": "^4.17.4",
    "nativescript-angular": "~3.1.1",
    "nativescript-bottombar": "^3.0.5",
    "nativescript-cardview": "^2.0.2",
    "nativescript-master-technology": "^1.1.1",
    "nativescript-ngx-slides": "^0.2.5",
    "nativescript-plugin-firebase": "^4.0.4",
    "nativescript-telerik-ui-pro": "^3.0.3",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.5",
    "ngrx-store-freeze": "0.1.9",
    "reflect-metadata": "^0.1.8",
    "rxjs": "~5.4.0",
    "tns-core-modules": "^3.1.0",
    "url": "0.10.3",
    "zone.js": "^0.8.10"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.1.2",
    "@ngrx/store-devtools": "~3.2.4",
    "@ngtools/webpack": "~1.5.0",
    "@types/jasmine": "2.5.41",
    "@types/lodash": "4.14.63",
    "babel-traverse": "6.20.0",
    "babel-types": "6.20.0",
    "babylon": "6.14.1",
    "codelyzer": "^3.0.1",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "fs-extra": "^0.30.0",
    "glob": "^7.0.5",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-sass": "^1.1.1",
    "nativescript-dev-webpack": "^0.7.3",
    "opener": "^1.4.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "rimraf": "^2.5.3",
    "tar.gz": "^1.0.5",
    "tns-platform-declarations": "^3.0.1",
    "tslint": "^5.2.0",
    "typescript": "~2.3.4",
    "webpack": "~3.2.0",
    "webpack-sources": "~1.0.1",
    "webpack-bundle-analyzer": "^2.8.2"
  }
}

``` 

```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

Error: Zone already loaded.
File: "file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js, line: 23, column: 8

StackTrace: 
	Frame: function:'ZoneAwareError', file:'<embedded>', line: 64213, column: 33
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 23, column: 15
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1321, column: 3
	Frame: function:'NO_ZONE.name', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 9, column: 65
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 12, column: 2
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform-common.js', line: 6, column: 1
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform.js', line: 3, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/app.js', line: 4, column: 18
	Frame: function:'require', file:'', line: 1, column: 266


Error: Zone already loaded.
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'ZoneAwareError', file:'<embedded>', line: 64213, column: 33
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 23, column: 15
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1321, column: 3
	Frame: function:'NO_ZONE.name', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 9, column: 65
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 12, column: 2
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform-common.js', line: 6, column: 1
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform.js', line: 3, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/app.js', line: 4, column: 18
	Frame: function:'require', file:'', line: 1, column: 266


Error: Zone already loaded.
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'ZoneAwareError', file:'<embedded>', line: 64213, column: 33
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 23, column: 15
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1321, column: 3
	Frame: function:'NO_ZONE.name', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 9, column: 65
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 12, column: 2
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform-common.js', line: 6, column: 1
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform.js', line: 3, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/app.js', line: 4, column: 18
	Frame: function:'require', file:'', line: 1, column: 266


Error: Zone already loaded.
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'ZoneAwareError', file:'<embedded>', line: 64213, column: 33
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 23, column: 15
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1321, column: 3
	Frame: function:'NO_ZONE.name', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 9, column: 65
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 12, column: 2
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform-common.js', line: 6, column: 1
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform.js', line: 3, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/app.js', line: 4, column: 18
	Frame: function:'require', file:'', line: 1, column: 266


Error: Zone already loaded.
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'ZoneAwareError', file:'<embedded>', line: 64213, column: 33
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 23, column: 15
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1321, column: 3
	Frame: function:'NO_ZONE.name', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 9, column: 65
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 12, column: 2
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform-common.js', line: 6, column: 1
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform.js', line: 3, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/app.js', line: 4, column: 18
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4731)
	at android.app.ActivityThread.-wrap1(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1415)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error calling module function 

Error calling module function 

Error: Zone already loaded.
File: "file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js, line: 23, column: 8

StackTrace: 
	Frame: function:'ZoneAwareError', file:'<embedded>', line: 64213, column: 33
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 23, column: 15
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1321, column: 3
	Frame: function:'NO_ZONE.name', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 9, column: 65
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 12, column: 2
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform-common.js', line: 6, column: 1
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform.js', line: 3, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/app.js', line: 4, column: 18
	Frame: function:'require', file:'', line: 1, column: 266


Error: Zone already loaded.
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'ZoneAwareError', file:'<embedded>', line: 64213, column: 33
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 23, column: 15
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1321, column: 3
	Frame: function:'NO_ZONE.name', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 9, column: 65
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 12, column: 2
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform-common.js', line: 6, column: 1
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform.js', line: 3, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/app.js', line: 4, column: 18
	Frame: function:'require', file:'', line: 1, column: 266


Error: Zone already loaded.
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'ZoneAwareError', file:'<embedded>', line: 64213, column: 33
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 23, column: 15
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1321, column: 3
	Frame: function:'NO_ZONE.name', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 9, column: 65
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 12, column: 2
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform-common.js', line: 6, column: 1
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform.js', line: 3, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/app.js', line: 4, column: 18
	Frame: function:'require', file:'', line: 1, column: 266


Error: Zone already loaded.
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'ZoneAwareError', file:'<embedded>', line: 64213, column: 33
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 23, column: 15
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1321, column: 3
	Frame: function:'NO_ZONE.name', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 9, column: 65
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 12, column: 2
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform-common.js', line: 6, column: 1
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform.js', line: 3, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/app.js', line: 4, column: 18
	Frame: function:'require', file:'', line: 1, column: 266


Error: Zone already loaded.
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'ZoneAwareError', file:'<embedded>', line: 64213, column: 33
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 23, column: 15
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1321, column: 3
	Frame: function:'NO_ZONE.name', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 9, column: 65
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 12, column: 2
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform-common.js', line: 6, column: 1
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/tns_modules/nativescript-angular/platform.js', line: 3, column: 25
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/app.hoppin.hoppinDev/files/app/app.js', line: 4, column: 18
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:521)
	at com.tns.Runtime.run(Runtime.java:513)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:19)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1036)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4728)
	... 8 more
```

**Comment by sis0k0** [comment]
Hey, @codeback. We'll need some additional information about your project to find the root of the problem here. First of all, can you share the full log of the build (but without using uglify flag). Lifehack if you're using linux/mac (which is probably the case cause you are building with snapshot) -
```
npm run start-android-bundle --snapshot | tee log.txt
```

That will print the log on the console and save it ton a file named log.txt in the cwd, too.
Also can you please share your webpack.config.js, app/vendor.ts and app/vendor-platform.ts.

Thanks in advance!

**Comment by codeback** [comment]
Thank you @sis0k0 for your response, 

The error is different if I run build-android-bundle or if i run start-android-bundle. With the first one I'm getting the "Zone Already Loaded" error and with the start-android-bundle I'm getting "webpackJsonp is not defined".

Please find here the requested files:
[files.zip](https://github.com/NativeScript/nativescript-dev-webpack/files/1161504/files.zip)

**Comment by sis0k0** [comment]
@codeback,

That's pretty odd (the different errors). According to the log, the snapshot generation is successful. Will you be able to email me the project or to write in the community slack?

**Comment by codeback** [comment]
@sis0k0, I've just sent you an invitation to the repo so you can check it.

Thanks in advance

**Comment by codeback** [comment]
Hi @sis0k0,

The error "Zone Already Loaded" was due to a plugin (nativescript-master-technology), I've removed it and now it is working. 

The error "webpackJsonp is not defined" is only shown if I run start-android-bundle in the emulator. When I run it in a device, it is working. 

It's not a big problem for me since I will run the --snapshot param only when I want build a release version.

Thank you very much for your help.

**Comment by manojdcoder** [comment]
@sis0k0 I'm running into same issue with snapshot on device.

> webpackJsonp is not defined

**Comment by manojdcoder** [comment]
@sis0k0 When I compared the complied `vendor.js` with and without snapshot, I could see that when built without snapshot `vendor.js` defines the function `webpackJsonp` in the very first line, something like `global["webpackJsonp"]=...` but when built with snapshot `vendor.js` is empty and `tns-java-classes.js` tries to use `webpackJsonp` function which throws en error. 

Does this give you any idea what could be wrong here?

**Comment by sis0k0** [comment]
@manojdcoder,

Can you open another issue and post your package.json and the full build log there. My suggestion is that the snapshot generation may fail. But, I think it's better to move the discussion to another thread.

**Comment by manojdcoder** [comment]
@sis0k0 Created #247, with steps to reproduce the issue.

**Comment by eloiqs** [comment]
Sorry for pinging you guys, this issue is kind of old and my problem is a bit different, but I just wanted to say that I had some "zone already loaded" problems, and I fixed it by `rm -rf node_modules && npm install`. Just wanted to leave that here in case someone else tries searching for "nativescript zone already loaded" on google, as this issue is the only result that comes up. I think it might be caused by some ngcc issues after cancelling the postinstall script in my terminal.
