### ISSUE TITLE
2.4.0 Breaks Webpack without Nativescript-dev-android-snapshot (Android)

### ISSUE THREAD

**Issue by vbresults** [NativeScript/nativescript-dev-webpack#25]
Ping @atanasovg @jasssonpet @hdeshev this seems to be related to the new snapshot system which I have not installed explicitly, but this must be happening due to runtime changes.

---

Removed the platform, added 2.4.0, and installed tns-core-modules@2.4.0.

Using the stock/template webpack.config.js, without nativescript-dev-android-snapshot:
```
D/TNS.Native( 3009): Failed to load snapshot: dlopen failed: library "libsnapshot.so" not found
D/TNS.Native( 3009): V8 version 5.2.361
D/TNS.Native( 3009): lenNodes=83964, lenNames=850548, lenValues=994948
D/TNS.Native( 3009): time=1
D/TNS.Java( 3009): Enabling NativeScript Debugger Agent
D/AndroidRuntime( 3009): Shutting down VM
E/art     ( 3009): invalid stream - problem with parameter iterator in /data/app/com.example.app-1/base.apk for method void com.tns.NativeScriptActivity.onCreate(android.os.Bundle)
W/System.err( 3009): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.app/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
W/System.err( 3009): Calling js method onCreate failed
W/System.err( 3009): [object Object]
W/System.err( 3009): File: "/data/data/com.example.app/files/app/tns-java-classes.js, line: 21798, column: 21
W/System.err( 3009): StackTrace: 
W/System.err( 3009): 	Frame: function:'', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 21798, column: 22
W/System.err( 3009): 	Frame: function:'', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 22409, column: 14
W/System.err( 3009): 	Frame: function:'EasySAXParser.parse', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 23276, column: 24
W/System.err( 3009): 	Frame: function:'XmlParser.parse', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 22456, column: 23
W/System.err( 3009): 	Frame: function:'XmlStringParser.parse', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 21804, column: 28
W/System.err( 3009): 	Frame: function:'parseInternal', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 21679, column: 12
W/System.err( 3009): 	Frame: function:'loadInternal', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 21756, column: 28
W/System.err( 3009): 	Frame: function:'load', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 21735, column: 32
W/System.err( 3009): 	Frame: function:'pageFromBuilder', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 1691, column: 28
W/System.err( 3009): 	Frame: function:'resolvePageFromEntry', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 1669, column: 21
W/System.err( 3009): 	Frame: function:'Frame.navigate', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 1745, column: 21
W/System.err( 3009): 	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 1466, column: 20
W/System.err( 3009): 	Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 31519, column: 26
W/System.err( 3009): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
W/System.err( 3009): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
W/System.err( 3009): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
W/System.err( 3009): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
W/System.err( 3009): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 3009): 	at android.os.Looper.loop(Looper.java:135)
W/System.err( 3009): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err( 3009): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 3009): 	at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 3009): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/System.err( 3009): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/System.err( 3009): Caused by: com.tns.NativeScriptException: 
W/System.err( 3009): Calling js method onCreate failed
W/System.err( 3009): [object Object]
W/System.err( 3009): File: "/data/data/com.example.app/files/app/tns-java-classes.js, line: 21798, column: 21
W/System.err( 3009): StackTrace: 
W/System.err( 3009): 	Frame: function:'', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 21798, column: 22
W/System.err( 3009): 	Frame: function:'', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 22409, column: 14
W/System.err( 3009): 	Frame: function:'EasySAXParser.parse', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 23276, column: 24
W/System.err( 3009): 	Frame: function:'XmlParser.parse', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 22456, column: 23
W/System.err( 3009): 	Frame: function:'XmlStringParser.parse', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 21804, column: 28
W/System.err( 3009): 	Frame: function:'parseInternal', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 21679, column: 12
W/System.err( 3009): 	Frame: function:'loadInternal', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 21756, column: 28
W/System.err( 3009): 	Frame: function:'load', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 21735, column: 32
W/System.err( 3009): 	Frame: function:'pageFromBuilder', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 1691, column: 28
W/System.err( 3009): 	Frame: function:'resolvePageFromEntry', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 1669, column: 21
W/System.err( 3009): 	Frame: function:'Frame.navigate', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 1745, column: 21
W/System.err( 3009): 	Frame: function:'ActivityCallbacksImplementation.onCreate', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 1466, column: 20
W/System.err( 3009): 	Frame: function:'NativeScriptActivity.onCreate', file:'/data/data/com.example.app/files/app/tns-java-classes.js', line: 31519, column: 26
W/System.err( 3009): 	at com.tns.Runtime.callJSMethodNative(Native Method)
W/System.err( 3009): 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1022)
W/System.err( 3009): 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:907)
W/System.err( 3009): 	at com.tns.Runtime.callJSMethod(Runtime.java:895)
W/System.err( 3009): 	at com.tns.Runtime.callJSMethod(Runtime.java:879)
W/System.err( 3009): 	at com.tns.Runtime.callJSMethod(Runtime.java:871)
W/System.err( 3009): 	at com.tns.NativeScriptActivity.onCreate(android.app.Activity.java)
W/System.err( 3009): 	at android.app.Activity.performCreate(Activity.java:5990)
W/System.err( 3009): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
W/System.err( 3009): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
W/System.err( 3009): 	... 10 more
```

With nativescript-dev-android-snapshot, it works.

**Comment by vbresults** [comment]
@hdeshev Installing nativescript-dev-android-snapshot fixes the problem.  But I am not using snapshots, so what to do :?

**Comment by jasssonpet** [comment]
Hey @vbresults, can you check that your XML pages are valid. I receive the same stack trace (line numbers probably shifted somehow) when there is a syntax error in some of the pages.
