### ISSUE TITLE
it tip:"Error: Cannot find module '../package.json'"when i enter command "tns --version" in window cmd

### ISSUE THREAD

**Issue by bright999** [NativeScript/nativescript-dev-webpack#270]
D:\demos\nativescript\ns-stock-ticker\app>tns --version
module.js:471
    throw err;
    ^
Error: Cannot find module '../package.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\AppData\Roaming\npm\node_modules\natives
cript\bin\tns:5:43)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

os:window 7
 node --version
v6.11.3

 npm -v
3.10.10----C:\Program Files\nodejs\node_modules\npm

 npm show angular-cli version
1.0.0-beta.28.3

npm show nativescript version
3.2.0

webpack --version
3.5.6

**Comment by bright999** [comment]
I fix it !  Because my nativescript is bad.so I delete the dir nativescript(C:\Users\AppData\Roaming\npm\node_modules\nativescript),then reinstall the nativescript using the command "npm i -g nativescript" in window cmd.finally it works well !
