### ISSUE TITLE
android build failed with command npm run start-android-bundle

### ISSUE THREAD

**Issue by Kunoacc** [NativeScript/nativescript-dev-webpack#272]
When i try to bundle, the build fails and i get this in the logs

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Novateur\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build-android-bundle' ]
2 info using npm@4.1.1
3 info using node@v8.3.0
4 verbose run-script [ 'prebuild-android-bundle',
4 verbose run-script   'build-android-bundle',
4 verbose run-script   'postbuild-android-bundle' ]
5 info lifecycle @~prebuild-android-bundle: @
6 silly lifecycle @~prebuild-android-bundle: no script for prebuild-android-bundle, continuing
7 info lifecycle @~build-android-bundle: @
8 verbose lifecycle @~build-android-bundle: unsafe-perm in lifecycle true
9 verbose lifecycle @~build-android-bundle: PATH: C:\Users\Novateur\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\Users\Novateur\Documents\tns-soji\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\ProgramData\ComposerSetup\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\wkhtmltopdf\bin;C:\Program Files\nodejs;C:\Program Files (x86)\Java\jdk1.8.0_121\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\ProgramData\ComposerSetup\bin;C:\ProgramData\chocolatey\bin;C:\Program Files\wkhtmltopdf\bin;C:\Program Files\nodejs;C:\Program Files (x86)\Java\jdk1.8.0_121\bin;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files (x86)\Microsoft Emulator Manager\1.0\;C:\Program Files\PuTTY\;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\Ruby23\bin;C:\Users\Novateur\AppData\Roaming\Composer\vendor\bin;C:\Users\Novateur\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Microsoft VS Code\bin;C:\Program Files (x86)\Java\jre1.8.0_121\bin;C:\Program Files\Heroku\bin;C:\Program Files (x86)\Android\android-sdk\tools;C:\Program Files (x86)\Android\android-sdk\platform-tools;C:\xampp\php;C:\Users\Novateur\AppData\Local\Fusetools\Fuse\App\Bin;C:\Program Files\Java\jdk1.8.0_131\bin;C:\Users\Novateur\AppData\Local\Programs\Fiddler;C:\Users\Novateur\AppData\Roaming\npm;C:\Users\Novateur\AppData\Local\Yarn\bin
10 verbose lifecycle @~build-android-bundle: CWD: C:\Users\Novateur\Documents\tns-soji
11 silly lifecycle @~build-android-bundle: Args: [ '/d /s /c', 'npm run ns-bundle --android --build-app' ]
12 silly lifecycle @~build-android-bundle: Returned: code: 1  signal: null
13 info lifecycle @~build-android-bundle: Failed to exec build-android-bundle script
14 verbose stack Error: @ build-android-bundle: `npm run ns-bundle --android --build-app`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\Novateur\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\Novateur\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:927:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid @
16 verbose cwd C:\Users\Novateur\Documents\tns-soji
17 error Windows_NT 10.0.15063
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Novateur\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build-android-bundle"
19 error node v8.3.0
20 error npm  v4.1.1
21 error code ELIFECYCLE
22 error @ build-android-bundle: `npm run ns-bundle --android --build-app`
22 error Exit status 1
23 error Failed at the @ build-android-bundle script 'npm run ns-bundle --android --build-app'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run ns-bundle --android --build-app
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by NickIliev** [comment]
@Kunoacc the provided info is not enough to fully investigate and reproduce the issue.
At this very moment the nativescript-dev-webpack has released new version - migrating guide can be found [here](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade)

Closing due to inactivity.
