### ISSUE TITLE
npm run start-{platform}-bundle fails on start up

### ISSUE THREAD

**Issue by jpgilchrist** [NativeScript/nativescript-dev-webpack#291]
This is a project I created with SideKick. I chose the blank JS template (not TS or Angular).

 Also running it without webpack seems to work fine.

The bundle seems to build correctly, but starting the bundle fails... 

Here's the android StackTrace:

```
Successfully started on device with identifier 'emulator-5554'.
10-12 17:36:32.483 23510 23510 E AndroidRuntime:        at com.tns.Runtime.callJSMethodNative(Native Method)
10-12 17:36:32.483 23510 23510 E AndroidRuntime:        at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
10-12 17:36:32.483 23510 23510 E AndroidRuntime:        at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
10-12 17:36:32.483 23510 23510 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:953)
10-12 17:36:32.483 23510 23510 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:937)
10-12 17:36:32.483 23510 23510 E AndroidRuntime:        at com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err: com.tns.NativeScriptException:
System.err: Calling js method onAnimationEnd failed
System.err:
System.err: TypeError: Cannot set property setTimeout of #<NativeScriptGlobalObject> which has only a getter
System.err: File: "file:///data/data/com.veoci.mobile/files/app/vendor.js, line: 92, column: 578
System.err:
System.err: StackTrace:
System.err:     Frame: function:'global.moduleMerge', file:'file:///data/data/com.veoci.mobile/files/app/vendor.js', line: 92, column: 579
System.err:     Frame: function:'get', file:'file:///data/data/com.veoci.mobile/files/app/vendor.js', line: 92, column: 1742
System.err:     Frame: function:'transitionOrAnimationCompleted', file:'file:///data/data/com.veoci.mobile/files/app/vendor.js', line: 778, column: 19692
System.err:     Frame: function:'AnimationListnerImpl.onAnimationEnd', file:'file:///data/data/com.veoci.mobile/files/app/vendor.js', line: 778, column: 10534
System.err:
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1084)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:966)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:953)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:937)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:929)
System.err:     at com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__AnimationListnerImpl.onAnimationEnd(Object_frnal_ts_helpers_l58_c38__AnimationListnerImpl.java:32)
System.err:     at android.animation.AnimatorSet.endAnimation(AnimatorSet.java:1293)
System.err:     at android.animation.AnimatorSet.doAnimationFrame(AnimatorSet.java:1079)
System.err:     at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
System.err:     at android.animation.AnimationHandler.-wrap2(Unknown Source:0)
System.err:     at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:909)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:723)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:655)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
System.err:     at android.os.Handler.handleCallback(Handler.java:789)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:98)
System.err:     at android.os.Looper.loop(Looper.java:164)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6541)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
ActivityManager: Process com.veoci.mobile (pid 23510) has died: fore TOP
ActivityManager: setHasOverlayUi called on unknown pid: 23510
```

Here's the iOS StackTrace:
```
Successfully started on device with identifier 'BF254262-DC9F-4F32-AEA0-E3B092615CD6'.
1   0x10ead7bf8 -[TNSRuntime executeModule:referredBy:]
2   0x10e639c61 main
3   0x1130f665d start
4   0x1
file:///app/vendor.js:122:418: JS ERROR TypeError: Attempted to assign to readonly property.
Oct 12 17:50:29 bitmeister com.apple.CoreSimulator.SimDevice.BF254262-DC9F-4F32-AEA0-E3B092615CD6.launchd_sim[26958] (UIKitApplication:com.veoci.mobile[0x1619][26984][43609]): Service exited due to Segmentation fault: 11
```

Here's my package.json:

```javascript
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.veoci.mobile",
    "tns-android": {
      "version": "3.2.0"
    },
    "tns-ios": {
      "version": "3.2.0"
    }
  },
  "dependencies": {
    "lodash": "4.17.4",
    "nativescript-theme-core": "1.0.4",
    "tns-core-modules": "3.2.0"
  },
  "devDependencies": {
    "babel-cli": "6.26.0",
    "babel-preset-es2015": "6.24.1",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-babel": "^0.1.6",
    "nativescript-dev-webpack": "0.8.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
```

**Comment by NickIliev** [comment]
Hello @jpgilchrist 

I have created blank JS project using SideKick and then using the exact same configuration as in your `package.json` the project was successfully bundled with Webpack.

[Here you can find the demo project](https://github.com/NickIliev/NS-Issues/tree/master/nativescript-dev-webpack/issue_291_sidekick) I have created and used in the process.

Please do let me know if there is any additional code added to your blank template and also you can try to clone my project and test if the WebPack bundling is successful at your side.

**Comment by jpgilchrist** [comment]
@NickIliev cloning your repo, switching directories to `NS-Issues/nativescript-dev-webpack/issue_291_sidekick` and running

``` bash
npm install
npm run start-android-bundle
``` 
did the trick.

However, I would love to know how and why. Did you perform the steps in a specific order? Could doing them out of order cause an issue? I removed all the "unnecessary" files/folders in my project to most closely match yours (I also removed the report folder from each) and ran a diff on the directories; here's the output:

``` bash
$ diff -rq . ~/Development/greywall/git/VeociMobile/
Only in /Users/jpegz/Development/greywall/git/VeociMobile/: .babelrc
Only in /Users/jpegz/Development/greywall/git/VeociMobile/: .git
Only in /Users/jpegz/Development/greywall/git/VeociMobile/: .gitignore
Only in /Users/jpegz/Development/greywall/git/VeociMobile/: .vscode
Files ./app/App_Resources/Android/AndroidManifest.xml and /Users/jpegz/Development/greywall/git/VeociMobile/app/App_Resources/Android/AndroidManifest.xml differ
Files ./app/App_Resources/Android/app.gradle and /Users/jpegz/Development/greywall/git/VeociMobile/app/App_Resources/Android/app.gradle differ
Files ./app/App_Resources/Android/settings.json and /Users/jpegz/Development/greywall/git/VeociMobile/app/App_Resources/Android/settings.json differ
Files ./app/App_Resources/iOS/Info.plist and /Users/jpegz/Development/greywall/git/VeociMobile/app/App_Resources/iOS/Info.plist differ
Files ./app/App_Resources/iOS/build.xcconfig and /Users/jpegz/Development/greywall/git/VeociMobile/app/App_Resources/iOS/build.xcconfig differ
Files ./app/home/home-page.js and /Users/jpegz/Development/greywall/git/VeociMobile/app/home/home-page.js differ
Files ./app/references.d.ts and /Users/jpegz/Development/greywall/git/VeociMobile/app/references.d.ts differ
Files ./package.json and /Users/jpegz/Development/greywall/git/VeociMobile/package.json differ
```

``` bash
$ diff ./app/App_Resources/Android/AndroidManifest.xml /Users/jpegz/Development/greywall/git/VeociMobile/app/App_Resources/Android/AndroidManifest.xml
3c3
<     xmlns:android="http://schemas.android.com/apk/res/android" package="__PACKAGE__" android:versionCode="1" android:versionName="1.0">
---
>     xmlns:android="http://schemas.android.com/apk/res/android" package="__PACKAGE__" android:versionCode="1" android:versionName="0.0.1">
```

``` bash
$ diff ./app/App_Resources/Android/app.gradle /Users/jpegz/Development/greywall/git/VeociMobile/app/App_Resources/Android/app.gradle
11c11
<     applicationId = "org.nativescript.issue291sidekick" 
---
>     applicationId = "com.veoci.mobile" 
```

``` bash
$ diff ./app/App_Resources/Android/settings.json  /Users/jpegz/Development/greywall/git/VeociMobile/app/App_Resources/Android/settings.json
1c1
< {"appId":"org.nativescript.issue291sidekick","minSdkVersion":null,"targetSdkVersion":null}
\ No newline at end of file
---
> {"appId":"com.veoci.mobile","minSdkVersion":null,"targetSdkVersion":null}
\ No newline at end of file
```

``` bash
$ diff ./app/App_Resources/iOS/Info.plist /Users/jpegz/Development/greywall/git/VeociMobile/app/App_Resources/iOS/Info.plist
4,47c4,47
< <dict>
< 	<key>CFBundleDevelopmentRegion</key>
< 	<string>en</string>
< 	<key>CFBundleDisplayName</key>
< 	<string>${PRODUCT_NAME}</string>
< 	<key>CFBundleExecutable</key>
< 	<string>${EXECUTABLE_NAME}</string>
< 	<key>CFBundleInfoDictionaryVersion</key>
< 	<string>6.0</string>
< 	<key>CFBundleName</key>
< 	<string>${PRODUCT_NAME}</string>
< 	<key>CFBundlePackageType</key>
< 	<string>APPL</string>
< 	<key>CFBundleShortVersionString</key>
< 	<string>1.0</string>
< 	<key>CFBundleSignature</key>
< 	<string>????</string>
< 	<key>CFBundleVersion</key>
< 	<string>1.0</string>
< 	<key>LSRequiresIPhoneOS</key>
< 	<true/>
< 	<key>UILaunchStoryboardName</key>
< 	<string>LaunchScreen</string>
< 	<key>UIRequiresFullScreen</key>
< 	<true/>
< 	<key>UIRequiredDeviceCapabilities</key>
< 	<array>
< 		<string>armv7</string>
< 	</array>
< 	<key>UISupportedInterfaceOrientations</key>
< 	<array>
< 		<string>UIInterfaceOrientationPortrait</string>
< 		<string>UIInterfaceOrientationLandscapeLeft</string>
< 		<string>UIInterfaceOrientationLandscapeRight</string>
< 	</array>
< 	<key>UISupportedInterfaceOrientations~ipad</key>
< 	<array>
< 		<string>UIInterfaceOrientationPortrait</string>
< 		<string>UIInterfaceOrientationPortraitUpsideDown</string>
< 		<string>UIInterfaceOrientationLandscapeLeft</string>
< 		<string>UIInterfaceOrientationLandscapeRight</string>
< 	</array>
< </dict>
< </plist>
---
> 	<dict>
> 		<key>CFBundleDevelopmentRegion</key>
> 		<string>en</string>
> 		<key>CFBundleDisplayName</key>
> 		<string>${PRODUCT_NAME}</string>
> 		<key>CFBundleExecutable</key>
> 		<string>${EXECUTABLE_NAME}</string>
> 		<key>CFBundleInfoDictionaryVersion</key>
> 		<string>6.0</string>
> 		<key>CFBundleName</key>
> 		<string>${PRODUCT_NAME}</string>
> 		<key>CFBundlePackageType</key>
> 		<string>APPL</string>
> 		<key>CFBundleShortVersionString</key>
> 		<string>0.0.1</string>
> 		<key>CFBundleSignature</key>
> 		<string>????</string>
> 		<key>CFBundleVersion</key>
> 		<string>0.0.1</string>
> 		<key>LSRequiresIPhoneOS</key>
> 		<true/>
> 		<key>UILaunchStoryboardName</key>
> 		<string>LaunchScreen</string>
> 		<key>UIRequiresFullScreen</key>
> 		<true/>
> 		<key>UIRequiredDeviceCapabilities</key>
> 		<array>
> 			<string>armv7</string>
> 		</array>
> 		<key>UISupportedInterfaceOrientations</key>
> 		<array>
> 			<string>UIInterfaceOrientationLandscapeLeft</string>
> 			<string>UIInterfaceOrientationLandscapeRight</string>
> 			<string>UIInterfaceOrientationPortrait</string>
> 		</array>
> 		<key>UISupportedInterfaceOrientations~ipad</key>
> 		<array>
> 			<string>UIInterfaceOrientationLandscapeLeft</string>
> 			<string>UIInterfaceOrientationLandscapeRight</string>
> 			<string>UIInterfaceOrientationPortrait</string>
> 			<string>UIInterfaceOrientationPortraitUpsideDown</string>
> 		</array>
> 	</dict>
> </plist>
\ No newline at end of file
```

``` bash
$ diff ./app/App_Resources/iOS/build.xcconfig /Users/jpegz/Development/greywall/git/VeociMobile/app/App_Resources/iOS/build.xcconfig
3c3
< // CODE_SIGN_IDENTITY = iPhone Distribution
---
> // CODE_SIGN_IDENTITY = iPhone Distribution 
5c5
< // DEVELOPMENT_TEAM = YOUR_TEAM_ID
---
> // DEVELOPMENT_TEAM = YOUR_TEAM_ID;
8d7
< TARGETED_DEVICE_FAMILY = 1;
```

``` bash
$ diff ./app/home/home-page.js /Users/jpegz/Development/greywall/git/VeociMobile/app/home/home-page.js
12,13d11
< var frameModule = require("ui/frame");
< var HomeViewModel = require("./home-view-model");
15c13,16
< var homeViewModel = new HomeViewModel();
---
> var frameModule = require('ui/frame')
> var HomeViewModel = require('./home-view-model')
> 
> var homeViewModel = new HomeViewModel()
44c45
< exports.onNavigatingTo = onNavigatingTo;
\ No newline at end of file
---
> exports.onNavigatingTo = onNavigatingTo;
```

``` bash
$ diff ./app/references.d.ts /Users/jpegz/Development/greywall/git/VeociMobile/app/references.d.ts
1c1
< /// <reference path="../node_modules/tns-core-modules/tns-core-modules.d.ts" /> Enable smart suggestions and completions in Visual Studio Code JavaScript projects.
---
> /// <reference path="../node_modules/tns-core-modules/tns-core-modules.d.ts" />
```

``` bash
$ diff ./package.json /Users/jpegz/Development/greywall/git/VeociMobile/package.json
7c7
<     "id": "org.nativescript.issue291sidekick",
---
>     "id": "com.veoci.mobile",
```

**Comment by jpgilchrist** [comment]
Oh and here's my .babelrc since it's the only real difference:
``` javascript
{
    "presets": [
        "es2015"
    ]
}
```

**Comment by jpgilchrist** [comment]
After removing everything such as node_modules, platforms, .babelrc (seemingly clean slate) running

``` bash
npm install
npm run start-android-bundle
```

still resulted in the same error.

**Comment by jpgilchrist** [comment]
I don't know if it matters, but I did add babel before I added webpack:

``` bash
tns install babel
``` 
per: https://docs.nativescript.org/tooling/transpilers

Then later followed the best practices suggestions per: https://docs.nativescript.org/best-practices/bundling-with-webpack

``` bash
$ npm install --save-dev nativescript-dev-webpack
$ npm install
```

**Comment by jpgilchrist** [comment]
@NickIliev I added .babelrc with presets es2015 and I hit the same issue in your "clean" project. In fact, I just double checked on a completely clean clone of your repo (i.e., deleted and re-cloned). 

Here's my command history:
``` bash
  600  git clone https://github.com/NickIliev/NS-Issues.git
  601  cd NS-Issues/nativescript-dev-webpack/
  602  ls
  603  cd issue_291_sidekick/
  604  ls
  605  vim .babelrc
  606  vim .babelrc
  607  npm install
  608  npm run start-android-bundle
```

Resulting in the exact same StackTrace!

**Comment by jpgilchrist** [comment]
Apologies for the immense amount of comments, but I was able to get it working in my branch as well with the following commands:

``` bash
$ rm .babelrc
$ rm platforms
$ npm run start-android-bundle
```

**Comment by jpgilchrist** [comment]
@NickIliev where do we go from here? I want to make sure this get's the right eyes on it. Is this a nativescript-dev-webpack or babel issue?

**Comment by NickIliev** [comment]
@jpgilchrist I have j8sut retested your case using the latest nativescript-dev-webpack and there is a successful build. You can test with by following [this migration guide](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade)
