### ISSUE TITLE
Webpack + RadListView from nativescript-pro-ui

### ISSUE THREAD

**Issue by gabitoesmiapodo** [NativeScript/nativescript-dev-webpack#294]
I'm having an issue where I can't build my project if I try to use the RadListView component on it.

The Webpack build or run throws this:

```
Running full build
finished with reading lines with js files
Exception in thread "main" java.lang.ClassNotFoundException: Class: android.support.v7.widget.RecyclerView$Adapter
        at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:709)
        at org.nativescript.staticbindinggenerator.Generator.collectInterfaceMethods(Generator.java:675)
        at org.nativescript.staticbindinggenerator.Generator.getPublicApi(Generator.java:212)
        at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:326)
        at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:117)
        at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:157)
        at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:77)
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:54)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/development/Sites/ba-mascotas-mobile/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 277

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java'' finished with non-zero exitvalue 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Command ./gradlew failed with exit code 1


```
I've read several other issues where the component is mentioned (and tried their fixes), and some say that it could be that it is being imported twice.

This is not the case, I only have it imported once on app.module.ts

Snippet:

```
(...)

import { NativeScriptFacebookModule } from "nativescript-facebook/angular";
import { NativeScriptUISideDrawerModule } from "nativescript-pro-ui/sidedrawer/angular";
import { NativeScriptUIListViewModule } from "nativescript-pro-ui/listview/angular";
import { NativeScriptLocalizeModule } from "nativescript-localize/angular";

// Routing
const routes = [
    ...authRoutes,
    {
        path: "main",
        loadChildren: "./modules/main/main.module#MainModule",
    }
];

const routing = NativeScriptRouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules });

@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        // Modules
        NativeScriptModule,
        NativeScriptRouterModule,
        NativeScriptLocalizeModule,
        NativeScriptUISideDrawerModule,
        NativeScriptUIListViewModule,
        AuthModule,
        routing
    ],
    declarations: [
        AppComponent
    ],
    entryComponents: [

    ],
    providers: [
        AuthGuard,
        AuthService,
        AuthStorageService,
        {
            provide: NgModuleFactoryLoader,
            useClass: NSModuleFactoryLoader
        }
    ],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class AppModule { }

```

The only other place where the component is mentioned is in another one where I actually use the RadListView.

I tried removing all the references to RadListView you can see below, but it fixed nothing.

It may be worth mentioning that this component is in a module which is lazily loaded.

```
import { Component, OnInit, AfterViewInit, ViewChild } from "@angular/core";
import * as platform from "platform";
import { localize } from "nativescript-localize";
import { RouterExtensions, PageRoute } from "nativescript-angular/router";
import { ObservableArray } from "tns-core-modules/data/observable-array";
import { ListViewEventData, ListViewScrollEventData } from "nativescript-pro-ui/listview";
import { RadListViewComponent } from "nativescript-pro-ui/listview/angular";

@Component({
    moduleId: module.id,
    selector: "the-list-component",
    templateUrl: "./the-list.component.html"
})
export class TheListomponent implements OnInit, AfterViewInit {

    @ViewChild("listView") listView : RadListViewComponent;

    (...)

}
```

Being that I could be duplicating code, I added these lines to vendor.ts but it made no difference.

```
require("nativescript-pro-ui/listview");
require("nativescript-pro-ui/sidedrawer")
require("nativescript-pro-ui/listview/angular");
require("nativescript-pro-ui/sidedrawer/angular");
```

My package.json looks like this

```
{
  "license": "LicenseRef-LICENSE",
  "readme": "README",
  "nativescript": {
    "id": "com.xxxxxx.xxxxxxxx",
    "tns-android": {
      "version": "3.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.4.1",
    "@angular/common": "~4.4.1",
    "@angular/compiler": "~4.4.1",
    "@angular/core": "~4.4.1",
    "@angular/forms": "~4.4.1",
    "@angular/http": "~4.4.1",
    "@angular/platform-browser": "~4.4.1",
    "@angular/router": "~4.4.1",
    "moment": "^2.18.1",
    "nativescript-angular": "4.4.1",
    "nativescript-camera": "^3.1.2",
    "nativescript-custom-entitlements": "^0.2.0",
    "nativescript-facebook": "^2.0.1",
    "nativescript-geolocation": "4.1.1",
    "nativescript-image-cache": "^1.0.8",
    "nativescript-imagepicker": "^3.0.7",
    "nativescript-iqkeyboardmanager": "1.1.0",
    "nativescript-localize": "^2.0.1",
    "nativescript-ngx-slides": "^0.4.3",
    "nativescript-permissions": "^1.2.3",
    "nativescript-phone": "^1.3.1",
    "nativescript-pro-ui": "^3.1.4",
    "nativescript-ripple": "^2.0.0",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toast": "^1.4.6",
    "reflect-metadata": "~0.1.8",
    "rxjs": "^5.0.1",
    "tns-core-modules": "^3.2.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.4.1",
    "@ngtools/webpack": "~1.6.0",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-sass": "^1.3.2",
    "nativescript-dev-typescript": "~0.4.0",
    "nativescript-dev-webpack": "^0.8.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "typescript": "~2.3.4",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}

```

If I try to build without Wepack (that is: 'tns build android ...'), it builds and runs normally.

If I completely remove the RadListView component and build using Webpack, it also builds and runs normally. In fact I was making my test builds normally with Webpack until I found this problem.

Anyway, any leads on this?

**Comment by NickIliev** [comment]
@gabitoesmiapodo tried to reproduce the issue but to no avail. I have created [this project ](https://github.com/NickIliev/NS-Issues/tree/master/nativescript-dev-webpack/issue_294)using your dependency versioning for all third-party plugin and at the same time using the latest versions of all angular dependencies.

To make sure that you have proper WebPack configuration follow these steps:
- in your project delete `webpack.config.js`
- run `npm install` and make sure that the file `wbpack.config.js` is recreated
- run 'npm run start-android-bundle'

The project should be bundled successfully.

Some things you should also consider:
- the RadListView module should be imported in the lazily loaded module where it is used 

lazyloaded.module.ts
```
import { NativeScriptUIListViewModule } from "nativescript-pro-ui/listview/angular";

...
imports: [ NativeScriptUIListViewModule ]
```

**Comment by gabitoesmiapodo** [comment]
Thanks @NickIliev , I found a solution by sheer luck, and it seems it had nothing to do with Webpack.

I'll leave it here if anyone encounters the same problem.

It looks it is necessary to add this to app.gradle to make RadListView work on a physical device (at least on mine):

```
dependencies {
    def supportVer = "22.2.0";
	if (project.hasProperty("supportVersion")) {
		supportVer = supportVersion
	}

	compile "com.android.support:recyclerview-v7:$supportVer"
}
```

Supposedly it should be added to app.gradle automatically by nativescript-pro-ui, but for some reason that isn't happening.

**Comment by VladimirAmiorkov** [comment]
Hi @gabitoesmiapodo , 

Thank you for you input, we have already resolve this issue in the nativescript-pro-ui@next version, to test it simply do:

`tns plugin add nativescript-pro-ui@next`

**Comment by gabitoesmiapodo** [comment]
Great, thank you!
