### ISSUE TITLE
Errors while running app

### ISSUE THREAD

**Issue by madsongr** [NativeScript/nativescript-dev-webpack#305]
I created a new project with `tns create NSAngular` and made no modifications to test if I get the same errors after installing webpack and the boring errors werer there again:

```
Project successfully created.
Executing before-prepare hook from D:\Mobile Develop\NativeScript\NSAngular\hooks\before-prepare\nativescript-dev-typescript.js
Preparing project...
Successfully prepared plugin nativescript-angular for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin nativescript-intl for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Gradle build...

 :config phase:  createDefaultIncludeFiles

 :config phase:  addAarDependencies
        +adding dependency: D:\Mobile Develop\NativeScript\NSAngular\platforms\android\libs\aar\widgets-release.aar
Project successfully prepared (android)
Running webpack for android...
Hash: f307bbf284caf3d9196e
Version: webpack 3.2.0
Time: 26490ms
              Asset       Size  Chunks                    Chunk Names
          bundle.js    62.9 kB       0  [emitted]         bundle
         app.css.js     5.1 kB       1  [emitted]         app.css
          vendor.js    3.07 MB       2  [emitted]  [big]  vendor
            app.css  515 bytes          [emitted]
       package.json  149 bytes          [emitted]
         starter.js   39 bytes          [emitted]
tns-java-classes.js    0 bytes          [emitted]
  [37] ./item/item.service.ts 1.59 kB {0} [built]
  [71] ./item/items.component.ts 858 bytes {0} [built]
  [72] ./item/item-detail.component.ts 801 bytes {0} [built]
 [119] .. lazy 160 bytes {2} [built]
 [127] ./app.component.ts 264 bytes {0} [built]
 [164] ./main.aot.ts 471 bytes {0} [built]
 [210] ./app.module.ngfactory.ts 7.06 kB {0} [built]
 [211] ./app.module.ts 655 bytes {0} [built]
 [213] ./item/items.component.ngfactory.ts 7.71 kB {0} [built]
 [251] ./item/item-detail.component.ngfactory.ts 4.78 kB {0} [built]
 [252] ./app.component.ngfactory.ts 2.98 kB {0} [built]
 [258] ./app.routing.ts 646 bytes {0} [built]
 [259] ./vendor.ts 405 bytes {2} [built]
 [260] ./vendor-platform.android.ts 466 bytes {2} [built]
 [275] ./app.css 4.88 kB {1} [built] [failed] [1 error]
    + 261 hidden modules

ERROR in ./app.css
Module build failed: BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`
    at error (D:\Mobile Develop\NativeScript\NSAngular\node_modules\browserslist\index.js:37:11)
    at D:\Mobile Develop\NativeScript\NSAngular\node_modules\browserslist\index.js:222:9
    at Array.forEach (native)
    at browserslist (D:\Mobile Develop\NativeScript\NSAngular\node_modules\browserslist\index.js:196:13)
    at cleanBrowsersList (D:\Mobile Develop\NativeScript\NSAngular\node_modules\caniuse-api\dist\utils.js:56:59)
    at setBrowserScope (D:\Mobile Develop\NativeScript\NSAngular\node_modules\caniuse-api\dist\index.js:29:43)
    at Object.<anonymous> (D:\Mobile Develop\NativeScript\NSAngular\node_modules\caniuse-api\dist\index.js:91:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Mobile Develop\NativeScript\NSAngular\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:7:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Mobile Develop\NativeScript\NSAngular\node_modules\postcss-merge-rules\dist\index.js:21:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

ERROR in ./app.css
Module build failed: ModuleBuildError: Module build failed: BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`
    at error (D:\Mobile Develop\NativeScript\NSAngular\node_modules\browserslist\index.js:37:11)
    at D:\Mobile Develop\NativeScript\NSAngular\node_modules\browserslist\index.js:222:9
    at Array.forEach (native)
    at browserslist (D:\Mobile Develop\NativeScript\NSAngular\node_modules\browserslist\index.js:196:13)
    at cleanBrowsersList (D:\Mobile Develop\NativeScript\NSAngular\node_modules\caniuse-api\dist\utils.js:56:59)
    at setBrowserScope (D:\Mobile Develop\NativeScript\NSAngular\node_modules\caniuse-api\dist\index.js:29:43)
    at Object.<anonymous> (D:\Mobile Develop\NativeScript\NSAngular\node_modules\caniuse-api\dist\index.js:91:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Mobile Develop\NativeScript\NSAngular\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:7:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\Mobile Develop\NativeScript\NSAngular\node_modules\postcss-merge-rules\dist\index.js:21:28)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at runLoaders (D:\Mobile Develop\NativeScript\NSAngular\node_modules\webpack\lib\NormalModule.js:193:19)
    at D:\Mobile Develop\NativeScript\NSAngular\node_modules\loader-runner\lib\LoaderRunner.js:364:11
    at D:\Mobile Develop\NativeScript\NSAngular\node_modules\loader-runner\lib\LoaderRunner.js:170:18
    at loadLoader (D:\Mobile Develop\NativeScript\NSAngular\node_modules\loader-runner\lib\loadLoader.js:27:11)
    at iteratePitchingLoaders (D:\Mobile Develop\NativeScript\NSAngular\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at iteratePitchingLoaders (D:\Mobile Develop\NativeScript\NSAngular\node_modules\loader-runner\lib\LoaderRunner.js:165:10)
    at D:\Mobile Develop\NativeScript\NSAngular\node_modules\loader-runner\lib\LoaderRunner.js:173:18
    at loadLoader (D:\Mobile Develop\NativeScript\NSAngular\node_modules\loader-runner\lib\loadLoader.js:36:3)
    at iteratePitchingLoaders (D:\Mobile Develop\NativeScript\NSAngular\node_modules\loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (D:\Mobile Develop\NativeScript\NSAngular\node_modules\loader-runner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (D:\Mobile Develop\NativeScript\NSAngular\node_modules\webpack\lib\NormalModule.js:180:3)
    at NormalModule.build (D:\Mobile Develop\NativeScript\NSAngular\node_modules\webpack\lib\NormalModule.js:273:15)
    at Compilation.buildModule (D:\Mobile Develop\NativeScript\NSAngular\node_modules\webpack\lib\Compilation.js:145:10)
    at moduleFactory.create (D:\Mobile Develop\NativeScript\NSAngular\node_modules\webpack\lib\Compilation.js:432:9)
    at factory (D:\Mobile Develop\NativeScript\NSAngular\node_modules\webpack\lib\NormalModuleFactory.js:253:5)
    at applyPluginsAsyncWaterfall (D:\Mobile Develop\NativeScript\NSAngular\node_modules\webpack\lib\NormalModuleFactory.js:99:14)
    at D:\Mobile Develop\NativeScript\NSAngular\node_modules\tapable\lib\Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (D:\Mobile Develop\NativeScript\NSAngular\node_modules\webpack\lib\CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (D:\Mobile Develop\NativeScript\NSAngular\node_modules\tapable\lib\Tapable.js:272:13)
    at resolver (D:\Mobile Develop\NativeScript\NSAngular\node_modules\webpack\lib\NormalModuleFactory.js:74:11)
    at process.nextTick (D:\Mobile Develop\NativeScript\NSAngular\node_modules\webpack\lib\NormalModuleFactory.js:205:8)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Child app\app.component.html:
       [0] ./app.component.html 167 bytes {0} [built]
Child app\item\items.component.html:
       [0] ./item/items.component.html 1.74 kB {0} [built]
Child app\item\item-detail.component.html:
       [0] ./item/item-detail.component.html 394 bytes {0} [built]
Child extract-text-webpack-plugin D:\Mobile Develop\NativeScript\NSAngular\node_modules\extract-text-webpack-plugin\dist D:\Mobile Develop\NativeScript\NSAngular\node_modules\resolve-url-loader\index.js??ref--1-1!D:\Mobile Develop\NativeScript\NSAngular\node_modules\nativescript-css-loader\index.js??ref--1-2!D:\Mobile Develop\NativeScript\NSAngular\node_modules\nativescript-dev-webpack\platform-css-loader.js!D:\Mobile Develop\NativeScript\NSAngular\app\app.css:
       [0] ../node_modules/resolve-url-loader?{"silent":true}!../node_modules/nativescript-css-loader?{"minimize":false}!../node_modules/nativescript-dev-webpack/platform-css-loader.js!./app.css 2.06 kB {0} [built] [failed] [1 error]

    ERROR in ../node_modules/resolve-url-loader?{"silent":true}!../node_modules/nativescript-css-loader?{"minimize":false}!../node_modules/nativescript-dev-webpack/platform-css-loader.js!./app.css
    Module build failed: BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")`
        at error (D:\Mobile Develop\NativeScript\NSAngular\node_modules\browserslist\index.js:37:11)
        at D:\Mobile Develop\NativeScript\NSAngular\node_modules\browserslist\index.js:222:9
        at Array.forEach (native)
        at browserslist (D:\Mobile Develop\NativeScript\NSAngular\node_modules\browserslist\index.js:196:13)
        at cleanBrowsersList (D:\Mobile Develop\NativeScript\NSAngular\node_modules\caniuse-api\dist\utils.js:56:59)
        at setBrowserScope (D:\Mobile Develop\NativeScript\NSAngular\node_modules\caniuse-api\dist\index.js:29:43)
        at Object.<anonymous> (D:\Mobile Develop\NativeScript\NSAngular\node_modules\caniuse-api\dist\index.js:91:1)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (D:\Mobile Develop\NativeScript\NSAngular\node_modules\postcss-merge-rules\dist\lib\ensureCompatibility.js:7:19)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (D:\Mobile Develop\NativeScript\NSAngular\node_modules\postcss-merge-rules\dist\index.js:21:28)
        at Module._compile (module.js:570:32)
        at Object.Module._extensions..js (module.js:579:10)
        at Module.load (module.js:487:32)
        at tryModuleLoad (module.js:446:12)
        at Function.Module._load (module.js:438:3)
        at Module.require (module.js:497:17)
        at require (internal/module.js:20:19)
Webpack Bundle Analyzer saved stats file to D:\Mobile Develop\NativeScript\NSAngular\report\stats.json
Webpack Bundle Analyzer saved report to D:\Mobile Develop\NativeScript\NSAngular\report\report.html
child process exited with code 2
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ ns-bundle: `ns-bundle`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ ns-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\madson_gr\AppData\Roaming\npm-cache\_logs\2017-10-27T19_39_24_724Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ start-android-bundle: `npm run ns-bundle --android --run-app`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ start-android-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\madson_gr\AppData\Roaming\npm-cache\_logs\2017-10-27T19_39_24_946Z-debug.log
```

is there a fix to this?
```
ERROR in ./app.css
Module build failed: BrowserslistError: Unknown browser query `basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
```

{N} + angular is very slow to start the app taking more than 10 seconds and {N} core or with typescript is very poor in docs or examples.

package.json
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.NSAngular",
    "tns-android": {
      "version": "3.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.4.1",
    "@angular/common": "~4.4.1",
    "@angular/compiler": "~4.4.1",
    "@angular/core": "~4.4.1",
    "@angular/forms": "~4.4.1",
    "@angular/http": "~4.4.1",
    "@angular/platform-browser": "~4.4.1",
    "@angular/router": "~4.4.1",
    "nativescript-angular": "~4.4.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.2",
    "tns-core-modules": "~3.2.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "nativescript-dev-typescript": "~0.5.0",
    "typescript": "~2.4.2",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1",
    "copy-webpack-plugin": "~4.0.1",
    "raw-loader": "~0.5.1",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-worker-loader": "~0.8.1",
    "resolve-url-loader": "~2.1.0",
    "extract-text-webpack-plugin": "~3.0.0",
    "@angular/compiler-cli": "~4.4.1",
    "@ngtools/webpack": "~1.6.0"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install"
  }
}
```

**Comment by NickIliev** [comment]
@madsongr based on the contetn of the `package.json` it seems that you are missing the devDependency to `nativescript-dev-webpack`

Install it and run npm install before executing the bundle commmand
```
rm -rf webpack.config.js
npm i nativescript-dev-webpack --save-dev
npm install
npm run start-android-bundle --uglify --snapshot
```

Full documentation on how to enable and use Webpack can be found [here](https://docs.nativescript.org/best-practices/bundling-with-webpack). I have also tested with [this application](https://github.com/NickIliev/NS-Issues/tree/master/nativescript-dev-webpack/issue_305) and bundling with Webpack + uglify and snapshot is working as expected on my side.

**Comment by madsongr** [comment]
I followed the steps in docs for several times in others apps but all the time I get that errors. I ll try your commands to see what happen

**Comment by madsongr** [comment]
@NickIliev Ok I solved the app.css error. In webpack.config.js the 

```const mainSheet = `app.css`; ```

had to be changed to 

```const mainSheet = `./app.css`;```

So, running `npm run start-android-bundle ` it works. But when I add `--uglify --snapshot` the error below is displayed:

```
'D:\Mobile' is not recognized as an internal or external command...
```

```
D:\Mobile Develop\NativeScript\NSAngular>npm run start-android-bundle --uglify --snapshot

> @ start-android-bundle D:\Mobile Develop\NativeScript\NSAngular
> npm run ns-bundle --android --run-app


> @ ns-bundle D:\Mobile Develop\NativeScript\NSAngular
> ns-bundle

Running tns prepare...
Executing before-prepare hook from D:\Mobile Develop\NativeScript\NSAngular\hooks\before-prepare\nativescript-dev-typescript.js
Preparing project...
Project successfully prepared (android)
'D:\Mobile' não é reconhecido como um comando interno
ou externo, um programa operável ou um arquivo em lotes.
child process exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ ns-bundle: `ns-bundle`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ ns-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\madson_gr\AppData\Roaming\npm-cache\_logs\2017-10-30T19_55_56_276Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start-android-bundle: `npm run ns-bundle --android --run-app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start-android-bundle script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\madson_gr\AppData\Roaming\npm-cache\_logs\2017-10-30T19_55_56_373Z-debug.log
```

**Comment by NickIliev** [comment]
@madsongr it seems that path is not recognized as the folder 'Mobile Develop' is using white space in its name. Can you try to move the project to a path that lacks white spaces - meanwhile I will test this scenario on my side and post the results here.

**Comment by madsongr** [comment]
@NickIliev ok, this error is not displayed. Now I have to solve this issue:

```
 What went wrong:
A problem occurred configuring root project 'NSAngular'.
> You have not accepted the license agreements of the following SDK components:
[Android SDK Build-Tools 25.0.2].
Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html
```

**Comment by NickIliev** [comment]
@madsongr this is most likely related to your version of Android Build Tools. NativeScript requires versions 25.0.2 to be installed (system requirements [here](Android SDK Build-tools 25.0.2 or a later stable official release)). Check your Android SDK Manager and install the required version of Android Build Tools and then rebuild the project (with restarted shell)

**Comment by madsongr** [comment]
@NickIliev ok, thank you. It´s working now. Still taking a considerable time to start but it came from more than 12s to 6s.

**Comment by NickIliev** [comment]
@madsongr you can profile your application and see what causes the delay by using `timeline-view` tool.
Blog post on how to install, enable and use `timeline-view` in your project can be found [here](https://www.nativescript.org/blog/deep-dive-into-nativescript-3.1-performance-improvements)
