### ISSUE TITLE
Error: No NgModule metadata found for 'AppModule'.

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-dev-webpack#317]
I'm using the groceries demo app ( from NS). -- Android.

I must say that  if I run :  `tns run android` , **- I do get it all OK** : 

The problem has  started where when i've installed `nativescript-dev-webpack`  - Where if I run : 
`npm run start-android-bundle` , I get an error : 

```
JS: Timeline: Modules: onActivityResumed com.tns.gen.android.app.Application_ActivityLifecycleCallbacks@46bcb04  (346195420.913214ms. - 346195436.816214ms.)
System.err: java.lang.RuntimeException: Unable to resume activity {org.nativescript.Groceries/com.tns.NativeScriptActivity}: com.tns.NativeScriptException:
System.err: Calling js method onActivityResumed failed
System.err:
System.err: Error: No NgModule metadata found for 'AppModule'.
System.err: File: "file:///data/data/org.nativescript.Groceries/files/app/bundle.js, line: 14404, column: 16
System.err:
System.err: StackTrace:
System.err:     Frame: function:'ZoneAwareError', file:'file:///data/data/org.nativescript.Groceries/files/app/vendor.js', line: 58488, column: 33
```

[**complete log is here**](http://jsbin.com/rubaneyera/edit?html)

**Question:**

What am I doing wrong ? 

BTW - I've already deleted the `platform` folder -   and `tns add platform android`
_Also- I don't have a `main.aot.ts` - I don't know why. I've searched it via file system and didnt find it)_

Anyway - here are the core files  : 

**main.ts**
```
import { platformNativeScriptDynamic } from "nativescript-angular/platform";
import { setStatusBarColors } from "./utils/status-bar-util";

import { AppModule } from "./app.module";
setStatusBarColors();

platformNativeScriptDynamic().bootstrapModule(AppModule);

```

**app.module.ts**
```
import {NgModule, NO_ERRORS_SCHEMA} from "@angular/core";
import {NativeScriptModule} from "nativescript-angular/nativescript.module";
import {NativeScriptFormsModule} from "nativescript-angular/forms";
import {AppComponent} from "./app.component";
import {NativeScriptHttpModule} from "nativescript-angular/http";
import {NativeScriptRouterModule} from "nativescript-angular/router";
import {routes, navigatableComponents} from "./app.routing";

@NgModule({
    imports: [NativeScriptModule, NativeScriptFormsModule, NativeScriptHttpModule, NativeScriptRouterModule,
        NativeScriptRouterModule.forRoot(routes)],
    declarations: [AppComponent, ...navigatableComponents],
    bootstrap: [AppComponent],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class AppModule
{
}
```

**app.component.ts**
```
import { Component } from "@angular/core";

@Component({
    moduleId: module.id,
    selector: "main",
    template: "<page-router-outlet></page-router-outlet>"
})
export class AppComponent {}
```

**login.component.ts**
```
import {Component, ElementRef, OnInit, ViewChild} from "@angular/core";
import {User} from "../../shared/user/user";
import {UserService} from "../../shared/user/user.service";
import {Router} from "@angular/router";
import {RouterExtensions} from "nativescript-angular";
import {Page} from "ui/page";
import {View} from "ui/core/view"
import {Color} from "color";
import { setHintColor } from "../../utils/hint-util";
import { TextField } from "ui/text-field";
@Component({
    selector: "my-app",
    templateUrl: "./login.html",
    moduleId: module.id,
    styleUrls: ["./login-common.css", "./login.css"],
    providers: [UserService]
})
export class LoginComponent implements OnInit
{
```

**list.component.ts**
```
import {Component, ElementRef, OnInit, ViewChild} from "@angular/core";
import {Grocery} from "../../shared/grocery/grocery";
import {GroceryListService} from "../../shared/grocery/grocery-list.service";
import {TextField} from "ui/text-field";
import * as SocialShare from "nativescript-social-share";
@Component({
    selector: "list",
    moduleId: module.id,
    providers: [GroceryListService],
    templateUrl: "./list.html",
    styleUrls: ["./list-common.css", "./list.css"]
})
export class ListComponent implements OnInit
{...
```

**More files :** 

`webpack.config.js`: http://jsbin.com/yoyekutame/edit?html,output

`Package.json` :  http://jsbin.com/roleliqefa/edit?html

`tsconfig.json`  : http://jsbin.com/caxihereje/edit?html

**Comment by NickIliev** [comment]
@RoyiNamir update your version of nativescript-angular plugin to 4.4.1 and then update the angular dependencies
```
cd node_modules/nativescript-angular/bin
./update-app-ng-deps
cd ../../../
npm install
```

Do the same with nativescript-dev-webpack plugin
```
cd node_modules/nativescript-dev-werbpack/bin
./update-ns-webpack
cd ../../../
npm install
```

And then execute the WebPack command
```
npm run start-android-bundle
```

You can use [this demo application](https://github.com/NickIliev/nativescript-ng-cosmos/) as a reference

**Comment by RoyiNamir** [comment]
I'm not near my pc so I can't test it.

But I must ask - how did you find the solution? I've searched a lot and didnt find an answer.

Thank you for your effort

**Comment by RoyiNamir** [comment]
@NickIliev I've tried this but : 

```
C:\temp\node_modules\nativescript-dev-webpack\bin>ns-webpack-update.cmd
module.js:472
    throw err;
    ^

Error: Cannot find module 'C:\temp\node_modules\nativescript-dev-webpack\bin\ns-webpack-update'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

C:\temp\node_modules\nativescript-dev-webpack\bin>
```
