### ISSUE TITLE
Start Android bundle error

### ISSUE THREAD

**Issue by cerealexx** [NativeScript/nativescript-dev-webpack#320]
I've tried upgrading both npm and node, still doesn't work:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'start-android-bundle' ]
2 info using npm@5.5.1
3 info using node@v8.9.1
4 verbose run-script [ 'prestart-android-bundle',
4 verbose run-script   'start-android-bundle',
4 verbose run-script   'poststart-android-bundle' ]
5 info lifecycle @~prestart-android-bundle: @
6 info lifecycle @~start-android-bundle: @
7 verbose lifecycle @~start-android-bundle: unsafe-perm in lifecycle true
8 verbose lifecycle @~start-android-bundle: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/alexartigas/Desktop/Proyectos/Mage Duel/node_modules/.bin:/Users/alexartigas/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/alexartigas/Downloads/google-cloud-sdk/bin
9 verbose lifecycle @~start-android-bundle: CWD: /Users/alexartigas/Desktop/Proyectos/Mage Duel
10 silly lifecycle @~start-android-bundle: Args: [ '-c', 'npm run ns-bundle --android --run-app' ]
11 silly lifecycle @~start-android-bundle: Returned: code: 2  signal: null
12 info lifecycle @~start-android-bundle: Failed to exec start-android-bundle script
13 verbose stack Error: @ start-android-bundle: `npm run ns-bundle --android --run-app`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid @
15 verbose cwd /Users/alexartigas/Desktop/Proyectos/Mage Duel
16 verbose Darwin 16.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-android-bundle"
18 verbose node v8.9.1
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 2
22 error @ start-android-bundle: `npm run ns-bundle --android --run-app`
22 error Exit status 2
23 error Failed at the @ start-android-bundle script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```
Package.json:

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.MageDuel",
    "tns-android": {
      "version": "3.2.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.4.1",
    "@angular/common": "~4.4.1",
    "@angular/compiler": "~4.4.1",
    "@angular/core": "~4.4.1",
    "@angular/forms": "~4.4.1",
    "@angular/http": "~4.4.1",
    "@angular/platform-browser": "~4.4.1",
    "@angular/router": "~4.4.1",
    "@ngrx/effects": "^4.1.0",
    "@ngrx/router-store": "^4.1.0",
    "@ngrx/store": "^4.1.0",
    "nativescript-angular": "~4.4.0",
    "nativescript-ng-shadow": "^1.1.2",
    "nativescript-plugin-firebase": "^4.2.1",
    "nativescript-status-bar": "^1.1.1",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.2",
    "tns-core-modules": "^3.3.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.4.1",
    "@ngtools/webpack": "~1.6.0",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "copy-webpack-plugin": "~4.0.1",
    "cz-conventional-changelog": "^2.1.0",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-sass": "^1.3.2",
    "nativescript-dev-typescript": "~0.5.0",
    "nativescript-dev-webpack": "^0.8.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "typescript": "~2.4.2",
    "webpack": "~3.2.0",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  },
  "config": {
    "commitizen": {
      "path": "./node_modules/cz-conventional-changelog"
    }
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
```

Any clues?

**Comment by NickIliev** [comment]
@cerealexx if possible please post the whole error log prior to the lines posted above.
Meanwhile, take a look at [this thread](https://github.com/NativeScript/nativescript-dev-webpack/issues/97#issuecomment-299864431) where the exact same error was caused because of using absolute paths instead of relative ones.

**Comment by cerealexx** [comment]
My bad. I forgot to add NO_ERRORS_SCHEMA to child modules.
Thx!
