### ISSUE TITLE
Webpack build fails after snapshot build

### ISSUE THREAD

**Issue by vchimev** [NativeScript/nativescript-dev-webpack#340]
Steps:
```
tns run android --bundle --env.aot --env.uglify --env.snapshot
tns run android --bundle
```

Expected:
`./platforms/android/app/src/main/assets/app/_embedded_script_.js*` to be removed

Actual:
```
Warning: The static binding generator will generate extend from:vendor.js implementation
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:/Users/vchimev/Work/tmp/appNG/platforms/android/app/src/main/java/com/tns/FragmentClass.java Class: com.tns.FragmentClass
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:68)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:15)

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/vchimev/Work/tmp/appNG/platforms/android/build-tools/android-static-binding-generator/build.gradle' line: 284
```

**Comment by dvdbrk** [comment]
I'm right now in the second day of hitting the same issue :-(
