### ISSUE TITLE
Error while using RadSideDrawer

### ISSUE THREAD

**Issue by madsongr** [NativeScript/nativescript-dev-webpack#357]
I cannot use webpack while using `xmlns:nsDrawer="nativescript-pro-ui/sidedrawer"` in m typescript app.

XML:

```
<Page xmlns="http://schemas.nativescript.org/tns.xsd" 
navigatingTo="navigatingTo"
xmlns:nsDrawer="nativescript-pro-ui/sidedrawer"
xmlns:x="nativescript-statusbar"
xmlns:FAB="nativescript-floatingactionbutton" class="page">

   <x:StatusBar ios:barStyle="light" barColor="#f56c0a" />

<ActionBar title="Assistência" class="action-bar myaction-bar">
        <android>
            <NavigationButton icon="res://menu" tap="{{ toggleDrawer }}" />
        </android>
        <ios>
            <ActionItem icon="res://menu" ios.position="left" tap="{{ toggleDrawer}}" />
        </ios>

            <!-- <ActionItem icon="res://add_white" ios.position="right" tap="{{ toggleDrawer}}" /> -->
	</ActionBar>

	<nsDrawer:RadSideDrawer id="sideDrawer" drawerContentSize="150">

		<!-- side drawer content -->
        <ns:RadSideDrawer.drawerContent>
            <StackLayout class="sidedrawer-left sideDrawer">
                <StackLayout class="sidedrawer-content">
                    <!-- <Image src="res://user72" stretch="none" class="user-png"/> -->
                    <Label text="Perfil" padding="10" tap="{{ cadastrar }}" />
                    <Label text="Assistência" padding="10" />
                    <Label text="Indicações" padding="10" />
                    <Label text="Pontos" padding="10" />
                    <Label text="Configurações" padding="10" />
                </StackLayout>
            </StackLayout>
        </ns:RadSideDrawer.drawerContent>

        <nsDrawer:RadSideDrawer.mainContent>

            <GridLayout rows="auto, *">

             ....

```

```
System.err: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.habitodigital.TSAssistence/com.tns.NativeScriptActivity}: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed
System.err: Error: Building UI from XML. @file:///app/assistence/assistence-page.xml:25:2
System.err:  > Module '/data/data/com.habitodigital.TSAssistence/files/app/nativescript-pro-ui/sidedrawer' not found for element 'nativescript-pro-ui/sidedrawer:RadSideDrawer'.
System.err:    > com.tns.NativeScriptException: Failed to find module: "/data/data/com.habitodigital.TSAssistence/files/app/nativescript-pro-ui/sidedrawer", relative to: app//
System.err:       com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     com.tns.NativeScriptActivity.onCreate(NativeScriptActivity.java:13)
System.err:     android.app.Activity.performCreate(Activity.java:6245)
System.err:     android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1130)
System.err:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
System.err:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
System.err:     android.app.ActivityThread.-wrap11(ActivityThread.java)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:148)
System.err:     android.app.ActivityThread.main(ActivityThread.java:5443)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
System.err: File: "file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js, line: 9204, column: 20
System.err: StackTrace: 
System.err: 	Frame: function:'ScopeError', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 7344, column: 24
System.err: 	Frame: function:'SourceError', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 7355, column: 23
System.err: 	Frame: function:'', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 9223, column: 17
System.err: 	Frame: function:'', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 9204, column: 33
System.err: 	Frame: function:'', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 26712, column: 13
System.err: 	Frame: function:'module.exports.EasySAXParser.parse', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 27580, column: 23
System.err: 	Frame: function:'module.exports.XmlParser.parse', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 26759, column: 22
System.err: 	Frame: function:'module.exports.XmlStringParser.parse', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 9210, column: 27
System.err: 	Frame: function:'parseInternal', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 9055, column: 11
System.err: 	Frame: function:'loadPage', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 9139, column: 27
System.err: 	Frame: function:'', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 11657, column: 26
System.err: 	Frame: function:'', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 11676, column: 20
System.err: 	Frame: function:'module.exports.FrameBase.navigate', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 11730, column: 28
System.err: 	Frame: function:'module.exports.ActivityCallbacksImplementation.onCreate', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 5908, column: 19
System.err: 	Frame: function:'module.exports.NativeScriptActivity.onCreate', file:'file:///data/data/com.habitodigital.TSAssistence/files/app/vendor.js', line: 32682, column: 25
System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2426)
System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2490)
System.err: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:148)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5443)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Calling js method onCreate failed

```

and I got similar error if I use `xmlns:x="nativescript-statusbar"`

**Comment by NickIliev** [comment]
@madsongr have you updated your dependencies [to the latest versions](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade).
If so please post the content of your `package.json` file or provide a sample project which we can use for further investigation.
