### ISSUE TITLE
tns run android --bundle fails

### ISSUE THREAD

**Issue by snakale** [NativeScript/nativescript-dev-webpack#387]
I'm building a nativescript app using Angular. Everything was working fine until I installed the nativescript-dev-webpack plugin. I get the following error when I try to run my app. 

Executing before-prepareJSApp hook from C:\apps\native\artisan\hooks\before-prepareJSApp\nativescript-dev-webpack.js
Running webpack for android...

C:\apps\native\artisan\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:88
        const config = ngtools_api_1.readConfiguration(this._tsConfigPath);
                                     ^
TypeError: ngtools_api_1.readConfiguration is not a function
    at NativeScriptAngularCompilerPlugin._setupOptions (C:\apps\native\artisan\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:88:38)
    at NativeScriptAngularCompilerPlugin.AngularCompilerPlugin (C:\apps\native\artisan\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:43:14)
    at NativeScriptAngularCompilerPlugin (C:\apps\native\artisan\node_modules\nativescript-dev-webpack\plugins\NativeScriptAngularCompilerPlugin.ts:36:9)
    at module.exports.env (C:\apps\native\artisan\webpack.config.js:109:13)
    at handleFunction (C:\apps\native\artisan\node_modules\webpack\lib\prepareOptions.js:26:13)
    at prepareOptions (C:\apps\native\artisan\node_modules\webpack\lib\prepareOptions.js:11:13)
    at requireConfig (C:\apps\native\artisan\node_modules\webpack\bin\convert-argv.js:98:14)
    at C:\apps\native\artisan\node_modules\webpack\bin\convert-argv.js:104:17
    at Array.forEach (native)
    at module.exports (C:\apps\native\artisan\node_modules\webpack\bin\convert-argv.js:102:15)
    at yargs.parse (C:\apps\native\artisan\node_modules\webpack\bin\webpack.js:171:41)
    at Object.Yargs.self.parse (C:\apps\native\artisan\node_modules\webpack\node_modules\yargs\yargs.js:533:18)
    at Object.<anonymous> (C:\apps\native\artisan\node_modules\webpack\bin\webpack.js:152:7)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

The following is my tsconfig
```
{
    "compilerOptions": {
        "module": "commonjs",
        "target": "es5",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "noEmitHelpers": true,
        "noEmitOnError": true,
        "lib": [
            "es6",
            "dom",
            "es2015.iterable"
        ],
        "baseUrl": ".",
        "paths": {
            "*": [
                "./node_modules/tns-core-modules/*",
                "./node_modules/*"
            ]
        }
    },
    "exclude": [
        "node_modules",
        "platforms",
        "**/*.aot.ts"
    ]
}
```

then, I have the following in my package.json file
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.cstnam.artisan",
    "tns-android": {
      "version": "3.4.0"
    }
  },
  "dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/platform-browser": "4.4.6",
    "@angular/router": "4.4.6",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^4.1.1",
    "@ngrx/store": "^4.1.1",
    "angular2-moment": "^1.7.1",
    "google-libphonenumber": "^3.0.9",
    "nativescript-angular": "4.4.1",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-ng-shadow": "^2.0.0",
    "nativescript-plugin-firebase": "^5.0.5",
    "nativescript-textinputlayout": "^2.0.1",
    "nativescript-theme-core": "1.0.4",
    "reflect-metadata": "0.1.10",
    "rxjs": "5.5.2",
    "tns-core-modules": "3.4.0",
    "zone.js": "0.8.18"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.4.6",
    "@ngtools/webpack": "~1.8.2",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.3.5",
    "nativescript-dev-typescript": "0.5.1",
    "nativescript-dev-webpack": "^0.9.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "sass-loader": "~6.0.6",
    "typescript": "2.4.2",
    "webpack": "~3.8.1",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  }
}
```

**Comment by jogboms** [comment]
@snakale you can follow this guide for a proper upgrade.  

https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade

**Comment by erkanarslan** [comment]
Follow [this guide](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade) and upgrade you project dependencies. This should fix this problem.

**Comment by snakale** [comment]
Thank you very much. Following the guide, I was able to solve my problem
