### ISSUE TITLE
vendor bundle is empty when --env.snapshot flag is used

### ISSUE THREAD

**Issue by erkanarslan** [NativeScript/nativescript-dev-webpack#388]
I can run my application with `tns run android --bundle`. When I try to run it with `tns run android --bundle --env.snapshot` command, project is built but app crashes immediately after it starts. Crash message says that `webpackJsonp` is not defined. I noticed that vendor bundle in `platforms/android/app/src/main/assets/app` is empty when snapshot flag is used. Probably snapshot plugin creates an empty snapshot because of that. As it is empty, app cannot find webpackJsonp function.

I just created a new project just to try this. Then, installed dev-webpack plugin. When I run bundle command with snapshot flag I always get this error on both emulator and a real android device and I was never able to use snapshot feature. It seems that only some developers face this problem. My tns version is 3.4.0, nativescript-dev-webpack version is 0.9.0.

I also noticed that, when webpack bundle command is running first a normal vendor.js file is created with full content. Then, this file becomes empty. Probably another code is overwriting it with empty content.

Error log is:

````
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
System.err: Error calling module function 
System.err: ReferenceError: webpackJsonp is not defined
System.err: File: "file:///data/data/io.cubicl.cubicl/files/app/tns-java-classes.js, line: 1, column: 60
System.err: StackTrace: 
System.err: 	Frame: function:'', file:'file:///data/data/io.cubicl.cubicl/files/app/tns-java-classes.js', line: 1, column: 61
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: ReferenceError: webpackJsonp is not defined
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace: 
System.err: 	Frame: function:'', file:'file:///data/data/io.cubicl.cubicl/files/app/tns-java-classes.js', line: 1, column: 61
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4521)
System.err: 	at android.app.ActivityThread.access$1500(ActivityThread.java:144)
System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1339)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
System.err: 	at android.os.Looper.loop(Looper.java:135)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:5221)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at java.lang.reflect.Method.invoke(Method.java:372)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
System.err: Caused by: com.tns.NativeScriptException: 
System.err: Error calling module function 
System.err: ReferenceError: webpackJsonp is not defined
System.err: File: "file:///data/data/io.cubicl.cubicl/files/app/tns-java-classes.js, line: 1, column: 60
System.err: StackTrace: 
System.err: 	Frame: function:'', file:'file:///data/data/io.cubicl.cubicl/files/app/tns-java-classes.js', line: 1, column: 61
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: ReferenceError: webpackJsonp is not defined
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace: 
System.err: 	Frame: function:'', file:'file:///data/data/io.cubicl.cubicl/files/app/tns-java-classes.js', line: 1, column: 61
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	at com.tns.Runtime.runModule(Native Method)
System.err: 	at com.tns.Runtime.runModule(Runtime.java:530)
System.err: 	at com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:214)
System.err: 	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:17)
System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4518)
System.err: 	... 9 more
ActivityManager: Process io.cubicl.cubicl (pid 5237) has died
````

**Comment by sis0k0** [comment]
@erkanarslan, this is intentional. The content of `vendor.js` is moved to `_embedded_script_.js` together with some other bits. Can you check if `_embedded_script_.js` is present? Also can you share the whole build log?

**Comment by erkanarslan** [comment]
`_embedded_script_.js` is present and not empty. Here is the full build log. If you want I can send you the whole project.

[build-log.zip](https://github.com/NativeScript/nativescript-dev-webpack/files/1597056/build-log.zip)

**Comment by sis0k0** [comment]
@erkanarslan, yep that would be good :)

**Comment by erkanarslan** [comment]
@sis0k0 I sent an email to your gmail address on github. Thanks.

**Comment by erkanarslan** [comment]
I was able to build the project on Mac with snapshot flag. Probably, this is a problem in my other computer.
