### ISSUE TITLE
Extending Application

### ISSUE THREAD

**Issue by carrbrpoa** [NativeScript/nativescript-dev-webpack#393]
Hello,

I was chasing a solution for the following error https://github.com/NativeScript/NativeScript/issues/4117 and then, with the help of https://discourse.nativescript.org/t/cant-build-application/3566/3, https://github.com/NativeScript/sample-Android-Multidex and https://docs.nativescript.org/angular/runtimes/android/advanced-topics/extend-application-activity#extending-application-and-activity I was able to put it working (`tns run android`), but when I try `npm run start-android-bundle`, I get runtime exception, even after a succeeding build:

```
ActivityManager: Start proc 6734:org.myapp/u0a391 for activity org.myapp/com.tns.NativeScriptActivity
System.err: remove failed: ENOENT (No such file or directory) : /data/user/0/org.myapp/shared_prefs/com.google.android.gms.measurement.prefs.
xml.bak
System.err: com.tns.NativeScriptException:
System.err: Error: com.tns.NativeScriptException: Failed to find module: "./application.js", relative to: app//
System.err:     com.tns.Module.resolvePathHelper(Module.java:146)
System.err:     com.tns.Module.resolvePath(Module.java:55)
System.err:     com.tns.Runtime.runModule(Native Method)
System.err:     com.tns.Runtime.runModule(Runtime.java:530)
System.err:     com.tns.Runtime.createJSInstance(Runtime.java:624)
System.err:     com.tns.Runtime.initInstance(Runtime.java:606)
System.err:     com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:221)
System.err:     org.myApp.Application.onCreate(Application.java:16)
System.err:     android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
System.err:     android.app.ActivityThread.handleBindApplication(ActivityThread.java:6322)
System.err:     android.app.ActivityThread.access$1800(ActivityThread.java:222)
System.err:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1862)
System.err:     android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     android.os.Looper.loop(Looper.java:158)
System.err:     android.app.ActivityThread.main(ActivityThread.java:7230)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
System.err: File: "<unknown>, line: 1, column: 265
System.err: StackTrace:
System.err:     Frame: function:'require', file:'', line: 1, column: 266
System.err:     at com.tns.Runtime.runModule(Native Method)
System.err:     at com.tns.Runtime.runModule(Runtime.java:530)
System.err:     at com.tns.Runtime.createJSInstance(Runtime.java:624)
System.err:     at com.tns.Runtime.initInstance(Runtime.java:606)
System.err:     at com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:221)
System.err:     at org.myApp.Application.onCreate(Application.java:16)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6322)
System.err:     at android.app.ActivityThread.access$1800(ActivityThread.java:222)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1862)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:158)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7230)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
System.err: java.lang.RuntimeException: Unable to create application org.myApp.Application: com.tns.NativeScriptException: JavaScript object for Java ID 0 not f
ound.
System.err: Attempting to call method onCreate
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6325)
System.err:     at android.app.ActivityThread.access$1800(ActivityThread.java:222)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1862)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:158)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7230)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
System.err: Caused by: com.tns.NativeScriptException: JavaScript object for Java ID 0 not found.
System.err: Attempting to call method onCreate
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:957)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:941)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:933)
System.err:     at org.myApp.Application.onCreate(Application.java:22)
System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6322)
System.err:     ... 8 more
ActivityManager: removeProcessNameLocked mProcessNames.remove pid=6734 ,hash=231551077 ,name=org.myapp
ActivityManager: Process org.myapp (pid 6734)(adj 0) has died(29,304)
ActivityManager: cleanUpApplicationRecord -- 6734
```

My package.json:

```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.myapp",
    "tns-android": {
      "version": "3.3.1"
    }
  },
  "dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/platform-browser": "4.4.6",
    "@angular/router": "4.4.6",
    "base-64": "^0.1.0",
    "nativescript-angular": "4.4.1",
    "nativescript-appversion": "^1.4.1",
    "nativescript-camera": "^3.0.0",
    "nativescript-couchbase": "^1.0.18",
    "nativescript-drop-down": "^3.1.0",
    "nativescript-exit": "^1.0.0",
    "nativescript-floatingactionbutton": "^4.1.3",
    "nativescript-geolocation": "^3.0.1",
    "nativescript-gif": "^3.1.1",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-material-icons": "^1.0.3",
    "nativescript-ngx-fonticon": "^2.2.0",
    "nativescript-plugin-firebase": "^4.0.5",
    "nativescript-pro-ui": "^3.2.0",
    "nativescript-ripple": "^2.0.0",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toast": "^1.4.6",
    "nativescript-webview-interface": "^1.4.1",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "^3.3.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "4.4.6",
    "@ngtools/webpack": "~1.6.0",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.0.1",
    "extract-text-webpack-plugin": "~2.1.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "~0.4.0",
    "nativescript-dev-webpack": "^0.8.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.0.2",
    "tns-platform-declarations": "^3.4.0",
    "typescript": "~2.3.2",
    "webpack": "~2.5.1",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~0.2.3"
  },
  "scripts": {
    "ns-bundle": "ns-bundle",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app"
  }
}
```

Any ideas about that?

Thanks in advance

**Comment by NickIliev** [comment]
The platform-specific file should be required in the platform-specific vendor.ts file - in your case weare talking about `applicaiton.anroid.js`.

The solution is provided [here](https://github.com/NativeScript/nativescript-dev-webpack/issues/65#issuecomment-277935167) and [here](https://github.com/NativeScript/nativescript-dev-webpack/issues/285#issuecomment-334673452)

**Comment by alexma01** [comment]
Hi @NickIliev ,
i have same problem when i extend java class:
**System.err: java.lang.RuntimeException: Unable to instantiate service com.tns.notifications.FirebaseInstanceIDServiceCustom: com.tns.NativeScriptException:
System.err:
System.err: Error: com.tns.NativeScriptException: Failed to find module: "app/notifications/FirebaseInstanceIDServiceCustom.js", relative to: app//**

Where should I specify the files?

Thanks
