### ISSUE TITLE
Error configuring webpack in existing project 

### ISSUE THREAD

**Issue by chauhan-saurabh** [NativeScript/nativescript-dev-webpack#398]
tns run ios --bundleSearching for devices...

```
Executing before-prepare hook from /Users/saurabh.chauhan/Desktop/shyft/hooks/before-prepare/nativescript-dev-sass.js
Executing before-prepare hook from /Users/saurabh.chauhan/Desktop/shyft/hooks/before-prepare/nativescript-dev-typescript.js
Hook skipped because either bundling or livesync is in progress.
Preparing project...
Executing before-prepareJSApp hook from /Users/saurabh.chauhan/Desktop/shyft/hooks/before-prepareJSApp/nativescript-dev-webpack.js
Running webpack for iOS...

/Users/saurabh.chauhan/Desktop/shyft/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:92
        this._rootNames = config.rootNames.concat(...this._singleFileIncludes);
                          ^
ReferenceError: config is not defined
    at NativeScriptAngularCompilerPlugin._setupOptions (/Users/saurabh.chauhan/Desktop/shyft/node_modules/@ngtools/webpack/src/an
gular_compiler_plugin.js:92:27)
    at NativeScriptAngularCompilerPlugin.AngularCompilerPlugin (/Users/saurabh.chauhan/Desktop/shyft/node_modules/@ngtools/webpac
k/src/angular_compiler_plugin.js:43:14)
    at NativeScriptAngularCompilerPlugin (/Users/saurabh.chauhan/Desktop/shyft/node_modules/nativescript-dev-webpack/plugins/NativeScriptAngularCompilerPlugin.ts:36:9)
    at module.exports.env (/Users/saurabh.chauhan/Desktop/shyft/webpack.config.js:102:13)
    at handleFunction (/Users/saurabh.chauhan/Desktop/shyft/node_modules/webpack/lib/prepareOptions.js:26:13)
    at prepareOptions (/Users/saurabh.chauhan/Desktop/shyft/node_modules/webpack/lib/prepareOptions.js:11:13)
    at requireConfig (/Users/saurabh.chauhan/Desktop/shyft/node_modules/webpack/bin/convert-argv.js:98:14)
    at /Users/saurabh.chauhan/Desktop/shyft/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (native)
    at module.exports (/Users/saurabh.chauhan/Desktop/shyft/node_modules/webpack/bin/convert-argv.js:102:15)
    at yargs.parse (/Users/saurabh.chauhan/Desktop/shyft/node_modules/webpack/bin/webpack.js:171:41)
    at Object.Yargs.self.parse (/Users/saurabh.chauhan/Desktop/shyft/node_modules/webpack/node_modules/yargs/yargs.js:533:18)
    at Object.<anonymous> (/Users/saurabh.chauhan/Desktop/shyft/node_modules/webpack/bin/webpack.js:152:7)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
Executing webpack failed with exit code 1.
```

**Comment by chauhan-saurabh** [comment]
//Package.JSON

`{
  "description": {app name},
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.{app name}",
    "tns-ios": {
      "version": "3.4.0"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~4.2.5",
    "@angular/common": "~4.2.5",
    "@angular/compiler": "~4.2.5",
    "@angular/core": "~4.2.5",
    "@angular/forms": "~4.2.5",
    "@angular/http": "~4.2.5",
    "@angular/platform-browser": "4.2.5",
    "@angular/router": "~4.2.5",
    "amazon-cognito-identity-js": "^1.28.0",
    "angular2-uuid": "^1.1.1",
    "jwt-decode": "^2.2.0",
    "moment": "^2.19.2",
    "nativescript-accordion": "^5.0.2",
    "nativescript-advanced-webview": "^1.2.0",
    "nativescript-angular": "4.2.0",
    "nativescript-autocomplete": "^1.0.0",
    "nativescript-background-http": "^3.1.0",
    "nativescript-braintree": "^1.0.8",
    "nativescript-camera": "^3.0.2",
    "nativescript-chatview": "^1.0.3",
    "nativescript-checkbox": "^2.1.11",
    "nativescript-dialog": "^0.1.0",
    "nativescript-directions": "^1.1.0",
    "nativescript-geolocation": "^4.2.1",
    "nativescript-google-places": "0.0.3",
    "nativescript-imagepicker": "^4.0.1",
    "nativescript-localstorage": "^1.1.5",
    "nativescript-mapbox": "^3.1.3",
    "nativescript-pro-ui": "^3.3.0",
    "nativescript-theme-core": "1.0.4",
    "nativescript-urlhandler": "^1.2.2",
    "node-googleplaces": "^0.1.2",
    "reflect-metadata": "0.1.10",
    "rxjs": "^5.0.1",
    "tns-core-modules": "3.1.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.2.5",
    "@ngtools/webpack": "~1.8.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "codelyzer": "3.1.2",
    "copy-webpack-plugin": "~4.0.1",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "1.3.0",
    "nativescript-dev-typescript": "^0.6.0",
    "nativescript-dev-webpack": "^0.9.0",
    "nativescript-worker-loader": "~0.8.1",
    "node-sass": "4.5.3",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.1.0",
    "sass-loader": "~6.0.6",
    "tslint": "5.6.0",
    "typescript": "2.4.2",
    "webpack": "~3.8.1",
    "webpack-bundle-analyzer": "^2.8.2",
    "webpack-sources": "~1.0.1"
  }
}
`

**Comment by NickIliev** [comment]
@chauhan-saurabh you are using version of nativescript-dev-webpack that is compatiblwe with nativescript-angular 5.x.x and NativeScript CLI and modules 3.4.x and above.

Guide on how to migrate your application to the latest versions of these plugins and the related dependencies can be found [here](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade)
