### ISSUE TITLE
Error with webpack (window not defined)

### ISSUE THREAD

**Issue by ChAraya** [NativeScript/nativescript-dev-webpack#405]
Hi, i use the new webpack for nativescript version 0.9.1 and when compile i got this error.

when i don't use the webpack the app work without any problem.

> JS:ERROR Error: Uncaught (in promise): ReferenceError: window is not defined
> JS: ReferenceError: window is not defined
> JS:     at BrowserDomAdapter.module.exports.BrowserDomAdapter.getUserAgent (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:40428:26)
> JS:     at _isAndroid (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:30994:194)
> JS:     at new DefaultValueAccessor (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:31025:38)
> JS:     at createClass (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:12489:20)
> JS:     at createDirectiveInstance (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:12332:37)
> JS:     at createViewNodes (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:13770:53)
> JS:     at callViewAction (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:14202:13)
> JS:     at execComponentViewsAction (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:14111:13)
> JS:     at createViewNodes (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:13798:5)
> JS:     at createRootView (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:13660:5)
> JS:     at callWithDebugContext (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:15061:42)
> JS:     at Object.debugCreateRootView [as createRootView] (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:14362:12)
> JS:     at ComponentFactory_.module.exports.ComponentFactory_.create (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:11281:46)
> JS:     at ComponentFactoryBoundToModule.module.exports.ComponentFactoryBoundToModule.create (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:4242:29)
> JS:     at ViewContainerRef_.module.exports.ViewContainerRef_.createComponent (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:11478:62)
> 

this is my package.json

> 
> {
>   "description": "NativeScript Application",
>   "license": "SEE LICENSE IN <your-license-filename>",
>   "readme": "NativeScript Application",
>   "repository": "<fill-your-repository-here>",
>   "nativescript": {
>     "id": "org.nativescript.MiApp",
>     "tns-ios": {
>       "version": "3.4.0"
>     },
>     "tns-android": {
>       "version": "3.2.0"
>     }
>   },
>   "dependencies": {
>     "@angular/animations": "~5.0.0",
>     "@angular/common": "~5.0.0",
>     "@angular/compiler": "~5.0.0",
>     "@angular/core": "~5.0.0",
>     "@angular/forms": "~5.0.0",
>     "@angular/http": "~5.0.0",
>     "@angular/platform-browser": "~5.0.0",
>     "@angular/platform-browser-dynamic": "~5.0.0",
>     "@angular/router": "~5.0.0",
>     "allow-publish": "^1.0.4",
>     "i": "^0.3.6",
>     "nativescript-accordion": "^5.0.3",
>     "nativescript-angular": "~5.0.0",
>     "nativescript-drop-down": "^3.2.0",
>     "nativescript-effects": "^1.0.0",
>     "nativescript-loading-indicator": "^2.4.0",
>     "nativescript-plugin-firebase": "^5.1.2",
>     "nativescript-slides": "^2.2.13",
>     "nativescript-snackbar": "^2.0.0",
>     "nativescript-telerik-ui": "^3.1.4",
>     "nativescript-theme-core": "~1.0.4",
>     "node-sass": "^4.7.2",
>     "npm": "^5.6.0",
>     "reflect-metadata": "~0.1.8",
>     "rxjs": "~5.5.2",
>     "tns-core-modules": "~3.4.0",
>     "zone.js": "~0.8.2"
>   },
>   "devDependencies": {
>     "@angular/compiler-cli": "~5.0.0",
>     "@ngtools/webpack": "~1.8.2",
>     "babel-traverse": "6.26.0",
>     "babel-types": "6.26.0",
>     "babylon": "6.18.0",
>     "copy-webpack-plugin": "~4.3.0",
>     "css-loader": "~0.28.7",
>     "extract-text-webpack-plugin": "~3.0.2",
>     "lazy": "1.0.11",
>     "nativescript-css-loader": "~0.26.0",
>     "nativescript-dev-sass": "^1.3.5",
>     "nativescript-dev-typescript": "~0.6.0",
>     "nativescript-dev-webpack": "^0.9.1",
>     "nativescript-worker-loader": "~0.8.1",
>     "raw-loader": "~0.5.1",
>     "resolve-url-loader": "~2.2.1",
>     "sass-loader": "~6.0.6",
>     "typescript": "~2.4.2",
>     "uglifyjs-webpack-plugin": "~1.1.6",
>     "webpack": "~3.10.0",
>     "webpack-bundle-analyzer": "^2.9.1",
>     "webpack-sources": "~1.1.0"
>   },
>   "scripts": {
>     "ns-bundle": "ns-bundle",
>     "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
>     "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install",
>     "start-android-bundle": "npm run ns-bundle --android --run-app",
>     "start-ios-bundle": "npm run ns-bundle --ios --run-app",
>     "build-android-bundle": "npm run ns-bundle --android --build-app",
>     "build-ios-bundle": "npm run ns-bundle --ios --build-app"
>   }
> }

what can i do ?

**Comment by NickIliev** [comment]
@ChAraya can you try following[this instruction](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade) and let me know if are able to bundle your project.

**Comment by ChAraya** [comment]
@NickIliev i did everything but nothing happens

still the same error.

> ERROR Error: Uncaught (in promise): ReferenceError: window is not defined
> JS: ReferenceError: window is not defined
> JS:     at BrowserDomAdapter.module.exports.BrowserDomAdapter.getUserAgent (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:40428:26)
> JS:     at _isAndroid (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:30994:194)
> JS:     at new DefaultValueAccessor (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:31025:38)
> JS:     at createClass (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:12489:20)
> JS:     at createDirectiveInstance (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:12332:37)
> JS:     at createViewNodes (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:13770:53)
> JS:     at callViewAction (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:14202:13)
> JS:     at execComponentViewsAction (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:14111:13)
> JS:     at createViewNodes (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:13798:5)
> JS:     at createRootView (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:13660:5)
> JS:     at callWithDebugContext (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:15061:42)
> JS:     at Object.debugCreateRootView [as createRootView] (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:14362:12)
> JS:     at ComponentFactory_.module.exports.ComponentFactory_.create (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:11281:46)
> JS:     at ComponentFactoryBoundToModule.module.exports.ComponentFactoryBoundToModule.create (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:4242:29)
> JS:     at ViewContainerRef_.module.exports.ViewContainerRef_.createComponent (file:///data/data/org.nativescript.MiPortal/files/app/vendor.js:11478:62)

**Comment by sud80** [comment]
I was also getting similar error 
NavigationError(id: 5, url: '/myapp/path', error: ReferenceError: window is not defined). 
When I enable aot, then it works fine. I haven't yet figured out what is the underlying core issue.

**Comment by NickIliev** [comment]
@sud80 @ChAraya we would need a sample project to reproduce the issue and investigate further.
@ChAraya I've noticed you are using `nativescript-telerik-ui` so I would recommend updating to `nativescript-pro-ui` version (free of use - some breaking changes - [migration guide here](http://docs.telerik.com/devtools/nativescript-ui/migration)).

Closing this issue due to inactivity and not being able to reproduce but please do let me know if you are still experiencing this one and if you have a sample project that can demonstrate the problem.

**Comment by kshipraShelke** [comment]
Can anybody help with the above issue ?? facing the same problem in webpack.

**Comment by mikaelkalt** [comment]
I'm having the same problem. What I've figured out so far, is that if I enable AOT then it's working. So
`tns run android|ios --bundle --env.aot` works... without AOT I'm getting the exact same error. 

I was trying to reproduce it in a demo project, but so far without any success. @kshipraShelke are you by any chance using the sidedrawer?

**Comment by mikaelkalt** [comment]
The value is `skipCodeGeneration: !aot` - I haven't changed anything in the configuration. I'm basically using the latest default template for the webpack config.

**Comment by mikaelkalt** [comment]
@kshipraShelke thanks a lot for your answer. Actually we're not using a nativescript-dropdown plugin...  so you're saying the sidedrawer is not causing the problem? so most likely I have to check other third-party plugins.
