### ISSUE TITLE
Update to angular 2.3.1 breaks webpack bundle

### ISSUE THREAD

**Issue by m-abs** [NativeScript/nativescript-dev-webpack#46]
`nativescript-angular@next` have just been updated to `angular 2.3.1`, unfortunately this breaks bundling with `nativescript-dev-webpack`.

I've created a demo project here:
https://github.com/m-abs/tns-webpack-ng2.3

All I did was:
* Create the project with: tns create my-hallo-world --template ng
* Update angular-deps, rxjs, zone.js, nativescript-angular@next and @ngtools/webpack

Running `npm run start-android-bundle` gives this error output:

```bash
> @ prestart-android-bundle /home/mabs/project/my-hallo-world
> npm run webpack-android


> @ prewebpack-android /home/mabs/project/my-hallo-world
> npm run clean-android


> @ clean-android /home/mabs/project/my-hallo-world
> tns clean-app android


> @ webpack-android /home/mabs/project/my-hallo-world
> webpack --config=webpack.android.js --progress

 GenerateBundleStarterPlugin: /home/mabs/project/my-hallo-world/app
Hash: 3160279b31a12a81c031
Version: webpack 2.1.0-beta.28
Time: 6746ms
       Asset       Size  Chunks           Chunk Names
  app.css.js  266 bytes  0[emitted]  app.css
   bundle.js  948 bytes  1[emitted]  bundle
   vendor.js    3.42 MB  2[emitted]  vendor
     app.css    13.4 kB  0[emitted]  app.css
package.json    1.45 kB  [emitted]  
  starter.js   41 bytes  [emitted]  
 [115] ../$$_gendir async 160 bytes {2} [built]
 [303] ./vendor-platform.android.ts 1.05 kB {2} [built]
 [306] ../$$_gendir 160 bytes {2} [built]
 [488] ./main.aot.ts 241 bytes {1} [built]
 [489] ./vendor.ts 394 bytes {2} [built]
 [490] ./app.css 41 bytes {0} [built] [1 warning]
    + 487 hidden modules

WARNING in ./app.css
  resolve-url-loader cannot operate: CSS error
  /home/mabs/project/my-hallo-world/app/app.css:6:426: property missing ':'
  at error (/home/mabs/project/my-hallo-world/node_modules/css/lib/parse/index.js:62:15)

WARNING in ./app.css
  resolve-url-loader cannot operate: CSS error
  /home/mabs/project/my-hallo-world/app/app.css:6:426: property missing ':'
  at error (/home/mabs/project/my-hallo-world/node_modules/css/lib/parse/index.js:62:15)

ERROR in Could not resolve "app/app.module" from "app/app.module".

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in '/home/mabs/project/my-hallo-world/app'
 @ ./main.aot.ts 2:0-60
Child app/app.component.html:
       [0] ./app.component.html 309 bytes {0} [built]
Child extract-text-webpack-plugin:
       [2] ../~/resolve-url-loader!../~/css-loader!../~/nativescript-dev-webpack/platform-css-loader.js!./app.css 885 bytes {0} [built] [1 warning]
        + 2 hidden modules
    
    WARNING in ../~/resolve-url-loader!../~/css-loader!../~/nativescript-dev-webpack/platform-css-loader.js!./app.css
      resolve-url-loader cannot operate: CSS error
      /home/mabs/project/my-hallo-world/app/app.css:6:426: property missing ':'
      at error (/home/mabs/project/my-hallo-world/node_modules/css/lib/parse/index.js:62:15)
```

Note the line "ERROR in Could not resolve "app/app.module" from "app/app.module"."

**Comment by hdeshev** [comment]
We will release an updated nativescript-dev-webpack plugin that uses the latest @ngtools/webpack. That should fix it. Stay tuned.

**Comment by hdeshev** [comment]
The nativescript-dev-webpack update is on npm now.

Just a heads up -- we discovered an issue that causes @angular/compiler to be included in your bundle. To avoid that, you need to change your `NativeScriptModule` import to something like:

`import { NativeScriptModule } from "nativescript-angular/nativescript.module";`
