### ISSUE TITLE
Error with webpack (window not defined)

### ISSUE THREAD

**Issue by kshipraShelke** [NativeScript/nativescript-dev-webpack#516]
Hi, I am using the webpack for nativescript version 0.9.1 and when compile I got this error.

when I don't use the webpack the app work without any problem.
and getting this error

```
JS: ERROR Error: Uncaught (in promise): ReferenceError: window is not defined
JS: ReferenceError: window is not defined
JS:     at t.getUserAgent (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:1712:8704)
JS:     at x (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:1290:156)
JS:     at new e (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:1290:500)
JS:     at Va (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:501:2933)
JS:     at Sa (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:501:1208)
JS:     at ds (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:536:4232)
JS:     at xs (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:536:8464)
JS:     at Es (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:536:7580)
JS:     at ds (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:536:4477)
JS:     at xs (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:536:8464)
JS:     at Es (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:536:7580)
JS:     at ds (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:536:4477)
JS:     at us (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:536:2936)
JS:     at wu (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:543:8868)
JS:     at Object.Ds [as createRootView] (file:///data/data/org.nativescript.drinkmates/files/app/vendor.js:543:1751)
```

**Comment by NickIliev** [comment]
@kshipraShelke consider posting any related information that can help us to investigate the issue 

```
<!--
We, the rest of the NativeScript community, thank you for your
feedback! 
To help the rest of the community review your issue, please follow the instructions in the template.
-->

<!-- ISSUE TEMPLATE -->
<!-- (Update "[ ]" to "[x]" to check a box) -->

## Issue Checklist

- [ ] You are submitting: <!-- a feature request; a bug report. For questions, please use the [NativeScript Forum]. -->
- [ ] You verified that this is a real problem by searching the [NativeScript Forum] and the other [issues] in this repo.
- [ ] You checked our [demo apps] and the [documentation] for sample usage.

## Tell us about the problem
<!-- Describe the issue with a few words. Provide build log and steps to reproduce if relevant. -->

## Local environment

- [ ] Platform <!-- Linux, Mac, Windows -->
- [ ] Node version XX <!-- run `node --version` -->
- [ ] NativeScript CLI version <!-- run `tns --version` -->

## Project data

- [ ] Platform you are building the app for <!-- Android, iOS, Both -->
- [ ] Node dependencies:
```

```
- [ ] Webpack configuration:
```

```

[NativeScript Forum]: http://forum.nativescript.org
[issues]: https://github.com/nativescript/nativescript-dev-webpack/issues?utf8=✓&q=is%3Aissue
[demo apps]: ../demo
[documentation]: https://docs.nativescript.org/best-practices/bundling-with-webpack

```

**Comment by kshipraShelke** [comment]
@NickIliev thanks for your reply..

 Platform android
 Node version 8.8.1
 NativeScript CLI 4.0.0
 webpack just updated to 0.11.0

Facing issue with this Command "tns run android --env.snapshot --env.uglify"

Package.json
"dependencies": {
    "@angular/common": "~5.1.0",
    "@angular/compiler": "~5.1.0",
    "@angular/core": "~5.1.0",
    "@angular/forms": "~5.1.0",
    "@angular/http": "~5.1.0",
    "@angular/platform-browser": "~5.1.0",
    "@angular/platform-browser-dynamic": "~5.1.0",
    "@angular/router": "~5.1.0",
    "date-fns": "^1.28.5",
    "nativescript-angular": "~5.1.0",
    "nativescript-background-http": "3.1.0",
    "nativescript-bottombar": "3.0.7",
    "nativescript-camera": "~3.1.2",
    "nativescript-cardview": "^2.0.5",
    "nativescript-contacts-lite": "0.2.5",
    "nativescript-drop-down": "3.1.0",
    "nativescript-emoji": "^1.1.1",
    "nativescript-exoplayer": "^3.4.0",
    "nativescript-floatingactionbutton": "^4.1.0",
    "nativescript-fresco": "3.0.6",
    "nativescript-geolocation": "4.2.6",
    "nativescript-imagecropper": "0.0.7",
    "nativescript-imagepicker": "3.0.7",
    "nativescript-iqkeyboardmanager": "1.0.1",
    "nativescript-loading-indicator": "^2.4.0",
    "nativescript-material-icons": "^1.0.3",
    "nativescript-mediafilepicker": "^1.0.4",
    "nativescript-ng-shadow": "^2.1.0",
    "nativescript-ngx-fonticon": "4.0.0",
    "nativescript-popup": "^1.4.0",
    "nativescript-push-notifications": "^1.1.0",
    "nativescript-ripple": "^2.0.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "^1.4.6",
    "nativescript-ui-autocomplete": "^3.7.0",
    "nativescript-ui-dataform": "^3.6.0",
    "nativescript-ui-gauge": "^3.5.0",
    "nativescript-ui-listview": "^3.5.6",
    "nativescript-ui-sidedrawer": "^4.0.0",
    "reflect-metadata": "^0.1.8",
    "rxjs": "^5.5.0",
    "tns-core-modules": "^3.4.0",
    "tns-platform-declarations": "^3.0.1",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~5.1.0",
    "@ngtools/webpack": "~1.9.4",
    "@types/chai": "^4.0.2",
    "@types/mocha": "^2.2.41",
    "@types/node": "^7.0.5",
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.0",
    "chai": "^3.5.0",
    "clean-webpack-plugin": "~0.1.19",
    "codelyzer": "^3.0.0",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "filewalker": "0.1.3",
    "karma": "^1.6.0",
    "karma-chai": "^0.1.0",
    "karma-mocha": "^1.3.0",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "mocha": "^3.3.0",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-appium": "^3.2.0",
    "nativescript-dev-typescript": "^0.7.1",
    "nativescript-dev-webpack": "^0.11.0",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "tns-platform-declarations": "3.4.0",
    "tslib": "1.7.1",
    "tslint": "^5.1.0",
    "typescript": "~2.4.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }

**Comment by NickIliev** [comment]
@kshipraShelke there are some incompatible versions in your package.json (e.g. using tns-core-modules@3.4.x along with the latest Android runtime tns-android@4.0.0 ). You should check all used plugins and update them to the version compatible with NativeScript 4.0.0. For nativescript-angular and nativescript-dev-webpack you can use the following workflow:
```
tns platform remove android
tns platform add android@latest
npm i tns-core-modules@latest --save
npm i nativescript-angular@latest --save
npm i nativescript-dev-webpack@latest --save
./node_modules/.bin/update-app-ng-deps
./node_modules/.bin/update-ns-webpack --configs --deps
npm i
tns run android --bundle --env.uglify --env.snapshot
```
For all other plugins (dependencies starting with nativescript-) you should manually verify and use the latest possible version (or the one that is compatible with nativeScript 4.0.0 and above)

Keep in mind that you need to pass `--bundle` flag to enable Webpack bundling.
I've created and used [this test app](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/nativescript-dev-webpack/issue_516) and this is [the package.json](https://github.com/NickIliev/NS-Issues-2018-II/blob/master/nativescript-dev-webpack/issue_516/package.json) after running the above commands

**Comment by NickIliev** [comment]
@kshipraShelke I am still not able to reproduce the issue (using the test project linked in my previous comment with the same `package.json` content as yours). Perhaps you could send me a sample project (Github or archive here without `node_modules` and `platforms` folders).

As a side note: You are using `tns-platform-declarations` both as `dependency` and as a `devDependency`. Remove it as a dependency as this would bring the declaration files in the built project and make your project unnecessary large.

**Comment by NickIliev** [comment]
Closing due to inactivity bu please do let me know if you have a sample project that can reproduce the issue

**Comment by kshipraShelke** [comment]
@NickIliev  I did not get what the real problem was but I with the new release of Nativescript 4.1 and angular 6 the issue is resolved.
