### ISSUE TITLE
Application entry point file not found using --bundle

### ISSUE THREAD

**Issue by jgerryl** [NativeScript/nativescript-dev-webpack#588]
## Issue Checklist

- [x] You are submitting:  a bug report.
- [x] You verified that this is a real problem by searching the [NativeScript Forum] and the other [issues] in this repo.
- [x] You checked our [demo apps] and the [documentation] for sample usage.

## Tell us about the problem
I'm trying to use nativescript-dev-webpack. i run `tns build android --bundle ` successfully but then got error when using `tns run android --bundle`. I'm using custom main activity. I'm following issue #559  but still got another error "application entry point file not found. please specify the file in package.json otherwise make sure the file index.js or bootstrap.js exists." I check my app/package.json in app folder said main : main.js and i check main.js exists.

## Local environment

- [x] Platform :  Windows
- [ ] Node version v8.11.3
- [ ] NativeScript CLI version 4.1.1

## Project data

- [x] Platform you are building the app for Android
- [ ] Node dependencies:
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.myapp.xx",
    "tns-android": {
      "version": "4.1.3"
    }
  },
  "dependencies": {
    "@angular/animations": "~6.0.6",
    "@angular/common": "~6.0.6",
    "@angular/compiler": "~6.0.6",
    "@angular/core": "~6.0.6",
    "@angular/forms": "~6.0.6",
    "@angular/http": "~6.0.6",
    "@angular/platform-browser": "~6.0.6",
    "@angular/platform-browser-dynamic": "~6.0.6",
    "@angular/router": "~6.0.6",
    "awesome-typescript-loader": "^5.2.0",
    "nativescript-angular": "^6.0.0",
    "nativescript-background-http": "^3.2.7",
    "nativescript-camera": "^4.0.2",
    "nativescript-feedback": "^1.2.0",
    "nativescript-local-notifications": "^2.0.4",
    "nativescript-mediafilepicker": "^1.0.7",
    "nativescript-push-notifications": "^1.1.4",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-ui-dataform": "^3.6.1",
    "nativescript-ui-listview": "^3.5.8",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~6.2.1",
    "tns-core-modules": "^4.1.0",
    "tns-platform-declarations": "^4.0.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.7.0-rc.0",
    "@angular/compiler-cli": "~6.1.0-beta.1",
    "angular-router-loader": "^0.8.5",
    "babel-traverse": "^6.26.0",
    "babel-types": "^6.26.0",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.7.1",
    "nativescript-dev-webpack": "^0.14.1",
    "typescript": "^2.7.2",
    "webpack": "^4.12.1"
  }
}

```
- [ ] Webpack configuration:
```
const { join, relative, resolve, sep } = require("path");

const webpack = require("webpack");
const nsWebpack = require("nativescript-dev-webpack");
const nativescriptTarget = require("nativescript-dev-webpack/nativescript-target");
const { PlatformReplacementHost } = require("nativescript-dev-webpack/host/platform");
const CleanWebpackPlugin = require("clean-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const { BundleAnalyzerPlugin } = require("webpack-bundle-analyzer");
const { NativeScriptWorkerPlugin } = require("nativescript-worker-loader/NativeScriptWorkerPlugin");
const UglifyJsPlugin = require("uglifyjs-webpack-plugin");
const { AngularCompilerPlugin } = require("@ngtools/webpack");

module.exports = env => {
    // Add your custom Activities, Services and other Android app components here.
    const appComponents = [
        "tns-core-modules/ui/frame",
        "tns-core-modules/ui/frame/activity",
        //"./app/activity.android.ts",
        resolve(__dirname, "app/activity.android.ts"),
    ];

    const platform = env && (env.android && "android" || env.ios && "ios");
    if (!platform) {
        throw new Error("You need to provide a target platform!");
    }

    const extensions = ["tns", platform];
    const platformHost = new PlatformReplacementHost(extensions);

    const projectRoot = __dirname;

    // Default destination inside platforms/<platform>/...
    const dist = resolve(projectRoot, nsWebpack.getAppPath(platform, projectRoot));
    const appResourcesPlatformDir = platform === "android" ? "Android" : "iOS";

    const {
        // The 'appPath' and 'appResourcesPath' values are fetched from
        // the nsconfig.json configuration file
        // when bundling with `tns run android|ios --bundle`.
        appPath = "app",
        appResourcesPath = "app/App_Resources",

        // You can provide the following flags when running 'tns run android|ios'
        aot, // --env.aot
        snapshot, // --env.snapshot
        uglify, // --env.uglify
        report, // --env.report
    } = env;

    const appFullPath = resolve(projectRoot, appPath);
    const appResourcesFullPath = resolve(projectRoot, appResourcesPath);

    const entryModule = aot ?
        nsWebpack.getAotEntryModule(appFullPath) : 
        `${nsWebpack.getEntryModule(appFullPath)}.ts`;
    const entryPath = `.${sep}${entryModule}`;

    const config = {
        mode: uglify ? "production" : "development",
        context: appFullPath,
        watchOptions: {
            ignored: [
                appResourcesFullPath,
                // Don't watch hidden files
                "**/.*",
            ]
        },
        target: nativescriptTarget,
        entry: {
            bundle: entryPath,
            application: "./activity.android",
        },
        output: {
            pathinfo: false,
            path: dist,
            libraryTarget: "commonjs2",
            filename: "[name].js",
            globalObject: "global",
        },
        resolve: {
            extensions: [".ts", ".js", ".scss", ".css"],
            // Resolve {N} system modules from tns-core-modules
            modules: [
                resolve(__dirname, "node_modules/tns-core-modules"),
                resolve(__dirname, "node_modules"),
                "node_modules/tns-core-modules",
                "node_modules",
            ],
            alias: {
                '~': appFullPath
            },
            symlinks: true
        },
        resolveLoader: {
            symlinks: false
        },
        node: {
            // Disable node shims that conflict with NativeScript
            "http": false,
            "timers": false,
            "setImmediate": false,
            "fs": "empty",
            "__dirname": false,
        },
        devtool: "none",
        optimization: {
            splitChunks: {
                cacheGroups: {
                    vendor: {
                        name: "vendor",
                        chunks: "all",
                        test: (module, chunks) => {
                            const moduleName = module.nameForCondition ? module.nameForCondition() : '';
                            return /[\\/]node_modules[\\/]/.test(moduleName) ||
                                    appComponents.some(comp => comp === moduleName);
                        },
                        enforce: true,
                    },
                }
            },
            minimize: !!uglify,
            minimizer: [
                new UglifyJsPlugin({
                    uglifyOptions: {
                        parallel: true,
                        cache: true,
                        output: {
                            comments: false,
                        },
                        compress: {
                            // The Android SBG has problems parsing the output
                            // when these options are enabled
                            'collapse_vars': platform !== "android",
                            sequences: platform !== "android",
                        }
                    }
                })
            ],
        },
        module: {
            rules: [
                {
                    test: new RegExp(entryPath),
                    use: [
                        // Require all Android app components
                        platform === "android" && {
                            loader: "nativescript-dev-webpack/android-app-components-loader",
                            options: { modules: appComponents }
                        },

                        {
                            loader: "nativescript-dev-webpack/bundle-config-loader",
                            options: {
                                angular: true,
                                loadCss: !snapshot, // load the application css if in debug mode
                            }
                        },
                    ].filter(loader => !!loader)
                },

                { test: /\.html$|\.xml$/, use: "raw-loader" },

                // tns-core-modules reads the app.css and its imports using css-loader
                {
                    test: /[\/|\\]app\.css$/,
                    use: {
                        loader: "css-loader",
                        options: { minimize: false, url: false },
                    }
                },
                {
                    test: /[\/|\\]app\.scss$/,
                    use: [
                        { loader: "css-loader", options: { minimize: false, url: false } },
                        "sass-loader"
                    ]
                },
                {
                    test: /\.ts$/,
                    loaders: 'awesome-typescript-loader',
                    options: {
                        useCache: true,
                        forceIsolatedModules: true
                    }
                  },
                  {
                    test: /\.(ts|js)$/,
                    loaders: [
                      'angular-router-loader'
                    ]
                  },

                // Angular components reference css files and their imports using raw-loader
                { test: /\.css$/, exclude: /[\/|\\]app\.css$/, use: "raw-loader" },
                { test: /\.scss$/, exclude: /[\/|\\]app\.scss$/, use: ["raw-loader", "resolve-url-loader", "sass-loader"] },

                // Compile TypeScript files with ahead-of-time compiler.
                {
                    test: /.ts$/, use: [
                        "nativescript-dev-webpack/moduleid-compat-loader",
                        "@ngtools/webpack",
                    ]
                },

                // Mark files inside `@angular/core` as using SystemJS style dynamic imports.
                // Removing this will cause deprecation warnings to appear.
                {
                    test: /[\/\\]@angular[\/\\]core[\/\\].+\.js$/,
                    parser: { system: true },
                },
            ],
        },
        plugins: [
            // Define useful constants like TNS_WEBPACK
            new webpack.DefinePlugin({
                "global.TNS_WEBPACK": "true",
            }),
            // Remove all files from the out dir.
            new CleanWebpackPlugin([ `${dist}/**/*` ]),
            // Copy native app resources to out dir.
            new CopyWebpackPlugin([
                {
                    from: `${appResourcesFullPath}/${appResourcesPlatformDir}`,
                    to: `${dist}/App_Resources/${appResourcesPlatformDir}`,
                    context: projectRoot
                },
            ]),
            // Copy assets to out dir. Add your own globs as needed.
            new CopyWebpackPlugin([
                { from: "fonts/**" },
                { from: "**/*.jpg" },
                { from: "**/*.png" },
            ], { ignore: [`${relative(appPath, appResourcesFullPath)}/**`] }),
            // Generate a bundle starter script and activate it in package.json
            new nsWebpack.GenerateBundleStarterPlugin([
                "./vendor",
                "./bundle",
            ]),
            // For instructions on how to set up workers with webpack
            // check out https://github.com/nativescript/worker-loader
            new NativeScriptWorkerPlugin(),

            new AngularCompilerPlugin({
                host: platformHost,
                entryModule: resolve(appPath, "app.module#AppModule"),
                tsConfigPath: join(__dirname, "tsconfig.esm.json"),
                skipCodeGeneration: !aot,
            }),
            // Does IPC communication with the {N} CLI to notify events when running in watch mode.
            new nsWebpack.WatchStateLoggerPlugin(),
        ],
    };

    if (report) {
        // Generate report files for bundles content
        config.plugins.push(new BundleAnalyzerPlugin({
            analyzerMode: "static",
            openAnalyzer: false,
            generateStatsFile: true,
            reportFilename: resolve(projectRoot, "report", `report.html`),
            statsFilename: resolve(projectRoot, "report", `stats.json`),
        }));
    }

    if (snapshot) {
        config.plugins.push(new nsWebpack.NativeScriptSnapshotPlugin({
            chunk: "vendor",
            angular: true,
            requireModules: [
                "reflect-metadata",
                "@angular/platform-browser",
                "@angular/core",
                "@angular/common",
                "@angular/router",
                "nativescript-angular/platform-static",
                "nativescript-angular/router",
            ],
            projectRoot,
            webpackConfig: config,
        }));
    }

    return config;
};

```

[NativeScript Forum]: http://forum.nativescript.org
[issues]: https://github.com/nativescript/nativescript-dev-webpack/issues?utf8=✓&q=is%3Aissue
[demo apps]: ../demo
[documentation]: https://docs.nativescript.org/best-practices/bundling-with-webpack

**Comment by NickIliev** [comment]
@jgerryl the error `application entry point file not found` is often related to the fact that the source JS files are not present in the build application (in `/platform/android/app/src/main/assets/app`). This might happen due to a number of reasons. My suggestion is to try a clean rebuild. 

```
rm -rf node_modules platforms hooks
// also remove webpack.config.js but do not forget to add the extended activity later in the newly generated one
npm i
// perhaps add the extended activity in the generated webpack.config.js
tns platform add android
tns build android
tns run android --bundle
```

**Comment by NickIliev** [comment]
@jgerryl another thing we noticed is that you are setting the extended activity as application entry
```
 entry: {
    bundle: entryPath,
    application: "./activity.android",
},
```

Remove the line `application: "./activity.android",` unless you are not extending the `application`. Details [here](https://github.com/NativeScript/nativescript-dev-webpack/issues/564#issuecomment-399675425)

**Comment by jgerryl** [comment]
Hi @NickIliev thanks for your response, already done it but it gives another error. I'm using lazy load so need to install awesome-typescript-loader and angular-router-loader as you can see in my webpack.config.js. 

> when i click a button
```
JS: ERROR Error: Uncaught (in promise): Object: {"loadChunkError":true,"details":{"originalStack":"Error: Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):\nError: C:\\Users\\admin\\Documents\\Native\\myApp\\app\\home\\home.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.\n    at AngularCompilerPlugin.getCompiledFile (C:\\Users\\admin\\Documents\\Native\\myApp\\node_modules\\@ngtools\\webpack\\src\\packages\\ngtools\\webpack\\src\\angular_compiler_plugin.ts:951:15)\n    at plugin.done.then (C:\\Users\\admin\\Documents\\Native\\myApp\\node_modules\\@ngtools\\webpack\\src\\packages\\ngtools\\webpack\\src\\loader.ts:49:29)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)\n    at new ZoneAwareError (file:///data/data/com.myapp.id/files/app/vendor.js:69743:33)\n    at Object../home/home.module.ts (file:///data/data/com.myapp.id/files/app/0.js:6:7)\n    at...
JS: ERROR Error: Uncaught (in promise): Error: No NgModule metadata found for 'undefined'.
JS: Error: No NgModule metadata found for 'undefined'.
JS:     at NgModuleResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.NgModuleResolver.resolve (file:///data/data/com.myapp.id/files/app/vendor.js:19642:23) [angular]
JS:     at CompileMetadataResolver.push.../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (file:///data/data/com.myapp.id/files/app/vendor.js:18279:43) [angular]
JS:     at JitCompiler.push.../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (file:///data/data/com.myapp.id/files/app/vendor.js:30417:51) [angular]
JS:     at JitCompiler.push.../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (file:///data/data/com.myapp.id/files/app/vendor.js:30398:36) [angular]
JS:     at JitCompiler.push.../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler.compileModuleAsync (file:///data/data/com.myapp...
```

> error when tns run android --bundle
```
ERROR in ./home/home.module.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\admin\Documents\Native\myApp\app\home\home.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\admin\Documents\Native\myApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:951:15)
    at plugin.done.then (C:\Users\admin\Documents\Native\myApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:49:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./app.routing.ts 13:132-163
 @ ./app.module.ts
 @ ./main.ts

ERROR in ./register/register.module.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\admin\Documents\Native\myApp\app\register\register.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\admin\Documents\Native\myApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:951:15)
    at plugin.done.then (C:\Users\admin\Documents\Native\myApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:49:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./app.routing.ts 17:132-171
 @ ./app.module.ts
 @ ./main.ts

ERROR in ./sub-setting/sub-setting.module.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\admin\Documents\Native\myApp\app\sub-setting\sub-setting.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\admin\Documents\Native\myApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:951:15)
    at plugin.done.then (C:\Users\admin\Documents\Native\myApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:49:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./app.routing.ts 24:132-177
 @ ./app.module.ts
 @ ./main.ts

ERROR in [at-loader] ./app/activity.android.ts:15:77
    TS2445: Property 'onCreate' is protected and only accessible within class 'Activity' and its subclasses.

ERROR in [at-loader] ./app/activity.android.ts:20:78
    TS2445: Property 'onSaveInstanceState' is protected and only accessible within class 'Activity' and its subclasses.

ERROR in [at-loader] ./app/activity.android.ts:23:56
    TS2445: Property 'onStart' is protected and only accessible within class 'Activity' and its subclasses.

ERROR in [at-loader] ./app/activity.android.ts:26:55
    TS2445: Property 'onStop' is protected and only accessible within class 'Activity' and its subclasses.
```

and bunch of error like
```
ERROR in [at-loader] ./app/delegate.ios.ts:5:5
    TS2304: Cannot find name '__extends'.

ERROR in [at-loader] ./app/delegate.ios.ts:24:23
    TS2339: Property 'ObjCProtocols' does not exist on type '() => any'.

ERROR in [at-loader] ./app/shared/backend.service.ts:6:20
    TS2339: Property 'isLoggedIn' does not exist on type '() => void'.

ERROR in [at-loader] ./app/shared/backend.service.ts:263:20
    TS2339: Property 'baseUrl' does not exist on type '() => void'.

ERROR in [at-loader] ./app/shared/backend.service.ts:264:20
    TS2339: Property 'appUserHeader' does not exist on type '() => void'.

ERROR in [at-loader] ./app/shared/backend.service.ts:265:20
    TS2339: Property 'apiUrl' does not exist on type '() => void'.
```

**Comment by jgerryl** [comment]
Just want to share i solve error Module build failed and error when click a button by changing tsconfig.json and add include property and change files property like this
```
"include": [
    "./app/*.ts",
    "./app/**/*.ts"
],
"files": [
        "./app/delegate.ios.ts",
        "./app/activity.android.ts",
        "./app/main.ts"
    ],
```

so the remain errors are [at-loader]. If anyone could give a suggestion. Thanks

**Comment by c13andka** [comment]
+1

**Comment by NickIliev** [comment]
@jgerryl not exactly sure which of the errors you have encoutered are resolved - can you clarify the case and also test by updating to nativescript-dev-webpack@0.14.2 and following the updated instructions and examples as done [here](https://github.com/NativeScript/nativescript-dev-webpack/issues/568#issuecomment-399663658)

**Comment by jgerryl** [comment]
@NickIliev i already tried couple times from the link you gave still no good result.

Only this issue is resolved by using include
```
ERROR in ./home/home.module.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\admin\Documents\Native\myApp\app\home\home.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\admin\Documents\Native\myApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:951:15)
    at plugin.done.then (C:\Users\admin\Documents\Native\myApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:49:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./app.routing.ts 13:132-163
 @ ./app.module.ts
 @ ./main.ts

ERROR in ./register/register.module.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\admin\Documents\Native\myApp\app\register\register.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\admin\Documents\Native\myApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:951:15)
    at plugin.done.then (C:\Users\admin\Documents\Native\myApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:49:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./app.routing.ts 17:132-171
 @ ./app.module.ts
 @ ./main.ts

ERROR in ./sub-setting/sub-setting.module.ts
Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
Error: C:\Users\admin\Documents\Native\myApp\app\sub-setting\sub-setting.module.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\Users\admin\Documents\Native\myApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\angular_compiler_plugin.ts:951:15)
    at plugin.done.then (C:\Users\admin\Documents\Native\myApp\node_modules\@ngtools\webpack\src\packages\ngtools\webpack\src\loader.ts:49:29)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./app.routing.ts 24:132-177
 @ ./app.module.ts
 @ ./main.ts
```

**Comment by NickIliev** [comment]
@jgerryl you could contact me in[ the community slack](https://nativescriptcommunity.slack.com/messages/C0L9EEURY/) (username: `niliev`) and send me a sample project so I could investigate your case. The issue seems related to a configuration problem but without codebase to work with, I find it difficult to give any directions.

**Comment by c13andka** [comment]
Hello, did you guys solve this problem ? i have the same

**Comment by btulsi-ygrene** [comment]
Facing same issue

**Comment by NickIliev** [comment]
@c13andka @btulsi-ygrene can you guys share sample projects that are reproducing the issue? 

Please make sure that your project is updated to latest version of `nativescript-dev-webpack` . In [this article](https://docs.nativescript.org/releases/upgrade-instructions#updating-webpack-version-and-configuration), you can find automated upgrade scripts for Webpack and Angular.

**Comment by btulsi-ygrene** [comment]
upgrading from 0.14.2 => 0.14.3 resolved the issue. not sure what about 0.14.2 caused the issue.
