### ISSUE TITLE
showModal() produce TypeError: Cannot read property '_showNativeModalView' of undefined

### ISSUE THREAD

**Issue by webleaf** [NativeScript/nativescript-dev-webpack#598]
Using `showModal` produce error when I do `tns run android --bundle` or `tns run android --bundle --env.uglify`

```
onItemTouch(args: TouchGestureEventData) {
        const stackLayout = <StackLayout>args.object;
        if(args.action == up){
                stackLayout.page.showModal('views/pages/some-page', {}, () => {}, true, true);
        }
}
```
Such error for `tns run android --bundle`:
```
07-04 14:57:04.443 25877 25877 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodNative(Native Method)
07-04 14:57:04.443 25877 25877 E MessageQueue-JNI: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
07-04 14:57:04.443 25877 25877 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
07-04 14:57:04.443 25877 25877 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:970)
07-04 14:57:04.443 25877 25877 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:954)
07-04 14:57:04.443 25877 25877 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onTouch failed
System.err: 
System.err: TypeError: Cannot read property '_showNativeModalView' of undefined
System.err: File: "file:///data/data/com.test/files/app/vendor.js, line: 25614, column: 17
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/core/view/view-common.js.ViewCommon.showModal', file:'file:///data/data/com.test/files/app/vendor.js', line: 25614, column: 18
System.err: 	Frame: function:'module.exports../views/pages/test-page/test-page-view-model.ts.TestPageViewModel.onItemTouch', file:'file:///data/data/com.test/files/app/bundle.js', line: 811, column: 34
System.err: 	Frame: function:'_executeCallback', file:'file:///data/data/com.test/files/app/vendor.js', line: 31228, column: 27
System.err: 	Frame: function:'push.../node_modules/tns-core-modules/ui/gestures/gestures.js.GesturesObserver.androidOnTouchEvent', file:'file:///data/data/com.test/files/app/vendor.js', line: 31171, column: 13
System.err: 	Frame: function:'', file:'file:///data/data/com.test/files/app/vendor.js', line: 26454, column: 29
System.err: 	Frame: function:'TouchListenerImpl.onTouch', file:'file:///data/data/com.test/files/app/vendor.js', line: 26453, column: 22
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err: 	at java.lang.Object_vendor_26445_32_TouchListenerImpl.onTouch(java.lang.Object.java)
System.err: 	at android.view.View.dispatchTouchEvent(View.java:10775)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2858)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2534)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:605)
System.err: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1895)
System.err: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3241)
System.err: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:567)
System.err: 	at android.view.View.dispatchPointerEvent(View.java:11008)
System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5155)
System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5007)
System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4585)
System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4551)
System.err: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4684)
System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4559)
System.err: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4741)
System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4585)
System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4551)
System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4559)
System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
System.err: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
System.err: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7024)
System.err: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6985)
System.err: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7202)
System.err: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
System.err: 	at android.os.MessageQueue.next(MessageQueue.java:323)
System.err: 	at android.os.Looper.loop(Looper.java:136)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
ActivityManager: Process com.test (pid 25877) has died(55,591)
```

And such error for `tns run android --bundle --env.uglify`:
```
07-04 14:47:44.564 25170 25170 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodNative(Native Method)
07-04 14:47:44.564 25170 25170 E MessageQueue-JNI: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
07-04 14:47:44.564 25170 25170 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
07-04 14:47:44.564 25170 25170 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:970)
07-04 14:47:44.564 25170 25170 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:954)
07-04 14:47:44.564 25170 25170 E MessageQueue-JNI: 	at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err: com.tns.NativeScriptException: 
System.err: Calling js method onTouch failed
System.err: 
System.err: TypeError: Cannot read property '_showNativeModalView' of undefined
System.err: File: "file:///data/data/com.test/files/app/vendor.js, line: 1, column: 499237
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'n.showModal', file:'file:///data/data/com.test/files/app/vendor.js', line: 1, column: 499238
System.err: 	Frame: function:'t.onItemTouch', file:'file:///data/data/com.test/files/app/bundle.js', line: 1, column: 25698
System.err: 	Frame: function:'g', file:'file:///data/data/com.test/files/app/vendor.js', line: 1, column: 461977
System.err: 	Frame: function:'r.androidOnTouchEvent', file:'file:///data/data/com.test/files/app/vendor.js', line: 1, column: 461060
System.err: 	Frame: function:'', file:'file:///data/data/com.test/files/app/vendor.js', line: 1, column: 4896
System.err: 	Frame: function:'r.onTouch', file:'file:///data/data/com.test/files/app/vendor.js', line: 1, column: 4874
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:970)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:954)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:946)
System.err: 	at com.tns.gen.java.lang.Object_vendor_1_4650_r.onTouch(Object_vendor_1_4650_r.java:18)
System.err: 	at android.view.View.dispatchTouchEvent(View.java:10775)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2858)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2534)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2864)
System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2549)
System.err: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:605)
System.err: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1895)
System.err: 	at android.app.Activity.dispatchTouchEvent(Activity.java:3241)
System.err: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:567)
System.err: 	at android.view.View.dispatchPointerEvent(View.java:11008)
System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5155)
System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5007)
System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4585)
System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4551)
System.err: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4684)
System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4559)
System.err: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4741)
System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4585)
System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4551)
System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4559)
System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4532)
System.err: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7092)
System.err: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7024)
System.err: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6985)
System.err: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7202)
System.err: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
System.err: 	at android.os.MessageQueue.next(MessageQueue.java:323)
System.err: 	at android.os.Looper.loop(Looper.java:136)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6776)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1518)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
ActivityManager: Process com.test (pid 25170) has died(51,587)
```

My `package.json`:
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.test",
    "tns-android": {
      "version": "4.1.3"
    }
  },
  "dependencies": {
    "nativescript-snackbar": "^3.1.0",
    "nativescript-sqlite": "^2.2.1",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-ui-dataform": "^3.6.1",
    "nativescript-ui-listview": "^3.5.8",
    "nativescript-ui-sidedrawer": "^4.1.1",
    "tns-core-modules": "^4.1.0",
    "tslib": "^1.9.3"
  },
  "devDependencies": {
    "@types/node": "^10.5.1",
    "awesome-typescript-loader": "~3.1.3",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "clean-webpack-plugin": "~0.1.19",
    "copy-webpack-plugin": "^4.5.2",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "^0.7.2",
    "nativescript-dev-webpack": "^0.14.2",
    "nativescript-worker-loader": "^0.9.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "tns-platform-declarations": "^4.1.0",
    "typescript": "~2.8.4",
    "uglifyjs-webpack-plugin": "^1.2.7",
    "webpack": "^4.10.2",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "~2.1.3",
    "webpack-sources": "~1.1.0"
  }
}
```

**Comment by NickIliev** [comment]
@webleaf using [this test project](https://github.com/NickIliev/NS-Issues-2018-II/tree/master/nativescript-dev-webpack/issue-598) the modal pages are working as expected with `--bundle`. I am using [the same codebase](https://github.com/NickIliev/NS-Issues-2018-II/blob/master/nativescript-dev-webpack/issue-598/app/main-page.ts#L11-L16) as the one you have provided. Please do let me know if there is some specifics in the code that are needed to reproduce the issue.

**Comment by webleaf** [comment]
@NickIliev sorry. Problem was in file naming. My page files wasn't postfixed with `root|page|fragment` as described in `bundle-config.ts`
It's second time when I stuck on this.
Why only files postfixed with `root|page|fragment` are bundled by default?
Why not bundled all `xml, css, js, ts, scss` files in the `app/` folder?
