### ISSUE TITLE
build fail with 0.15.1

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/nativescript-dev-webpack#629]
I tried to upgrade to 0.15.1.
Now build fails with this error:
```
/Volumes/data/dev/nativescript/Mini2SmartApp/node_modules/webpack-cli/bin/webpack.js:449
                                throw err;
                                ^

TypeError: Cannot read property 'synchronous' of undefined
    at new SyncDelegateHost (/Volumes/data/dev/nativescript/Mini2SmartApp/node_modules/@angular-devkit/core/src/virtual-fs/host/sync.js:14:37)
    at new WebpackCompilerHost (/Volumes/data/dev/nativescript/Mini2SmartApp/node_modules/@ngtools/webpack/src/compiler_host.js:125:26)
    at compiler.hooks.environment.tap (/Volumes/data/dev/nativescript/Mini2SmartApp/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:443:41)
    at SyncHook.eval [as call] (eval at create (/Volumes/data/dev/nativescript/Mini2SmartApp/node_modules/tapable/lib/HookCodeFactory.js:17:12), <anonymous>:7:1)
    at SyncHook.lazyCompileHook [as _call] (/Volumes/data/dev/nativescript/Mini2SmartApp/node_modules/tapable/lib/Hook.js:35:21)
    at webpack (/Volumes/data/dev/nativescript/Mini2SmartApp/node_modules/webpack/lib/webpack.js:40:30)
    at processOptions (/Volumes/data/dev/nativescript/Mini2SmartApp/node_modules/webpack-cli/bin/webpack.js:437:16)
    at yargs.parse (/Volumes/data/dev/nativescript/Mini2SmartApp/node_modules/webpack-cli/bin/webpack.js:513:3)
    at Object.parse (/Volumes/data/dev/nativescript/Mini2SmartApp/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /Volumes/data/dev/nativescript/Mini2SmartApp/node_modules/webpack-cli/bin/webpack.js:218:8
    at Object.<anonymous> (/Volumes/data/dev/nativescript/Mini2SmartApp/node_modules/webpack-cli/bin/webpack.js:515:3)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Volumes/data/dev/nativescript/Mini2SmartApp/node_modules/webpack/bin/webpack.js:157:2)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:695:10)
    at startup (internal/bootstrap/node.js:201:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:516:3)
```
my packages:
```
"dependencies": {
    "@angular/animations": "6.1.2",
    "@angular/common": "6.1.2",
    "@angular/compiler": "6.1.2",
    "@angular/core": "6.1.2",
    "@angular/forms": "6.1.2",
    "@angular/http": "6.1.2",
    "@angular/platform-browser": "6.1.2",
    "@angular/platform-browser-dynamic": "6.1.2",
    "@angular/router": "6.1.2",
    "@tweenjs/tween.js": "17.2.0",
    "nativescript-angular": "6.1.0",
    "nativescript-loading-indicator": "~2.4.0",
    "nativescript-localize": "~3.0.5",
    "nativescript-ngx-fonticon": "~4.2.0",
    "nativescript-theme-core": "~1.0.4",
    "nativescript-toast": "~1.4.6",
    "nativescript-ui-gauge": "^3.6.0",
    "nativescript-ui-sidedrawer": "^4.2.1",
    "reflect-metadata": "~0.1.12",
    "rxjs": "~6.2.2",
    "tns-core-modules": "~4.2.0",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "0.7.2",
    "@angular/compiler-cli": "6.1.2",
    "@types/tween.js": "^16.9.0",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "^1.6.0",
    "nativescript-dev-typescript": "~0.7.2",
    "nativescript-dev-webpack": "0.15.1",
    "tns-platform-declarations": "^4.2.0",
    "typescript": "^3.0.1"
  },
```
and my Webpack angular part:
```
new AngularCompilerPlugin({
                // host: Object.assign(nsWebpack.getResolver([platform, "tns"]), {capabilities:{synchronous:true}}),
                host: nsWebpack.getResolver([platform, "tns"]),
                preserveSymlinks:true,
                entryModule: resolve(appPath, 'app.module#AppModule'),
                tsConfigPath: join(__dirname, 'tsconfig.esm.json'),
                hostReplacementPaths: {
                    "/Volumes/data/dev/nativescript/nativescript-bluetooth/plugin/": join(__dirname, "node_modules/nativescript-bluetooth"),
                    "/Volumes/data/dev/nativescript/nativescript-blurview/plugin/": join(__dirname, "node_modules/nativescript-blurview"),
                    "/Volumes/data/dev/nativescript/nativescript-material-components/plugin/": join(__dirname, "nativescript-material-components"),
                  },
                compilerOptions:{
                    preserveSymlinks:true
                },
                skipCodeGeneration: !aot,
                sourceMap: !!sourceMap
            }),
```

**Comment by farfromrefug** [comment]
My bad wrongly upgraded from template!
