### ISSUE TITLE
Module not found: Error: Can't resolve 'nativescript-dev-webpack/style-hot-loader'

### ISSUE THREAD

**Issue by ErgoFriend** [NativeScript/nativescript-dev-webpack#665]
```
Win10 HOME
vue 3.0.3
npm 5.6.0
node v8.11.4
```

Why did not install ```style-hot-loader.js``` ?
I used ```vue init nativescript-vue/vue-cli-template sample```, then ``` tns run android --bundle``` .
But it makes error...
[https://nativescript-vue.org/en/docs/getting-started/upgrade-guide/](https://nativescript-vue.org/en/docs/getting-started/upgrade-guide/)

```
ERROR in ./main.js
Module not found: Error: Can't resolve 'nativescript-dev-webpack/style-hot-loader' in 'C:\Users\ergop\Documents\Development\NativeScript\sample\app'
 @ ./main.js 17:0-23
```

![image](https://user-images.githubusercontent.com/29725082/45625978-2bc00f00-bac9-11e8-9599-dfb1cddd772a.png)

All logs
```
An uncaught Exception occurred on "main" thread.
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error: Cannot find module './HelloWorld.vue?vue&type=style&index=0&id=763db97b&scoped=true&lang=css&'
File: "file:///data/data/org.nativescript.application/files/app/bundle.js, line: 523, column: 222

StackTrace: 
	Frame: function:'webpackMissingModule', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 523, column: 85
	Frame: function:'./components/HelloWorld.vue', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 523, column: 233
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'./router/index.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 678, column: 80
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 627, column: 65
	Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 658, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


Error: Cannot find module './HelloWorld.vue?vue&type=style&index=0&id=763db97b&scoped=true&lang=css&'
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'webpackMissingModule', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 523, column: 85
	Frame: function:'./components/HelloWorld.vue', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 523, column: 233
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'./router/index.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 678, column: 80
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 627, column: 65
	Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 658, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


Error: Cannot find module './HelloWorld.vue?vue&type=style&index=0&id=763db97b&scoped=true&lang=css&'
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'webpackMissingModule', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 523, column: 85
	Frame: function:'./components/HelloWorld.vue', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 523, column: 233
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'./router/index.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 678, column: 80
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 627, column: 65
	Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 658, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5743)
	at android.app.ActivityThread.-wrap1(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: com.tns.NativeScriptException: 

Error calling module function 

Error calling module function 

Error: Cannot find module './HelloWorld.vue?vue&type=style&index=0&id=763db97b&scoped=true&lang=css&'
File: "file:///data/data/org.nativescript.application/files/app/bundle.js, line: 523, column: 222

StackTrace: 
	Frame: function:'webpackMissingModule', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 523, column: 85
	Frame: function:'./components/HelloWorld.vue', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 523, column: 233
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'./router/index.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 678, column: 80
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 627, column: 65
	Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 658, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


Error: Cannot find module './HelloWorld.vue?vue&type=style&index=0&id=763db97b&scoped=true&lang=css&'
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'webpackMissingModule', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 523, column: 85
	Frame: function:'./components/HelloWorld.vue', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 523, column: 233
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'./router/index.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 678, column: 80
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 627, column: 65
	Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 658, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


Error: Cannot find module './HelloWorld.vue?vue&type=style&index=0&id=763db97b&scoped=true&lang=css&'
File: "<unknown>, line: 1, column: 265

StackTrace: 
	Frame: function:'webpackMissingModule', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 523, column: 85
	Frame: function:'./components/HelloWorld.vue', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 523, column: 233
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'./router/index.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 678, column: 80
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 627, column: 65
	Frame: function:'./main.js', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 658, column: 30
	Frame: function:'__webpack_require__', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 76, column: 30
	Frame: function:'checkDeferredModules', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 45, column: 23
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 149, column: 18
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/bundle.js', line: 152, column: 10
	Frame: function:'require', file:'', line: 1, column: 266
	Frame: function:'', file:'file:///data/data/org.nativescript.application/files/app/starter.js', line: 2, column: 1
	Frame: function:'require', file:'', line: 1, column: 266


	at com.tns.Runtime.runModule(Native Method)
	at com.tns.Runtime.runModule(Runtime.java:553)
	at com.tns.Runtime.run(Runtime.java:545)
	at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:21)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
	... 8 more
```

**Comment by rigor789** [comment]
I can confirm, version `0.17.0-2018-09-17-01` and onward does not have the `style-hot-loader.js` file anymore. 

As a temporary workaround, pin the version to `0.17.0-2018-09-15-02` and it should work.

**Comment by nikolasdas** [comment]
> 
> 
> I can confirm, version `0.17.0-2018-09-17-01` and onward does not have the `style-hot-loader.js` file anymore.
> 
> As a temporary workaround, pin the version to `0.17.0-2018-09-15-02` and it should work.

Confirmed, this does the trick! Thank you! 👍

**Comment by ngstwr** [comment]
OMG! I have been trying to fix this since last 4 hours.

**Comment by ErgoFriend** [comment]
Thunk you so match :D

```
  },
  "dependencies": {
  },
  "devDependencies": {
   - "nativescript-dev-webpack": "^0.17.0-2018-09-12-01",
   + "nativescript-dev-webpack": "0.17.0-2018-09-12-01",
  }
}
```

**Comment by rigor789** [comment]
@ErgoFriend Please re-open the issue, because it still needs solving, the solution is just temporary.

**Comment by ErgoFriend** [comment]
I see

**Comment by vchimev** [comment]
Hey @rigor789 and @ErgoFriend,

We've published a few `next` packages which do not contain the HMR related loaders and source while improving our CI build system. However, `next` version again contains the latest source code from the `master` branch, so feel free to count on it.

**Comment by rorgonas** [comment]
> nativescript-dev-webpack

@ErgoFriend version change from "nativescript-dev-webpack": "next" to "nativescript-dev-webpack": "0.17.0-2018-09-12-01"  indeed fixed my problem after hours of trying.

When I checked back my package.json file I saw that it has been updated as:
"nativescript-dev-webpack": "^0.20.2"

Regards.

**Comment by rigor789** [comment]
@rorgonas if you are working with a newer project, it's likely a bad idea to pin to such an old version.
