### ISSUE TITLE
Build fails with webpack-cli 2.1.1 and webpack 4.20.2

### ISSUE THREAD

**Issue by sis0k0** [NativeScript/nativescript-dev-webpack#674]
The webpack build fails when `webpack-cli` **2.1.1** and `webpack` **4.20.2** are installed.
Stack trace:
```
/Users/.../node_modules/webpack-cli/bin/config-yargs.js:89
                describe: optionsSchema.definitions.output.properties.path.description,
                                                           ^

TypeError: Cannot read property ‘properties’ of undefined
   at module.exports (/Users/.../node_modules/webpack-cli/bin/config-yargs.js:89:48)
   at /Users/.../node_modules/webpack-cli/bin/webpack.js:60:27
   at Object.<anonymous> (/Users/.../node_modules/webpack-cli/bin/webpack.js:515:3)
   at Module._compile (module.js:653:30)
   at Object.Module._extensions..js (module.js:664:10)
   at Module.load (module.js:566:32)
   at tryModuleLoad (module.js:506:12)
   at Function.Module._load (module.js:498:3)
   at Module.require (module.js:597:17)
```

This affects {N}+Web code-sharing projects that depend on `webpack` **4.20.2** (brought by `@angular-devkit/build-angular`).
The other flavors of NativeScript projects are not affected, because they depend on older versions of `webpack` (brought by `nativescript-dev-webpack`).
The solution is to update the versions of both packages to latest - `webpack-cli` to **3.1.1** and `webpack` to **4.20.2**.

related to https://github.com/webpack/webpack/issues/8082, https://github.com/webpack/webpack-cli/issues/607.

10x to @SvetoslavTsenov for reporting.

**Comment by sis0k0** [comment]
resolved in 0.16.2
