### ISSUE TITLE
TypeError: chunk.getChildIdsByOrders is not a function

### ISSUE THREAD

**Issue by henrywongkar** [NativeScript/nativescript-dev-webpack#697]
**Environment**
 - CLI: 4.2.3
 - Cross-platform modules:
 - Android Runtime: 4.2.0
 - iOS Runtime: 4.2.0
 - Plugin(s):
 - Node.js: 8.12.0
 
"nativescript": {
    "tns-ios": {
      "version": "4.2.0"
    },
    "tns-android": {
      "version": "4.2.0"
    }
  },
  "android": {
    "markingMode": "none"
  },
  "dependencies": {
    "@angular/common": "^6.1.0",
    "@angular/compiler": "^6.1.0",
    "@angular/core": "^6.1.0",
    "@angular/forms": "^6.1.0",
    "@angular/http": "^6.1.0",
    "@angular/platform-browser": "^6.1.0",
    "@angular/platform-browser-dynamic": "^6.1.0",
    "@angular/router": "^6.1.0",
    "kinvey-nativescript-sdk": "^3.11.5",
    "nativescript-angular": "^6.2.0-2018-10-19-164050-02",
    "nativescript-carousel": "^4.0.2",
    "nativescript-intl": "~3.0.0",
    "nativescript-theme-core": "^1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~6.0.0",
    "tns-core-modules": "^5.2.0-2018-10-19-184840-04",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.7.1",
    "@angular-devkit/core": "^0.5.13",
    "@angular/compiler-cli": "^6.1.0",
    "@ngtools/webpack": "^6.2.6",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.10.0",
    "clean-webpack-plugin": "~0.1.19",
    "codelyzer": "^3.0.1",
    "copy-webpack-plugin": "^4.5.4",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^2.1.2",
    "fs-extra": "^0.30.0",
    "glob": "^7.1.2",
    "lazy": "1.0.11",
    "markdown-snippet-injector": "^0.2.0",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-typescript": "next",
    "nativescript-dev-webpack": "^0.17.0-rc.0",
    "nativescript-worker-loader": "~0.8.1",
    "opener": "^1.4.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.3.0",
    "rimraf": "^2.5.3",
    "tar.gz": "^1.0.5",
    "tns-platform-declarations": "^3.4.1",
    "tslint": "^5.11.0",
    "typescript": "~2.7.2",
    "uglifyjs-webpack-plugin": "^1.2.7",
    "webpack": "~4.5.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "~2.0.14",
    "webpack-sources": "~1.1.0"
  },

**Describe the bug**

TypeError: chunk.getChildIdsByOrders is not a function
    at chunkTemplate.hooks.hashForChunk.tap (/home/user/project/node_modules/nativescript-dev-webpack/node_modules/webpack/lib/web/JsonpChunkTemplatePlugin.js:66:38)
    at SyncHook.eval [as call] (eval at create (/home/user/project/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at SyncHook.lazyCompileHook (/home/user/project/node_modules/tapable/lib/Hook.js:154:20)
    at ChunkTemplate.updateHashForChunk (/home/user/project/node_modules/webpack/lib/ChunkTemplate.js:49:27)
    at Compilation.createHash (/home/user/project/node_modules/webpack/lib/Compilation.js:1700:13)
    at hooks.optimizeTree.callAsync.err (/home/user/project/node_modules/webpack/lib/Compilation.js:939:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/user/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/home/user/project/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/home/user/project/node_modules/webpack/lib/Compilation.js:896:27)
    at hooks.make.callAsync.err (/home/user/project/node_modules/webpack/lib/Compiler.js:479:17)
    at _done (eval at create (/home/user/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at _err2 (eval at create (/home/user/project/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:48:22)
    at _addModuleChain (/home/user/project/node_modules/webpack/lib/Compilation.js:764:12)
    at processModuleDependencies.err (/home/user/project/node_modules/webpack/lib/Compilation.js:703:9)
    at _combinedTickCallback (internal/process/next_tick.js:132:7)
    at process._tickCallback (internal/process/next_tick.js:181:9)

**To Reproduce**

tns build android --bundle --env.uglify --env.aot --env.snapshot --release --keyStorePath path/to/keystore --keyStorePassword password --keyStoreAlias alias --keyStoreAliasPassword aliaspass

**Comment by NickIliev** [comment]
@henrywongkar try updating to latest version which as of now is 5.x.x (for tns-core-modules and tns-android) and also run[ the upgrade instruction ](https://docs.nativescript.org/angular/releases/upgrade-instructions)for nativescript-dev-webpack.
