### ISSUE TITLE
Some issues with compiling

### ISSUE THREAD

**Issue by abhayastudios** [NativeScript/nativescript-dev-webpack#86]
I am running in a couple of issues bundling my project. Not sure if they are related or not and whether they are issues with nativescript-dev-webpack or with my project specifically. Hoping someone can point me in the right direction.

First of all, when running `npm run start-ios-bundle` I get the error below:

```
ERROR in ./components/group-mgt-modal.ts
Module build failed: TypeError: Cannot read property 'toUpperCase' of undefined
    at /Users/joni/projects/friendy/node_modules/nativescript-dev-webpack/tns-xml-loader.js:41:77
    at Array.map (native)
    at Object.onopentag (/Users/joni/projects/friendy/node_modules/nativescript-dev-webpack/tns-xml-loader.js:41:47)
    at Parser.onopentagend (/Users/joni/projects/friendy/node_modules/htmlparser2/lib/Parser.js:172:37)
    at Tokenizer._stateBeforeAttributeName (/Users/joni/projects/friendy/node_modules/htmlparser2/lib/Tokenizer.js:230:13)
    at Tokenizer._parse (/Users/joni/projects/friendy/node_modules/htmlparser2/lib/Tokenizer.js:658:9)
    at Tokenizer.write (/Users/joni/projects/friendy/node_modules/htmlparser2/lib/Tokenizer.js:632:7)
    at Parser.write (/Users/joni/projects/friendy/node_modules/htmlparser2/lib/Parser.js:334:18)
    at Object.parseResource (/Users/joni/projects/friendy/node_modules/nativescript-dev-webpack/tns-xml-loader.js:53:12)
 @ ./components/group-mgt-modal.ngfactory.ts 12:0-45
 @ ./app.module.ngfactory.ts
 @ ./main.aot.ts
```

The thing is that `./components/group-mgt-modal.ts` does not contain any `toUpperCase`, so how can I know where the problem is?

I tried to run `/node_modules/.bin/ngc -p tsconfig.aot.json` so it will generate the `*.ngfactory.ts` files to inspect, but looking at `./components/group-mgt-modal.ngfactory.ts` line 12 I don't see anything that seems relevant. How should I investigate this?

Another thing (maybe related?) is that when I run `/node_modules/.bin/ngc -p tsconfig.aot.json`, I get all kinds of errors that seem both related to the `nativescript-telerik-ui` plugin (even though I am using v1.6.1 which should work with AoT), as well as to the `tns-core-modules`:

```
$ node_modules/.bin/ngc -p tsconfig.aot.json
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:21:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/page/page.d.ts' is not a module.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:50:20: Supplied parameters do not match any signature of call target.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:81:53: Property 'drawerOpening' does not exist on type 'RadSideDrawerComponent'.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:82:53: Property 'drawerOpen' does not exist on type 'RadSideDrawerComponent'.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:83:53: Property 'drawerClosing' does not exist on type 'RadSideDrawerComponent'.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:84:53: Property 'drawerClosed' does not exist on type 'RadSideDrawerComponent'.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:93:20: Supplied parameters do not match any signature of call target.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:120:20: Supplied parameters do not match any signature of call target.
Error at /Users/joni/projects/testjoni/app/components/availability-details-modal.ngfactory.ts:27:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/page/page.d.ts' is not a module.
Error at /Users/joni/projects/testjoni/app/components/group-mgt-modal.ngfactory.ts:19:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/page/page.d.ts' is not a module.
Error at /Users/joni/projects/testjoni/app/components/header-bar.ngfactory.ts:19:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/page/page.d.ts' is not a module.
Error at /Users/joni/projects/testjoni/app/app.component.ngfactory.ts:26:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/page/page.d.ts' is not a module.
Error at /Users/joni/projects/testjoni/app/app.module.ngfactory.ts:77:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/frame/frame.d.ts' is not a module.
Error at /Users/joni/projects/testjoni/app/app.module.ngfactory.ts:78:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/page/page.d.ts' is not a module.
```

By the way, the first time I ran it, I got also load of errors about variables/methods that I use in templates being private. I fixed them after I saw these errors, but should they not be displayed when running by the book `npm run start-ios-bundle`?

```
$ tns info
All NativeScript components versions information
┌──────────────────┬─────────────────┬────────────────┬───────────────┐
│ Component        │ Current version │ Latest version │ Information   │
│ nativescript     │ 2.5.2           │ 2.5.2          │ Up to date    │
│ tns-core-modules │ 2.5.1           │ 2.5.1          │ Up to date    │
│ tns-android      │                 │ 2.5.0          │ Not installed │
│ tns-ios          │ 2.5.0           │ 2.5.0          │ Up to date    │
└──────────────────┴─────────────────┴────────────────┴───────────────┘
```

One last thing:
```
$ node --version
v7.6.0
$ npm --version
4.4.0
```

Also tried using node v6.9.5 & npm 4.1.2 with the same result.
Thanks!

**Comment by sis0k0** [comment]
Hi @abhayastudios,

I think that's a problem with the plugin. Could you please share the `group-mgt-modal.ts` file so we can track it down easier?

**Comment by abhayastudios** [comment]
Sure

```
import {Component,ElementRef,OnInit,ViewChild} from '@angular/core';
import {ModalDialogParams} from "nativescript-angular/modal-dialog";
import {Page} from "ui/page";
import {confirm as Confirm} from "ui/dialogs";
import {GroupCurrentMembersComponent} from '../components/group-current-members';
import {GroupsData} from '../providers/groups-data';
import {KeyboardProvider} from '../providers/keyboard'
import {SessionProvider} from '../providers/session';

@Component({
  template: `
    <StackLayout backgroundColor="white" style="height:100%; width:100%">
      <-- header bar -->
      <GridLayout rows="50" columns="50 * 50" class="header">
        <Button text="&#xf014;" row="0" col="0" class="fa header-text header-btn" (tap)="onDeleteGroup()"></Button>
        <Label text="Manage Group" row="0" col="1" class="center header-text"></Label>
        <Button text="&#xf00d;" row="0" col="2" class="fa header-text header-btn" (tap)="params.closeCallback(group)"></Button>
      </GridLayout>
      <GridLayout rows="auto auto *" columns="*">
        <SearchBar row="0" col="0" [text]="searchFilter" hint="Search" (propertyChange)="searchFilter=$event.value"></SearchBar>

        <!-- member list -->
        <ScrollView row="1" col="0" orientation="horizontal" #memberScroll>
          <GroupCurrentMembers [members]="group.member_phonebook_ids" (tap)="onMemberTap($event)"></GroupCurrentMembers>
        </ScrollView>

        <-- contact list -->
        <ListView row="2" col="0" [items]="session.cachedPhonebook | searchFilter: searchFilter">
          <template let-item="item" let-index="index">
            <GridLayout rows="auto" columns="55 * 30" class="list-item" (tap)="onContactAdd(item)">
              <Image row="0" col="0" *ngIf="item.thumbnail" [src]="item.thumbnail" class="thumbnail"></Image>
              <Label row="0" col="0" *ngIf="!item.thumbnail" text="&#xf2be;" class="fa thumbnail-awesome"></Label>
              <Label row="0" col="1" [text]="item.name" class="contact-row"></Label>
              <Label row="0" col="2" text="&#xf067;" class="fa icon-btn"></Label>
            </GridLayout>
          </template>
        </ListView>
      </GridLayout>
    </StackLayout>
  `,
  styles: [`
    ListView { separator-color:transparent; height:100%; }
    .header { background-color:#0d88ff; }
    .header-text { color:white; font-size: 18; vertical-align:center; }
    .header-btn { width:30; }
    .list-item { margin:1 0; padding:10; background-color: #f6f6f6; }
    .thumbnail { width:50; height:50; border-radius:25; vertical-align:center; text-align:center; }
    .thumbnail-awesome { font-size:50; color:#b7b7b7; vertical-align:center; text-align:center; }
    .contact-row { font-size: 18; color: #000000; margin-left: 10; vertical-align:center; }
    .icon-btn { color: #a8a8a8; font-size: 22; text-align: center; vertical-align: center; padding:0 5; width:30; }
    .delete-group-btn { font-size:18; color:black; background-color:#ef2a2f; height:50; vertical-align:center; text-align:center; }
  `]
})
export class GroupMgtModal implements OnInit {
  @ViewChild('memberScroll') memberScroll: ElementRef;

  public group:any;
  public searchFilter:string = '';

  constructor(private groups:GroupsData, private keyboard:KeyboardProvider, public params: ModalDialogParams, private page:Page, public session:SessionProvider) {
    this.group = this.params.context;
  }

  public ngOnInit() {
    this.keyboard.hideAndroidKeyBoard(this.page);
  }

  public updateGroup() {
    this.params.closeCallback(this.group); // reference to group object is passed to parent
    console.dump(this.group);
  }

  public onContactAdd(contact) {
    if (this.group.member_phonebook_ids.indexOf(contact.phonebook_id)==-1) { // contact is not a member already
      this.searchFilter='';
      this.group.member_phonebook_ids.push(contact.phonebook_id);
      this.group.member_phonebook_ids = [...this.group.member_phonebook_ids]; // force reference change so members binding gets updated
      // scroll to end of scrollview - use timeout to allow for new element to be added to view
      setTimeout(() => { this.memberScroll.nativeElement.scrollToHorizontalOffset(this.memberScroll.nativeElement.scrollableWidth, true); },100);
    } else { 
      console.log('Contact already group member!');
    }
  }

  public onMemberTap(event) {
    // remove member from group
    let memberIndex = this.group.member_phonebook_ids.indexOf(event.value);

    if (memberIndex>-1) {
      this.group.member_phonebook_ids.splice(memberIndex, 1);
      this.group.member_phonebook_ids = [...this.group.member_phonebook_ids]; // force reference change so members get updated
    }
  }

  public onDeleteGroup() {
    let options = {
      title: 'Delete Group',
      message: `Are you sure you want to delete group ${this.group.name}?`,
      okButtonText: 'Yes',
      cancelButtonText: 'No'
    };

    Confirm(options).then((result: boolean) => {
      // result can be true/false/undefined
      if (result===true) {
        this.groups.deleteGroup(this.group);
        setTimeout(() => { this.params.closeCallback(null); },100); // close modal
      }
    });
  }
}
```

**Comment by sis0k0** [comment]
Hey @abhayastudios,

The error is actually caused by these invalid comments:

```
<-- header bar -->
...
<-- contact list -->
```

The comments should start with `<!--`. I'll make a fix in the plugin to ignore invalid comments or probably throw a better error. Thanks!

**Comment by abhayastudios** [comment]
Wow... you are right! Now it compiles :) I must have reviewed that file dozens of times but failed to noticed the invalid comment!

Thank you so much! :)

By the way I still get these errors when running `./node_modules/.bin/ngc -p tsconfig.aot.json`:

```
$ node_modules/.bin/ngc -p tsconfig.aot.json
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:21:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/page/page.d.ts' is not a module.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:50:20: Supplied parameters do not match any signature of call target.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:81:53: Property 'drawerOpening' does not exist on type 'RadSideDrawerComponent'.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:82:53: Property 'drawerOpen' does not exist on type 'RadSideDrawerComponent'.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:83:53: Property 'drawerClosing' does not exist on type 'RadSideDrawerComponent'.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:84:53: Property 'drawerClosed' does not exist on type 'RadSideDrawerComponent'.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:93:20: Supplied parameters do not match any signature of call target.
Error at /Users/joni/projects/testjoni/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.ngfactory.ts:120:20: Supplied parameters do not match any signature of call target.
Error at /Users/joni/projects/testjoni/app/components/availability-details-modal.ngfactory.ts:27:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/page/page.d.ts' is not a module.
Error at /Users/joni/projects/testjoni/app/components/group-mgt-modal.ngfactory.ts:19:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/page/page.d.ts' is not a module.
Error at /Users/joni/projects/testjoni/app/components/header-bar.ngfactory.ts:19:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/page/page.d.ts' is not a module.
Error at /Users/joni/projects/testjoni/app/app.component.ngfactory.ts:26:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/page/page.d.ts' is not a module.
Error at /Users/joni/projects/testjoni/app/app.module.ngfactory.ts:77:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/frame/frame.d.ts' is not a module.
Error at /Users/joni/projects/testjoni/app/app.module.ngfactory.ts:78:27: File '/Users/joni/projects/testjoni/node_modules/tns-core-modules/ui/page/page.d.ts' is not a module.
```

Any idea why the webpack doesn't alert on these? Also any advice on how to include JS assets that I use in web workers? It appears they are not automatically included in the bundle:

```
[native code]: JS ERROR Error: Could not find module './get-contacts-worker.js'. Computed path '/Users/joni/Library/Developer/CoreSimulator/Devices/F62604FD-8264-4A8B-94AB-08735CB0B04C/data/Containers/Bundle/Application/97145C79-3910-4BA3-BE0C-A8A1B03EC9FC/friendy.app/app/get-contacts-worker.js'.
CONSOLE LOG file:///app/vendor.js:72635:24: === dump(): dumping members ===
	{
	    "line": 11850,
	    "column": 26,
	    "sourceURL": "file:///app/vendor.js",
	    "filename": "",
	    "lineno": 0,
	    "colno": 0
	}
	=== dump(): dumping function and properties names ===
	=== dump(): finished ===
```

Thanks again :)

**Comment by sis0k0** [comment]
On the first question:
The errors `'...ui/frame/frame.d.ts' is not a module`, etc. are caused by 'ui/frame' and 'ui/page' being ambient modules. This will probably be fixed in NativeScript 3.0. You can solve that by making the modules non-ambient in your `node_modules/tns-core-modules`. We haven't escalated the issue since we recommend using the webpack plugin and not plain ngc.
The errors `Property 'drawerOpening' does not exist...` probably appear because these properties are private in the component. If you are using them in your templates, they should be public (according to Angular's style guide).

On the second question:
All files you want to be included in your bundle, should be required somewhere in the app / webpack configuration. Generally, it doesn't matter where you'll require that file. A great place would be the `app/vendor.ts` file, though.

**Comment by abhayastudios** [comment]
A little clarification:

The plugin that I wrote has a web worker file called `node_modules/nativescript-contacts-lite/get-contacts-worker.js`. So any other user of the plugin would not have this knowledge that there are web-worker files in my plugin. 

Isn't there a way setting this in my plugin that webpack can pick up on including this without adding a reference in the app project? Or should I really just include a section in the README of my plugin for the user to manually add this?

Thanks again!

**Comment by abhayastudios** [comment]
I was able to solve it using triniwiz' version of the [worker-loader](https://github.com/triniwiz/worker-loader). Then conditionally loading the web worker JS files:

```
let worker = {};
if (global.TNS_WEBPACK) {
  let Worker = require("worker-loader!./get-contacts-worker.js");
  worker = new Worker;
} else { worker = new Worker('./get-contacts-worker.js'); }
```

**Comment by andipahlevy** [comment]
@abhayastudios 

I get an error too

'Error: Error: com.tns.NativeScriptException: Failed to find module: "./get-all-contacts-worker.js"

where should i place this code ?

let worker = {};
if (global.TNS_WEBPACK) {
  let Worker = require("worker-loader!./get-contacts-worker.js");
  worker = new Worker;
} else { worker = new Worker('./get-contacts-worker.js'); }

**Comment by sandoche** [comment]
I have also this error `JS: 'Error: Error: com.tns.NativeScriptException: Failed to find module: "./get-all-contacts-worker.js", relative to: app//` using `nativescript-contacts` on my NativeScript Vue project.

I am using it like this:
```
var contacts = require( "nativescript-contacts" )

export default async function getContacts () {
  var contactFields = ['name','phoneNumbers']
  contacts.getAllContacts(contactFields).then(function(args){
      console.log('getAllContacts Complete')
      console.log(JSON.stringify(args))
      /// Returns args:
      /// args.data: Generic cross platform JSON object, null if no contacts were found.
      /// args.reponse: "fetch"
  }, function(err){
      console.log("Error: " + err)
  })
}
```

**Comment by sandoche** [comment]
Actually I don't have any problem with 'nativescript-contacts-lite'
