### ISSUE TITLE
Packages.json not found during validating before-prepareJSApp

### ISSUE THREAD

**Issue by blaur** [NativeScript/nativescript-dev-webpack#879]
**Environment**
Node.js: 10.13.0 and NPM 6.5.0

My package.json
```
  "dependencies": {
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/router": "~7.2.0",
    "email-validator": "2.0.4",
    "moment": "2.24.0",
    "nativescript-angular": "^7.2.0",
    "nativescript-camera": "4.4.0",
    "nativescript-google-places": "0.0.3",
    "nativescript-iqkeyboardmanager": "1.4.0",
    "nativescript-loading-indicator": "2.5.1",
    "nativescript-plugin-firebase": "^7.5.0",
    "nativescript-pro-ui": "^3.4.1",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toolbox": "^3.0.1",
    "nativescript-web-image-cache": "5.0.0",
    "reflect-metadata": "~0.1.13",
    "rxjs": "^6.3.3",
    "rxjs-compat": "^6.5.1",
    "tns-core-modules": "^5.1.2",
    "webpack": "^4.0.0"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~7.2.0",
    "@ngtools/webpack": "~7.1.2",
    "@types/node": "~10.12.12",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "codelyzer": "5.0.1",
    "enhanced-resolve": "4.1.0",
    "filewalker": "0.1.3",
    "htmlparser2": "^3.10.1",
    "jasmine-core": "^3.4.0",
    "karma": "^4.1.0",
    "karma-jasmine": "^2.0.1",
    "karma-nativescript-launcher": "^0.4.0",
    "lazy": "1.0.11",
    "nativescript-css-loader": "^0.26.1",
    "nativescript-dev-typescript": "^0.9.0",
    "nativescript-dev-webpack": "^0.21.2",
    "tslint": "5.16.0",
    "typescript": "~3.1.1",
    "webpack-cli": "^3.3.1",
    "zone.js": "^0.8.4"
  }
```

**Describe the bug**
During tns build android, we are getting the following errors (not specific to firebase below but for all) where no package.json files are in the .bin file of all dependencies of my dependencies. The error occurs when the hook for nativescript-dev-webpack before-prepareJSApp is called:
module.exports = require("nativescript-dev-webpack/lib/before-prepareJS.js");

I've tried removing the firebase plugin and then I get the exactly same error on another dependency.
It is the following error we are getting:
```
Validating before-prepareJSApp arguments.
{ Error: ENOENT: no such file or directory, open 'C:\Users\bbl\Desktop\Brian\Development\instructor-app\platforms\android\app\src\main\assets\app\tns_modules\nativescript-plugin-firebase\node_modules\nativescript-hook\node_modules\.bin\package.json'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at FileSystem.readFile (C:\Users\bbl\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:171:19)
    at FileSystem.readText (C:\Users\bbl\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:181:21)
    at FileSystem.readJson (C:\Users\bbl\AppData\Roaming\npm\node_modules\nativescript\lib\common\file-system.js:184:27)
    at PluginsService.isNativeScriptPlugin (C:\Users\bbl\AppData\Roaming\npm\node_modules\nativescript\lib\services\plugins-service.js:189:51)
    at dependencies.forEach.d (C:\Users\bbl\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-dest-copy.js:50:42)
    at Array.forEach (<anonymous>)
    at TnsModulesCopy.removeDependenciesPlatformsDirs (C:\Users\bbl\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-dest-copy.js:47:18)
    at dependencies.forEach.d (C:\Users\bbl\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-dest-copy.js:53:22)
    at Array.forEach (<anonymous>)
    at TnsModulesCopy.removeDependenciesPlatformsDirs (C:\Users\bbl\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-dest-copy.js:47:18)
    at TnsModulesCopy.copyDependencyDir (C:\Users\bbl\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-dest-copy.js:37:18)
    at TnsModulesCopy.copyModules (C:\Users\bbl\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-dest-copy.js:25:18)
    at NodeModulesBuilder.initialPrepareNodeModules (C:\Users\bbl\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-builder.js:48:24)
    at NodeModulesBuilder.intialPrepareNodeModulesIfRequired (C:\Users\bbl\AppData\Roaming\npm\node_modules\nativescript\lib\tools\node-modules\node-modules-builder.js:36:18)
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path:
   'C:\\Users\\bbl\\Desktop\\Brian\\Development\\instructor-app\\platforms\\android\\app\\src\\main\\assets\\app\\tns_modules\\nativescript-plugin-firebase\\node_modules\\nativescript-hook\\node_modules\\.bin\\package.json' }
Processing node_modules failed. Error: ENOENT: no such file or directory, open 'C:\Users\bbl\Desktop\Brian\Development\instructor-app\platforms\android\app\src\main\assets\app\tns_modules\nativescript-plugin-firebase\node_modules\nativescript-hook\node_modules\.bin\package.json'
```

When trying to run with tns build android --bundle --env.aot I get the following:
`ERROR in The loader "C:\Users\bbl\Desktop\Brian\Development\instructor-app\app\pages\goalview\goalview.html" didn't return a string.`

If adding template rather than templateUrl it all works (at least for the --bundle build). Could that be related?
```
@Component({
    selector: "goal-modal-content",
    moduleId: module.id,
    //templateUrl: './goalview.html',
    template: "<Label class=\"material-icon\"\ [text]=\"hmmmmm\"></Label>",
    styleUrls: ["./goalview-common.css"],
    providers: [ GoalsListService, UserService ]
})
```

**To Reproduce**
tns build android with the above package.json

**Expected behavior**
The project to build.

**Comment by blaur** [comment]
I've posted it on stackoverflow instead so closing this.
https://stackoverflow.com/questions/56000885/packages-json-not-found-during-validating-before-preparejsapp
