### ISSUE TITLE
Provide configuration options for extending Activity & Application in Code Shared Project

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/nativescript-dev-webpack#906]
Scenario to resolve:
- Create a project with code sharing (web + mobile)
- Introduce the extended activity and application files (Android) and/or custom delegate files (iOS) written in TypeScript.
- Build with Webpack

Result: The build needs a custom resolve path for the extended files which are usually set in the `webpack.config.js` configuration file. However, in the case where the project is code-shared it won't resolve TypeScript files ([see this thread ](https://github.com/NativeScript/nativescript-schematics/issues/155#issuecomment-440173321)where we can only resolve plain JavaScript files)

Wanted feature:
- [ ] Provide means of either setting the resolve paths TypeScript files or automatically adding the provided extended files to the Webpack config.
- [ ] Document the feature and create code-shared example with extended Activity/Application (Android) + custom delegate file (iOS)

 Note:
As reported, the current tsconfig.json configuration is causing issue with the TypeScript compiler when thera are similar TypeScript files. The result TSC error is of kind:
```TypeScript
Error: C:\work\miira-user-frontend-2\src\app\activity.ts is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
    at AngularCompilerPlugin.getCompiledFile (C:\work\miira-user-frontend-2\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:752:23)
    at plugin.done.then (C:\work\miira-user-frontend-2\node_modules\@ngtools\webpack\src\loader.js:41:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 @ ./app/app.component.ts 18:19-40
 @ ./app/app.module.ts
 @ ./main.ts
```

Related to t.1408775

**Comment by NickIliev** [comment]
The above error is happening in Code-Shared project because the `tscongig.json` file sets some rules in **_exclude_** like
```JSON
    "exclude": [
        "**/*.tns.ts",
        "**/*.android.ts",
        "**/*.ios.ts",
        "**/*.spec.ts"
    ]
```

**Solution**

To overcome the issue and prevent excluding the extended activity & application files from being transpiled, we need to overwrite the **_exclude_** section

- Open the **_tsconfig.tns.json_** file and add the following exclude rule (so we can overwrite the one from the root **_tsconfig.json_** and in the same time apply the change only for the NativeScript project)

**_tsconfig.tns.json_**
```JSON
{
    "extends": "./tsconfig",
    "compilerOptions": {
        "module": "es2015",
        "moduleResolution": "node",
        "experimentalDecorators": true
    },
    "exclude": []
}

```
