### ISSUE TITLE
TypeError: nsWebpack.getConvertedExternals is not a function

### ISSUE THREAD

**Issue by devyaz** [NativeScript/nativescript-dev-webpack#923]
**Environment**
Provide version numbers for the following components (information can be retrieved by running `tns info` in your project folder or by inspecting the `package.json` of the project):
``# tns info
✔ Getting NativeScript components versions information...
✔ Component nativescript has 5.4.0 version and is up to date.
✔ Component tns-core-modules has 5.4.1 version and is up to date.
✔ Component tns-android has 5.4.0 version and is up to date.
⚠ Update available for component tns-ios. Your current version is 5.1.1 and the latest available version is 5.4.0.
``
 - CLI: 
 - Cross-platform modules:
 - Android Runtime:
 - iOS Runtime:
 - Plugin(s):
 - Node.js:
 
 - [ ] Please, attach your package.json and webpack.config.js as these configurations are usually critical for investigating issues with webpack
 

**Describe the bug**
before updating everything run/built fine 
 after updating to {N}5.4, i run ``tns run android``
 here's what i get 
```
tns run android --bundle
Skipping node_modules folder! Use the syncAllFiles option to sync files from this folder.
Searching for devices...
Running webpack for Android...
/home/martin/MalaChat/node_modules/webpack-cli/bin/cli.js:244
                                throw err;
                                ^

TypeError: nsWebpack.getConvertedExternals is not a function
    at module.exports.env (/home/martin/MalaChat/webpack.config.js:50:33)
    at handleFunction (/home/martin/MalaChat/node_modules/webpack-cli/bin/prepareOptions.js:23:13)
    at prepareOptions (/home/martin/MalaChat/node_modules/webpack-cli/bin/prepareOptions.js:9:5)
    at requireConfig (/home/martin/MalaChat/node_modules/webpack-cli/bin/convert-argv.js:136:14)
    at /home/martin/MalaChat/node_modules/webpack-cli/bin/convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/martin/MalaChat/node_modules/webpack-cli/bin/convert-argv.js:140:15)
    at yargs.parse (/home/martin/MalaChat/node_modules/webpack-cli/bin/cli.js:241:39)
    at Object.parse (/home/martin/MalaChat/node_modules/yargs/yargs.js:567:18)
    at /home/martin/MalaChat/node_modules/webpack-cli/bin/cli.js:219:8
    at Object.<anonymous> (/home/martin/MalaChat/node_modules/webpack-cli/bin/cli.js:538:3)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/martin/MalaChat/node_modules/webpack/bin/webpack.js:155:2)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:877:12)
    at internal/main/run_main_module.js:21:11
Executing webpack failed with exit code 1.
Cannot read property 'kill' of undefined
```

**To Reproduce**
update an app from 5.1.1 to 5.4(never used webpack before in {N})
app wont even run, tried removing platform then re-adding it back but still no luck 
**Expected behavior**
Should run normally

**Sample project**

**Additional context**
doesn't work on mobile or emulator

[package.txt](https://github.com/NativeScript/nativescript-dev-webpack/files/3249275/package.txt)
[webpack.config.txt](https://github.com/NativeScript/nativescript-dev-webpack/files/3249276/webpack.config.txt)

**Comment by rosen-vladimirov** [comment]
Hey @devyaz ,
Please excuse me for the late reply. It seems your `webpack.config.js` is updated, but your `nativescript-dev-webpack` is an old one. Can you please try updating both of them, i.e. execute the following:
```
npm i --save-dev nativescript-dev-webpack@next
./node_modules/.bin/update-ns-webpack --configs
tns run android
```
and see if it works?

**Comment by devyaz** [comment]
Thanks I updated and it now works
