### ISSUE TITLE
Webpack bundled app can't find modules when app is closed to run as a background service

### ISSUE THREAD

**Issue by devyaz** [NativeScript/nativescript-dev-webpack#952]
This is app runs when built in legacy it uses a background service to receive massages and other real-time content, but when bundled and the app is closed app crashes, it can't find modules required in NotificatinIntentService! I asked here  at SO https://stackoverflow.com/questions/56777821/webpack-bundle-cant-find-a-module-when-in-background ,```Error: com.tns.NativeScriptException: Failed to find module: "../db", relative to: app/notifications/```
this is NotificationIntentService.js 
```fore webpack it worked but bundling breaks the relative paths when app goes in the background for notifications from server. if i use legacy build it works but webpack beats me!

tried changing relative paths it doesn't work!

this is NotificationIntentService.js where it requires the modules needed for background communication(real time notifications and messages)

    onHandleIntent: function (intent) {
        var action = intent.getAction();
        if ("ACTION_START" == action) {
            processStartNotification();
        }
  android.support.v4.content.WakefulBroadcastReceiver.completeWakefulIntent(intent);
    }
});
const db=require("../db")
var LocalNotifications_1= require("nativescript-local-notifications");
var Vibrate = require("nativescript-vibrate").Vibrate;
var vibrator = new Vibrate();
var color_1 = require('tns-core-modules/color');
var dialogs_1 = require("tns-core-modules/ui/dialogs");
var model=require("../view");
var frameModule = require("tns-core-modules/ui/frame");
 model.checkStatus()
var io=require('../connection').io;
var iD=0
function processStartNotification() {
    // Do something. For example, fetch fresh data from backend to create a rich notification?
    var utils = require("tns-core-modules/utils/utils");
    var context = utils.ad.getApplicationContext();
    var ID=0;
}

function getDeleteIntent(context) {
        var intent = new android.content.Intent(context, com.tns.broadcastreceivers.NotificationEventReceiver.class);
        intent.setAction("ACTION_DELETE_NOTIFICATION");
        return android.app.PendingIntent.getBroadcast(context, 0, intent, android.app.PendingIntent.FLAG_UPDATE_CURRENT);
}
```

It seems after bundling paths can't be resolved while in background all others work while app is 'live'
*Replicate*
Create an app with a background service that requires modules like database, connection to server , when closed app set's an alarm service firing every 5 min, it shouldn't error.
I tried changing relative paths

**Comment by rosen-vladimirov** [comment]
Hey @devyaz ,
Can you please share a demo project reproducing this behavior? This will allow us to investigate this issue faster and provide more meaningful help.
Thanks in advance for your time!

**Comment by devyaz** [comment]
I'll do as soon as am near my Dev pc

**Comment by devyaz** [comment]
@rosen-vladimirov  here's the app attached just  ``tns install`` ,build and run then close app it should stay closed no errors in legacy but errors when bundled! Try setTimout to show a notification it should open the app when tapped
[github.zip](https://github.com/NativeScript/nativescript-dev-webpack/files/3335668/github.zip)

**Comment by DimitarTachev** [comment]
Hi @devyaz,

The issue is caused by the `webpack.config` which contains:

``` javascript
new CopyWebpackPlugin([
  { from: { glob: "fonts/**" } },
  { from: { glob: "**/*.jpg" } },
  { from: { glob: "**/*.png" } },
  { from: { glob: "notifications/**" } },
  { from: { glob: "activities/**" } },
  { from: { glob: "broadcastreceivers/**" } }
```

The `CopyWebpackPlugin` should be used only for static resources like image, fonts and databases.

The JavaScript files of the Android Services and Activities should be added in the `appComponents` array as shown below:

``` javascript
// Add your custom Activities, Services and other android app components here.
const appComponents = [
  "tns-core-modules/ui/frame",
  "tns-core-modules/ui/frame/activity",
  resolve(__dirname, "app/broadcastreceivers/NotificationEventReceiver"),
  resolve(__dirname, "app/broadcastreceivers/NotificationServiceStarterReceiver"),
  resolve(__dirname, "app/notifications/NotificationIntentService"),
  resolve(__dirname, "app/activities/NotificationActivity"),
    ];
```

P.S. Don't forget to update your `CopyWebpackPlugin` as follows:

``` javascript
new CopyWebpackPlugin([
  { from: { glob: "fonts/**" } },
  { from: { glob: "**/*.jpg" } },
  { from: { glob: "**/*.png" } }
```

**Comment by devyaz** [comment]
i made he changes, i get new error related to nativescript-vibrate plugin
in vendor.js
the line
```
  function Vibrate() {
        var _this = _super.call(this) || this;
        _this.service =
app.android.context.getSystemService(android.content.Context.VIBRATOR_SERVICE);
        return _this;
    }
```
the error:
```
System.err: TypeError: Cannot read property 'getSystemService' of undefined
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'Vibrate',
file:'file:///data/data/com.MalaChat.a
io/files/app/vendor.js', line: 4235, column: 45
System.err:     Frame: function:'./connection.js',
file:'file:///data/data/com.Ma
laChat.aio/files/app/bundle.js', line: 705, column: 17
System.err:     Frame: function:'__webpack_require__',
file:'file:///data/data/co
m.MalaChat.aio/files/app/runtime.js', line: 751, column: 30
System.err:     Frame: function:'fn',
file:'file:///data/data/com.MalaChat.aio/fi
les/app/runtime.js', line: 121, column: 20
System.err:     Frame:
function:'./notifications/NotificationIntentService.js', f
ile:'file:///data/data/com.MalaChat.aio/files/app/bundle.js', line: 1657,
column:
8
```

**Comment by devyaz** [comment]
@DimitarTachev @rosen-vladimirov  i made he changes, i get new error related to nativescript-vibrate plugin
in vendor.js
the line
``` function Vibrate() {
        var _this = _super.call(this) || this;
        _this.service =
app.android.context.getSystemService(android.content.Context.VIBRATOR_SERVICE);
        return _this;
    }
```
the error:
```
System.err: TypeError: Cannot read property 'getSystemService' of undefined
System.err: File: "<unknown>, line: 1, column: 265
System.err:
System.err: StackTrace:
System.err:     Frame: function:'Vibrate',
file:'file:///data/data/com.MalaChat.a
io/files/app/vendor.js', line: 4235, column: 45
System.err:     Frame: function:'./connection.js',
file:'file:///data/data/com.Ma
laChat.aio/files/app/bundle.js', line: 705, column: 17
System.err:     Frame: function:'__webpack_require__',
file:'file:///data/data/co
m.MalaChat.aio/files/app/runtime.js', line: 751, column: 30
System.err:     Frame: function:'fn',
file:'file:///data/data/com.MalaChat.aio/fi
les/app/runtime.js', line: 121, column: 20
System.err:     Frame:
function:'./notifications/NotificationIntentService.js', f
ile:'file:///data/data/com.MalaChat.aio/files/app/bundle.js', line: 1657,
column:
8
```

**Comment by DimitarTachev** [comment]
Hi @devyaz,

This error is thrown because the Bundle workflow requires the JavaScript files of the Android Services and Activities before the application start and you cannot use any application related code in the root scope of these files (the Vibrate class is using some methods from the `tns-core-modules` application which is not ready yet).

In other words, you should move the following lines:
``` JavaScript
const db = require("../db")
var LocalNotifications_1 = require("nativescript-local-notifications");
var Vibrate = require("nativescript-vibrate").Vibrate;
var vibrator = new Vibrate();
var color_1 = require('tns-core-modules/color');
var dialogs_1 = require("tns-core-modules/ui/dialogs");
var model = require("../view");
var frameModule = require("tns-core-modules/ui/frame");
model.checkStatus()
var io = require('../connection').io;
var iD = 0
```
somewhere in the service methods (e.g. in `processStartNotification`) in order to execute this code when the NativeScript application is ready.

**Comment by devyaz** [comment]
Ok I'll try this evening and report back

**Comment by devyaz** [comment]
@DimitarTachev @rosen-vladimirov  i followed your advice and now app starts fine but when closed this is what it throws
```JS: onReceive from alarm, starting notification service! thread: main
System.err: java.lang.RuntimeException: Unable to start service com.tns.notifications.NotificationIntentService@537c768 with Intent { act=ACTION_START cmp=com.MalaChat.aio/com.tns.notifications.NotificationIntentService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.app.IntentService$ServiceHandler.obtainMessage()' on a null object reference
System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3383)
System.err:     at android.app.ActivityThread.-wrap21(ActivityThread.java)
System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
System.err:     at android.os.Looper.loop(Looper.java:154)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:6236)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.app.IntentService$ServiceHandler.obtainMessage()' on a null object reference
System.err:     at android.app.IntentService.onStart(IntentService.java:119)
System.err:     at android.app.IntentService.onStartCommand(IntentService.java:133)
System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3366)
System.err:     ... 8 more
```
**webpack config**
```
const appComponents = [
        "tns-core-modules/ui/frame",
        "tns-core-modules/ui/frame/activity",
        resolve(__dirname, "app/broadcastreceivers/NotificationEventReceiver"),
        resolve(__dirname, "app/broadcastreceivers/NotificationServiceStarterReceiver"),
        resolve(__dirname, "app/notifications/NotificationIntentService"),
        resolve(__dirname, "app/activities/NotificationActivity"),
        resolve(__dirname, "app/service-helper"),
    ];

**Comment by DimitarTachev** [comment]
Hi @devyaz,

Thanks for updating us back!

We were getting the same exception with your app both with the Legacy and the Bundle workflow. Please open a new issue in the Android Runtime or ask a question in StackOverflow as this is not related with the Bundle workflow anymore.

**Comment by devyaz** [comment]
Now that you mentioned it even in legacy it's the same, before I submitted this issue I could run it without exceptions,even the APK I built before runs without exception it can receive notifications when closed! But after {N} 5.4 everything changed so am very positive it's got everything to do with either {N} or we pack, I'll downgrade and try again then upgrade but run/build in legacy then report

**Comment by devyaz** [comment]
@rosen-vladimirov @DimitarTachev  i downgraded to 5.3.4 and everything worked i got notifications while app closed, an hour ago i upgrades to {N}5.4.2
 ```tns platform remove android```
 then ```./node_modules/.bin/update-ns-webpack --deps --config```
then ```tns update```
then ```tns run android --bundle```

guess what when app closed? 
```JS:  trying to set alarm!!
JS: gone awol
JS: onReceive from alarm, starting notification service! thread: main
System.err: java.lang.RuntimeException: Unable to start service com.tns.notifications.NotificationIntentService@ee179c5 with Intent { act=ACTION_START cmp=com.MalaChat.aio/com.tns.notifications.NotificationIntentService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Message android.app.IntentService$ServiceHandler.obtainMessage()' on a null object reference
System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3383)
```

so am positive its got to do with webpack/ or {N}5.4.2 now after upgrading even legacy throws an exception

**Comment by devyaz** [comment]
last options? otherwise am good to revert to old {N}5.3.4

**Comment by devyaz** [comment]
Here is what I have found out, if I downgrade to {N}5.3.4 and use webpack app runs as expected so it could be {N} 5.4 that's not working with Android services when app closed

**Comment by DimitarTachev** [comment]
Hi @devyaz,

Thanks for the additional details!

After a further investigation with the NativeScript Android runtime team, we found out that the issue is caused by a missing `onCreate` method in your `NotificationIntentService`. Could you try updating the service as follows:
```JavaScript
com.pip3r4o.android.app.IntentService.extend("com.tns.notifications.NotificationIntentService", {

    onCreate: function () {
        this.super.onCreate();
    },

    onHandleIntent: function (intent) {
        var action = intent.getAction();
        if ("ACTION_START" == action) {
            processStartNotification();
        }

        android.support.v4.content.WakefulBroadcastReceiver.completeWakefulIntent(intent);
    }
});
```
and update us back?

P.S. We are still investigating why is this working with Android Runtime 5.3.4 and we highly recommend you to update the runtime as we have a few important fixes related to the Android Background services (e.g. https://github.com/NativeScript/android-runtime/issues/1347).

**Comment by devyaz** [comment]
``` tns doctor
✔ Getting environment information 

No issues were detected.
✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Local builds for iOS can be executed only on a macOS system. To build for iOS on a different operating system, you can use the NativeScript cloud infrastructure.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 6.0.0 version and is up to date.
✔ Component tns-core-modules has 6.0.1 version and is up to date.
✔ Component tns-android has 6.0.0 version and is up to date.
✔ Component tns-ios has 6.0.1 version and is up to date.
```
i migrated to {N}6 and updated ``NotificationIntenService`` as you stated, now a new exception point to ``/broadcastreceivers/NotificationEventReceiver.js`` line 1

```
android.support.v4.content.WakefulBroadcastReceiver.extend("com.tns.broadcastreceivers.NotificationEventReceiver", {
    onReceive: function (context, intent) {
        var action = intent.getAction();
        var serviceIntent = null;
        if ("ACTION_START_NOTIFICATION_SERVICE" == action) {
            console.log("onReceive from alarm, starting notification service! thread: " + java.lang.Thread.currentThread().getName());
            serviceIntent = createIntentStartNotificationService(context);
        } else if ("ACTION_DELETE_NOTIFICATION" == action) {
            console.log("onReceive delete notification action, starting notification service to handle delete");
            serviceIntent = createIntentDeleteNotification(context);
        }

        if (serviceIntent) {
            android.support.v4.content.WakefulBroadcastReceiver.startWakefulService(context, serviceIntent);
        }
    }
})

var Intent = android.content.Intent;


function createIntentStartNotificationService(context) {
    var intent = new Intent(context, com.tns.notifications.NotificationIntentService.class);
    intent.setAction("ACTION_START");
    return intent;
}

function createIntentDeleteNotification(context) {
    var intent = new Intent(context, com.tns.notifications.NotificationIntentService.class);
    intent.setAction("ACTION_DELETE");
    return intent;
}
```
**Heres the exception**
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: Error calling module function 
System.err: TypeError: Cannot read property 'WakefulBroadcastReceiver' of undefined
System.err: File: "file:///app/broadcastreceivers/NotificationEventReceiver.js:1:0
System.err: 
System.err: StackTrace: 
System.err:     Frame: function:'', file:'file:///app/broadcastreceivers/NotificationEventReceiver.js:1:0
System.err:     Frame: function:'./broadcastreceivers/NotificationEventReceiver.js', file:'file:///data/data/com.MalaChat.aio/files/app/bundle.js', line: 668, column: 30......
```
i tried removing the platforms and re-adding, reconfig webpack ``./node_modules/.bin/update-ns-webpack --deps --config
`` webpack is ver-1.0.1 
[package.json.txt](https://github.com/NativeScript/nativescript-dev-webpack/files/3406470/package.json.txt)

**Comment by DimitarTachev** [comment]
One of the biggest changes in NativeScript 6.0.0 is the AndroidX support (the Android Support Library is replaced with the new AndroidX one) - read [here ](https://www.nativescript.org/blog/migrating-nativescript-plugins-to-androidx)for more details.

I also suggest you take a look at the [Migrating to NativeScript 6.0](https://www.nativescript.org/blog/nativescript-6.0-application-migration) blog post.

Regarding the `'WakefulBroadcastReceiver' of undefined` exception, just follow the [AndroidX migration guide](https://developer.android.com/jetpack/androidx/migrate) and replace `android.support.v4.content.WakefulBroadcastReceiver` with `androidx.legacy.content.WakefulBroadcastReceiver`.

**Comment by devyaz** [comment]
@DimitarTachev you are awesome and the whole {N} Team, i had to do ``androidx.legacy.content`` in 2 files, ``NotificationIntentService.js and NotificationEventReceiver`` now {N}6 app is rocking
How do i Mark as **SOLVED**
