### ISSUE TITLE
Sass imports on scss files failing

### ISSUE THREAD

**Issue by Jonatthu** [NativeScript/nativescript-dev-webpack#98]
I have `@import './sign-in.component.common.scss';` on my` sign-in.component.(android||ios).scss` files and this is failing my webpack config is...

```
var webpack = require("webpack");
var nsWebpack = require("nativescript-dev-webpack");
var nativescriptTarget = require("nativescript-dev-webpack/nativescript-target");
var path = require("path");
var CopyWebpackPlugin = require("copy-webpack-plugin");
var ExtractTextPlugin = require("extract-text-webpack-plugin");
var AotPlugin = require("@ngtools/webpack").AotPlugin;

module.exports = function (platform, destinationApp) {
    if (!destinationApp) {
        //Default destination inside platforms/<platform>/...
        destinationApp = nsWebpack.getAppPath(platform);
    }
    var entry = {};
    //Discover entry module from package.json
    entry.bundle = "./" + nsWebpack.getEntryModule();
    //Vendor entry with third party libraries.
    entry.vendor = "./vendor";

    var plugins = [
        //Vendor libs go to the vendor.js chunk
        new webpack.optimize.CommonsChunkPlugin({
            name: ["vendor"]
        }),
        //Define useful constants like TNS_WEBPACK
        new webpack.DefinePlugin({
            "global.TNS_WEBPACK": "true",
        }),
        //Copy assets to out dir. Add your own globs as needed.
        new CopyWebpackPlugin([
            { from: "css/**" },
            { from: "fonts/**" },
            { from: "**/*.jpg" },
            { from: "**/*.png" },
            { from: "**/*.xml" },
        ], { ignore: ["App_Resources/**"] }),
        //Generate a bundle starter script and activate it in package.json
        new nsWebpack.GenerateBundleStarterPlugin([
            "./vendor",
            "./bundle",
        ]),

        //Angular AOT compiler
        new AotPlugin({
            tsConfigPath: "tsconfig.aot.json",
            entryModule: path.resolve(__dirname, "app/app.module#AppModule"),
            typeChecking: false
        }),
        new nsWebpack.StyleUrlResolvePlugin({platform}),
    ];

    if (process.env.npm_config_uglify) {
        plugins.push(new webpack.LoaderOptionsPlugin({
            minimize: true
        }));

        //Work around an Android issue by setting compress = false
        var compress = platform !== "android";
        plugins.push(new webpack.optimize.UglifyJsPlugin({
            mangle: {
                except: nsWebpack.uglifyMangleExcludes,
            },
            compress: compress,
        }));
    }

    return {
        context: path.resolve("./app"),
        target: nativescriptTarget,
        entry: entry,
        output: {
            pathinfo: true,
            path: path.resolve(destinationApp),
            libraryTarget: "commonjs2",
            filename: "[name].js",
        },
        resolve: {
            //Resolve platform-specific modules like module.android.js
            extensions: [
                ".aot.ts",
                ".ts",
                ".js",
                ".css",
                "." + platform + ".ts",
                "." + platform + ".js",
                "." + platform + ".css",
            ],
            //Resolve {N} system modules from tns-core-modules
            modules: [
                "node_modules/tns-core-modules",
                "node_modules"
            ]
        },
        node: {
            //Disable node shims that conflict with NativeScript
            "http": false,
            "timers": false,
            "setImmediate": false,
            "fs": "empty",
        },
        module: {
            loaders: [
                {
                    test: /\.html$|\.xml$/,
                    loaders: [
                        "raw-loader",
                    ]
                },
                // Compile TypeScript files with ahead-of-time compiler.
                {
                    test: /\.ts$/,
                    loaders: [
                        "nativescript-dev-webpack/tns-aot-loader",
                        "@ngtools/webpack",
                    ]
                },
                // SASS support
                {
                    test: /\.scss$/,
                    loaders: [
                        "raw-loader",
                        "resolve-url-loader",
                        "sass-loader"
                    ]
                },
            ]
        },
        plugins: plugins,
    };
};
```

the error:

```
Child app/pages/sign-in/sign-in.component.html:
       [0] ./pages/sign-in/sign-in.component.html 1.09 kB {0} [built]
Child app/pages/sign-in/sign-in.component.ios.scss:
       [0] ./pages/sign-in/sign-in.component.ios.scss 1.02 kB {0} [built]
Running tns run...
Executing before-prepare hook from /Users/jonatthu/Desktop/CrossPlaftform/nativescript/hooks/before-prepare/native
script-dev-android-snapshot.js
Executing before-prepare hook from /Users/jonatthu/Desktop/CrossPlaftform/nativescript/hooks/before-prepare/native
script-dev-sass.js
/Users/jonatthu/Desktop/CrossPlaftform/nativescript/app/pages/sign-in/sign-in.component.android.scss SASS CSS pre-
processing failed. Error: Error: File to import not found or unreadable: ./sign-in.component.common.scss.
Parent style sheet: stdin
child process exited with code 127
```

**Comment by Jonatthu** [comment]
```
Users/jonatthu/Desktop/CrossPlaftform/nativescript/app/pages/sign-in/sign-in.component.ios.scss SASS CSS pre-proc
essing failed. Error: Error: File to import not found or unreadable: ./_sign-in.component.common.scss.
Parent style sheet: stdin
child process exited with code 127
```

**Comment by TeddyBo** [comment]
Have the same issue

**Comment by jwuliger** [comment]
Ok thank god I am not the only one with this problem. 

Here is what I get:

```
> npm run ns-bundle --android --start-app


> @ ns-bundle D:\PaMe\Mobile\pame-mobile
> ns-bundle

Running webpack for android...
D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:14876
            var sourceFile = new SourceFileConstructor(263 /* SourceFile */, /*pos*/ 0, /* end */ sourceText.length);
                                                                                                            ^

TypeError: Cannot read property 'length' of undefined
    at createSourceFile (D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:14876:109)
    at parseSourceFileWorker (D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:14808:26)
    at Object.parseSourceFile (D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:14757:26)
    at Object.createSourceFile (D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:14612:29)
    at WebpackCompilerHost.getSourceFile (D:\PaMe\Mobile\pame-mobile\node_modules\@ngtools\webpack\src\compiler_host.js:210:27)
    at findSourceFile (D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:64751:29)
    at processSourceFile (D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:64682:27)
    at D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:64792:17
    at Object.forEach (D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:1398:30)
    at processReferencedFiles (D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:64790:16)
    at findSourceFile (D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:64775:21)
    at processSourceFile (D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:64682:27)
    at processRootFile (D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:64570:13)
    at D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:63919:60
    at Object.forEach (D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:1398:30)
    at Object.createProgram (D:\PaMe\Mobile\pame-mobile\node_modules\typescript\lib\typescript.js:63919:16)
child process exited with code 1
```

**Comment by sis0k0** [comment]
Hey there,

Sorry for the late reply. We'll investigate this issue. Can you attach a sample project?

**Comment by sis0k0** [comment]
Hey, 

I couldn't reproduce your issue.  Here's a working app:
[sassTest.zip](https://github.com/NativeScript/nativescript-dev-webpack/files/964684/sassTest.zip)

**Comment by manojdcoder** [comment]
@sis0k0 Web pack fails when I introduce platform specific app.css (app.<platform>.css) using [sass](https://docs.nativescript.org/ui/theme#sass-usage). Any idea how I can fix this pls?

**Comment by sis0k0** [comment]
@manojdcoder how does it fail? Note that the webpack configuration needs to be updated if you want to use app stylesheet with a different name. In your case: 

` entry["app.css"] = "app.css"; ` --> ``` entry[`app.${platform}.css`] = `./app.${platform}.css`; ```

```
    new CopyWebpackPlugin([
            { from: `app.css` },
...
```

-->

```
    new CopyWebpackPlugin([
            { from: `app.${platform}.css` },
...
```

I'm attaching a sample project. [sassTest.zip](https://github.com/NativeScript/nativescript-dev-webpack/files/967846/sassTest.zip)
Edit: I decided to upload it, too: https://github.com/sis0k0/nativescript-webpack-sass.

**Comment by manojdcoder** [comment]
@sis0k0 I almost figured out that was the issue but didn't know how to fix that being new to angular and web pack. Thanks a lot for the sample project, will try that.

**Comment by manojdcoder** [comment]
@sis0k0 Thanks a lot for your support. I have last one or two errors. Unable to find what is the issue, do you guess what is this?

I'm using `nativescript-i18n` plugin in the project, not sure whether the problem is that one or the `main.aot.ts`

```
ERROR in Error encountered resolving symbol values statically. Reference to a non-exported class L. Consider exporting the class (position 15:1 in the original .ts file), resolving symbol NativeScriptI18nModule in /Users/manojkumar/Backup/NativeScript_Workspace/magpi-hybrid-new/node_modules/nativescript-i18n/angular.ts

ERROR in ./main.aot.ts
Module not found: Error: Can't resolve './app.module.ngfactory' in '/Users/manojkumar/Backup/NativeScript_Workspace/magpi-hybrid-new/app'
 @ ./main.aot.ts 4:29-62
```

**Comment by sis0k0** [comment]
Open a new issue, please

**Comment by xmlking** [comment]
@sis0k0 generated css files i.e., `app.android.css`  are checked-in in  your sample app: https://github.com/sis0k0/nativescript-webpack-sass 
What if I don't have those files generated, when I first time start the app? Should I generate them with some other command before running this command?
`npm run start-android-bundle`
I am getting error:
```
ERROR in Entry module not found: Error: Can't resolve './app.android.css' in '/dev/nativescript-webpack-sass/app'

ERROR in [copy-webpack-plugin] unable to locate 'app.android.css' at '/dev/nativescript-webpack-sass/app/app.android.css'
```

**Comment by julienbiaussat** [comment]
same problem :
o	TypeError: Cannot read property 'length' of undefined : at createSourceFile (C:_DATA\RENAULT\CADRAGE\GIT\Cadrage\node_modules\typescript\lib\typescript.js:14876:109)
I just played with environment.ts adding a baseURL :
export const env = {
production: false,
baseUrl: 'http://localhost:8080/api'
};
but the file was not found in my login service :
import { env } from '../environments/environment';
so I moved it one directory up to test, and it was ok
import { env } from '../environment';

I don't see relation with the bug ???

**Comment by julienbiaussat** [comment]
main.ts -> wrong path : import { environment } from './environments/environment';  
because I moved environment.ts.... pfff
